// Code generated by ent, DO NOT EDIT.

package reportrun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/iWorld-y/domain_radar/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ReportRun {
	return predicate.ReportRun(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ReportRun {
	return predicate.ReportRun(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ReportRun {
	return predicate.ReportRun(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ReportRun {
	return predicate.ReportRun(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ReportRun {
	return predicate.ReportRun(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ReportRun {
	return predicate.ReportRun(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ReportRun {
	return predicate.ReportRun(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ReportRun {
	return predicate.ReportRun(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ReportRun {
	return predicate.ReportRun(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ReportRun {
	return predicate.ReportRun(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ReportRun {
	return predicate.ReportRun(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ReportRun {
	return predicate.ReportRun(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ReportRun {
	return predicate.ReportRun(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ReportRun {
	return predicate.ReportRun(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ReportRun {
	return predicate.ReportRun(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ReportRun {
	return predicate.ReportRun(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ReportRun {
	return predicate.ReportRun(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ReportRun {
	return predicate.ReportRun(sql.FieldLTE(FieldCreatedAt, v))
}

// HasDomainReports applies the HasEdge predicate on the "domain_reports" edge.
func HasDomainReports() predicate.ReportRun {
	return predicate.ReportRun(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DomainReportsTable, DomainReportsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDomainReportsWith applies the HasEdge predicate on the "domain_reports" edge with a given conditions (other predicates).
func HasDomainReportsWith(preds ...predicate.DomainReport) predicate.ReportRun {
	return predicate.ReportRun(func(s *sql.Selector) {
		step := newDomainReportsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDeepAnalysisResults applies the HasEdge predicate on the "deep_analysis_results" edge.
func HasDeepAnalysisResults() predicate.ReportRun {
	return predicate.ReportRun(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DeepAnalysisResultsTable, DeepAnalysisResultsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeepAnalysisResultsWith applies the HasEdge predicate on the "deep_analysis_results" edge with a given conditions (other predicates).
func HasDeepAnalysisResultsWith(preds ...predicate.DeepAnalysisResult) predicate.ReportRun {
	return predicate.ReportRun(func(s *sql.Selector) {
		step := newDeepAnalysisResultsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReportRun) predicate.ReportRun {
	return predicate.ReportRun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReportRun) predicate.ReportRun {
	return predicate.ReportRun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReportRun) predicate.ReportRun {
	return predicate.ReportRun(sql.NotPredicates(p))
}
