// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/transport/http"
	"github.com/iWorld-y/domain_radar/app/display/internal/conf"
	"github.com/iWorld-y/domain_radar/app/display/internal/data"
	"github.com/iWorld-y/domain_radar/app/display/internal/server"
	"github.com/iWorld-y/domain_radar/app/display/internal/service"
	"github.com/iWorld-y/domain_radar/app/display/internal/usecase"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, radar *conf.Radar, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := usecase.NewUserUseCase(userRepo, auth, logger)
	reportRepo := data.NewReportRepo(dataData, logger)
	reportUseCase := usecase.NewReportUseCase(reportRepo, logger)
	engine, cleanup2, err := server.NewRadarEngine(radar, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	displayService := service.NewDisplayService(userUseCase, reportUseCase, logger, engine)
	httpServer := server.NewHTTPServer(confServer, auth, displayService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func newApp(logger log.Logger, hs *http.Server) *kratos.App {
	return kratos.New(kratos.ID(id), kratos.Name(Name), kratos.Version(Version), kratos.Metadata(map[string]string{}), kratos.Logger(logger), kratos.Server(hs))
}
