// Code generated by ent, DO NOT EDIT.

package keyevent

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the keyevent type in the database.
	Label = "key_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDomainReportID holds the string denoting the domain_report_id field in the database.
	FieldDomainReportID = "domain_report_id"
	// FieldEventContent holds the string denoting the event_content field in the database.
	FieldEventContent = "event_content"
	// EdgeDomainReport holds the string denoting the domain_report edge name in mutations.
	EdgeDomainReport = "domain_report"
	// Table holds the table name of the keyevent in the database.
	Table = "key_events"
	// DomainReportTable is the table that holds the domain_report relation/edge.
	DomainReportTable = "key_events"
	// DomainReportInverseTable is the table name for the DomainReport entity.
	// It exists in this package in order to avoid circular dependency with the "domainreport" package.
	DomainReportInverseTable = "domain_reports"
	// DomainReportColumn is the table column denoting the domain_report relation/edge.
	DomainReportColumn = "domain_report_id"
)

// Columns holds all SQL columns for keyevent fields.
var Columns = []string{
	FieldID,
	FieldDomainReportID,
	FieldEventContent,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the KeyEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDomainReportID orders the results by the domain_report_id field.
func ByDomainReportID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDomainReportID, opts...).ToFunc()
}

// ByEventContent orders the results by the event_content field.
func ByEventContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventContent, opts...).ToFunc()
}

// ByDomainReportField orders the results by domain_report field.
func ByDomainReportField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDomainReportStep(), sql.OrderByField(field, opts...))
	}
}
func newDomainReportStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DomainReportInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DomainReportTable, DomainReportColumn),
	)
}
