// Code generated by ent, DO NOT EDIT.

package keyevent

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/iWorld-y/domain_radar/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldLTE(FieldID, id))
}

// DomainReportID applies equality check predicate on the "domain_report_id" field. It's identical to DomainReportIDEQ.
func DomainReportID(v int) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldEQ(FieldDomainReportID, v))
}

// EventContent applies equality check predicate on the "event_content" field. It's identical to EventContentEQ.
func EventContent(v string) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldEQ(FieldEventContent, v))
}

// DomainReportIDEQ applies the EQ predicate on the "domain_report_id" field.
func DomainReportIDEQ(v int) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldEQ(FieldDomainReportID, v))
}

// DomainReportIDNEQ applies the NEQ predicate on the "domain_report_id" field.
func DomainReportIDNEQ(v int) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldNEQ(FieldDomainReportID, v))
}

// DomainReportIDIn applies the In predicate on the "domain_report_id" field.
func DomainReportIDIn(vs ...int) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldIn(FieldDomainReportID, vs...))
}

// DomainReportIDNotIn applies the NotIn predicate on the "domain_report_id" field.
func DomainReportIDNotIn(vs ...int) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldNotIn(FieldDomainReportID, vs...))
}

// DomainReportIDIsNil applies the IsNil predicate on the "domain_report_id" field.
func DomainReportIDIsNil() predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldIsNull(FieldDomainReportID))
}

// DomainReportIDNotNil applies the NotNil predicate on the "domain_report_id" field.
func DomainReportIDNotNil() predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldNotNull(FieldDomainReportID))
}

// EventContentEQ applies the EQ predicate on the "event_content" field.
func EventContentEQ(v string) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldEQ(FieldEventContent, v))
}

// EventContentNEQ applies the NEQ predicate on the "event_content" field.
func EventContentNEQ(v string) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldNEQ(FieldEventContent, v))
}

// EventContentIn applies the In predicate on the "event_content" field.
func EventContentIn(vs ...string) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldIn(FieldEventContent, vs...))
}

// EventContentNotIn applies the NotIn predicate on the "event_content" field.
func EventContentNotIn(vs ...string) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldNotIn(FieldEventContent, vs...))
}

// EventContentGT applies the GT predicate on the "event_content" field.
func EventContentGT(v string) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldGT(FieldEventContent, v))
}

// EventContentGTE applies the GTE predicate on the "event_content" field.
func EventContentGTE(v string) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldGTE(FieldEventContent, v))
}

// EventContentLT applies the LT predicate on the "event_content" field.
func EventContentLT(v string) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldLT(FieldEventContent, v))
}

// EventContentLTE applies the LTE predicate on the "event_content" field.
func EventContentLTE(v string) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldLTE(FieldEventContent, v))
}

// EventContentContains applies the Contains predicate on the "event_content" field.
func EventContentContains(v string) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldContains(FieldEventContent, v))
}

// EventContentHasPrefix applies the HasPrefix predicate on the "event_content" field.
func EventContentHasPrefix(v string) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldHasPrefix(FieldEventContent, v))
}

// EventContentHasSuffix applies the HasSuffix predicate on the "event_content" field.
func EventContentHasSuffix(v string) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldHasSuffix(FieldEventContent, v))
}

// EventContentIsNil applies the IsNil predicate on the "event_content" field.
func EventContentIsNil() predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldIsNull(FieldEventContent))
}

// EventContentNotNil applies the NotNil predicate on the "event_content" field.
func EventContentNotNil() predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldNotNull(FieldEventContent))
}

// EventContentEqualFold applies the EqualFold predicate on the "event_content" field.
func EventContentEqualFold(v string) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldEqualFold(FieldEventContent, v))
}

// EventContentContainsFold applies the ContainsFold predicate on the "event_content" field.
func EventContentContainsFold(v string) predicate.KeyEvent {
	return predicate.KeyEvent(sql.FieldContainsFold(FieldEventContent, v))
}

// HasDomainReport applies the HasEdge predicate on the "domain_report" edge.
func HasDomainReport() predicate.KeyEvent {
	return predicate.KeyEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DomainReportTable, DomainReportColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDomainReportWith applies the HasEdge predicate on the "domain_report" edge with a given conditions (other predicates).
func HasDomainReportWith(preds ...predicate.DomainReport) predicate.KeyEvent {
	return predicate.KeyEvent(func(s *sql.Selector) {
		step := newDomainReportStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.KeyEvent) predicate.KeyEvent {
	return predicate.KeyEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.KeyEvent) predicate.KeyEvent {
	return predicate.KeyEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.KeyEvent) predicate.KeyEvent {
	return predicate.KeyEvent(sql.NotPredicates(p))
}
