// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iWorld-y/domain_radar/app/common/ent/actionguide"
	"github.com/iWorld-y/domain_radar/app/common/ent/deepanalysisresult"
)

// ActionGuideCreate is the builder for creating a ActionGuide entity.
type ActionGuideCreate struct {
	config
	mutation *ActionGuideMutation
	hooks    []Hook
}

// SetDeepAnalysisID sets the "deep_analysis_id" field.
func (_c *ActionGuideCreate) SetDeepAnalysisID(v int) *ActionGuideCreate {
	_c.mutation.SetDeepAnalysisID(v)
	return _c
}

// SetNillableDeepAnalysisID sets the "deep_analysis_id" field if the given value is not nil.
func (_c *ActionGuideCreate) SetNillableDeepAnalysisID(v *int) *ActionGuideCreate {
	if v != nil {
		_c.SetDeepAnalysisID(*v)
	}
	return _c
}

// SetGuideContent sets the "guide_content" field.
func (_c *ActionGuideCreate) SetGuideContent(v string) *ActionGuideCreate {
	_c.mutation.SetGuideContent(v)
	return _c
}

// SetNillableGuideContent sets the "guide_content" field if the given value is not nil.
func (_c *ActionGuideCreate) SetNillableGuideContent(v *string) *ActionGuideCreate {
	if v != nil {
		_c.SetGuideContent(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ActionGuideCreate) SetID(v int) *ActionGuideCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetDeepAnalysisResultID sets the "deep_analysis_result" edge to the DeepAnalysisResult entity by ID.
func (_c *ActionGuideCreate) SetDeepAnalysisResultID(id int) *ActionGuideCreate {
	_c.mutation.SetDeepAnalysisResultID(id)
	return _c
}

// SetNillableDeepAnalysisResultID sets the "deep_analysis_result" edge to the DeepAnalysisResult entity by ID if the given value is not nil.
func (_c *ActionGuideCreate) SetNillableDeepAnalysisResultID(id *int) *ActionGuideCreate {
	if id != nil {
		_c = _c.SetDeepAnalysisResultID(*id)
	}
	return _c
}

// SetDeepAnalysisResult sets the "deep_analysis_result" edge to the DeepAnalysisResult entity.
func (_c *ActionGuideCreate) SetDeepAnalysisResult(v *DeepAnalysisResult) *ActionGuideCreate {
	return _c.SetDeepAnalysisResultID(v.ID)
}

// Mutation returns the ActionGuideMutation object of the builder.
func (_c *ActionGuideCreate) Mutation() *ActionGuideMutation {
	return _c.mutation
}

// Save creates the ActionGuide in the database.
func (_c *ActionGuideCreate) Save(ctx context.Context) (*ActionGuide, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ActionGuideCreate) SaveX(ctx context.Context) *ActionGuide {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActionGuideCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActionGuideCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ActionGuideCreate) check() error {
	return nil
}

func (_c *ActionGuideCreate) sqlSave(ctx context.Context) (*ActionGuide, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ActionGuideCreate) createSpec() (*ActionGuide, *sqlgraph.CreateSpec) {
	var (
		_node = &ActionGuide{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(actionguide.Table, sqlgraph.NewFieldSpec(actionguide.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.GuideContent(); ok {
		_spec.SetField(actionguide.FieldGuideContent, field.TypeString, value)
		_node.GuideContent = value
	}
	if nodes := _c.mutation.DeepAnalysisResultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   actionguide.DeepAnalysisResultTable,
			Columns: []string{actionguide.DeepAnalysisResultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deepanalysisresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DeepAnalysisID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ActionGuideCreateBulk is the builder for creating many ActionGuide entities in bulk.
type ActionGuideCreateBulk struct {
	config
	err      error
	builders []*ActionGuideCreate
}

// Save creates the ActionGuide entities in the database.
func (_c *ActionGuideCreateBulk) Save(ctx context.Context) ([]*ActionGuide, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ActionGuide, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ActionGuideMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ActionGuideCreateBulk) SaveX(ctx context.Context) []*ActionGuide {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActionGuideCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActionGuideCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
