// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/iWorld-y/domain_radar/app/common/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/iWorld-y/domain_radar/app/common/ent/actionguide"
	"github.com/iWorld-y/domain_radar/app/common/ent/article"
	"github.com/iWorld-y/domain_radar/app/common/ent/deepanalysisresult"
	"github.com/iWorld-y/domain_radar/app/common/ent/domainreport"
	"github.com/iWorld-y/domain_radar/app/common/ent/keyevent"
	"github.com/iWorld-y/domain_radar/app/common/ent/reportrun"
	"github.com/iWorld-y/domain_radar/app/common/ent/user"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// ActionGuide is the client for interacting with the ActionGuide builders.
	ActionGuide *ActionGuideClient
	// Article is the client for interacting with the Article builders.
	Article *ArticleClient
	// DeepAnalysisResult is the client for interacting with the DeepAnalysisResult builders.
	DeepAnalysisResult *DeepAnalysisResultClient
	// DomainReport is the client for interacting with the DomainReport builders.
	DomainReport *DomainReportClient
	// KeyEvent is the client for interacting with the KeyEvent builders.
	KeyEvent *KeyEventClient
	// ReportRun is the client for interacting with the ReportRun builders.
	ReportRun *ReportRunClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.ActionGuide = NewActionGuideClient(c.config)
	c.Article = NewArticleClient(c.config)
	c.DeepAnalysisResult = NewDeepAnalysisResultClient(c.config)
	c.DomainReport = NewDomainReportClient(c.config)
	c.KeyEvent = NewKeyEventClient(c.config)
	c.ReportRun = NewReportRunClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		ActionGuide:        NewActionGuideClient(cfg),
		Article:            NewArticleClient(cfg),
		DeepAnalysisResult: NewDeepAnalysisResultClient(cfg),
		DomainReport:       NewDomainReportClient(cfg),
		KeyEvent:           NewKeyEventClient(cfg),
		ReportRun:          NewReportRunClient(cfg),
		User:               NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		ActionGuide:        NewActionGuideClient(cfg),
		Article:            NewArticleClient(cfg),
		DeepAnalysisResult: NewDeepAnalysisResultClient(cfg),
		DomainReport:       NewDomainReportClient(cfg),
		KeyEvent:           NewKeyEventClient(cfg),
		ReportRun:          NewReportRunClient(cfg),
		User:               NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		ActionGuide.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.ActionGuide, c.Article, c.DeepAnalysisResult, c.DomainReport, c.KeyEvent,
		c.ReportRun, c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.ActionGuide, c.Article, c.DeepAnalysisResult, c.DomainReport, c.KeyEvent,
		c.ReportRun, c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ActionGuideMutation:
		return c.ActionGuide.mutate(ctx, m)
	case *ArticleMutation:
		return c.Article.mutate(ctx, m)
	case *DeepAnalysisResultMutation:
		return c.DeepAnalysisResult.mutate(ctx, m)
	case *DomainReportMutation:
		return c.DomainReport.mutate(ctx, m)
	case *KeyEventMutation:
		return c.KeyEvent.mutate(ctx, m)
	case *ReportRunMutation:
		return c.ReportRun.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ActionGuideClient is a client for the ActionGuide schema.
type ActionGuideClient struct {
	config
}

// NewActionGuideClient returns a client for the ActionGuide from the given config.
func NewActionGuideClient(c config) *ActionGuideClient {
	return &ActionGuideClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `actionguide.Hooks(f(g(h())))`.
func (c *ActionGuideClient) Use(hooks ...Hook) {
	c.hooks.ActionGuide = append(c.hooks.ActionGuide, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `actionguide.Intercept(f(g(h())))`.
func (c *ActionGuideClient) Intercept(interceptors ...Interceptor) {
	c.inters.ActionGuide = append(c.inters.ActionGuide, interceptors...)
}

// Create returns a builder for creating a ActionGuide entity.
func (c *ActionGuideClient) Create() *ActionGuideCreate {
	mutation := newActionGuideMutation(c.config, OpCreate)
	return &ActionGuideCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ActionGuide entities.
func (c *ActionGuideClient) CreateBulk(builders ...*ActionGuideCreate) *ActionGuideCreateBulk {
	return &ActionGuideCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ActionGuideClient) MapCreateBulk(slice any, setFunc func(*ActionGuideCreate, int)) *ActionGuideCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ActionGuideCreateBulk{err: fmt.Errorf("calling to ActionGuideClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ActionGuideCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ActionGuideCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ActionGuide.
func (c *ActionGuideClient) Update() *ActionGuideUpdate {
	mutation := newActionGuideMutation(c.config, OpUpdate)
	return &ActionGuideUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ActionGuideClient) UpdateOne(_m *ActionGuide) *ActionGuideUpdateOne {
	mutation := newActionGuideMutation(c.config, OpUpdateOne, withActionGuide(_m))
	return &ActionGuideUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ActionGuideClient) UpdateOneID(id int) *ActionGuideUpdateOne {
	mutation := newActionGuideMutation(c.config, OpUpdateOne, withActionGuideID(id))
	return &ActionGuideUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ActionGuide.
func (c *ActionGuideClient) Delete() *ActionGuideDelete {
	mutation := newActionGuideMutation(c.config, OpDelete)
	return &ActionGuideDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ActionGuideClient) DeleteOne(_m *ActionGuide) *ActionGuideDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ActionGuideClient) DeleteOneID(id int) *ActionGuideDeleteOne {
	builder := c.Delete().Where(actionguide.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ActionGuideDeleteOne{builder}
}

// Query returns a query builder for ActionGuide.
func (c *ActionGuideClient) Query() *ActionGuideQuery {
	return &ActionGuideQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeActionGuide},
		inters: c.Interceptors(),
	}
}

// Get returns a ActionGuide entity by its id.
func (c *ActionGuideClient) Get(ctx context.Context, id int) (*ActionGuide, error) {
	return c.Query().Where(actionguide.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ActionGuideClient) GetX(ctx context.Context, id int) *ActionGuide {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryDeepAnalysisResult queries the deep_analysis_result edge of a ActionGuide.
func (c *ActionGuideClient) QueryDeepAnalysisResult(_m *ActionGuide) *DeepAnalysisResultQuery {
	query := (&DeepAnalysisResultClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(actionguide.Table, actionguide.FieldID, id),
			sqlgraph.To(deepanalysisresult.Table, deepanalysisresult.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, actionguide.DeepAnalysisResultTable, actionguide.DeepAnalysisResultColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ActionGuideClient) Hooks() []Hook {
	return c.hooks.ActionGuide
}

// Interceptors returns the client interceptors.
func (c *ActionGuideClient) Interceptors() []Interceptor {
	return c.inters.ActionGuide
}

func (c *ActionGuideClient) mutate(ctx context.Context, m *ActionGuideMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ActionGuideCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ActionGuideUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ActionGuideUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ActionGuideDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ActionGuide mutation op: %q", m.Op())
	}
}

// ArticleClient is a client for the Article schema.
type ArticleClient struct {
	config
}

// NewArticleClient returns a client for the Article from the given config.
func NewArticleClient(c config) *ArticleClient {
	return &ArticleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `article.Hooks(f(g(h())))`.
func (c *ArticleClient) Use(hooks ...Hook) {
	c.hooks.Article = append(c.hooks.Article, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `article.Intercept(f(g(h())))`.
func (c *ArticleClient) Intercept(interceptors ...Interceptor) {
	c.inters.Article = append(c.inters.Article, interceptors...)
}

// Create returns a builder for creating a Article entity.
func (c *ArticleClient) Create() *ArticleCreate {
	mutation := newArticleMutation(c.config, OpCreate)
	return &ArticleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Article entities.
func (c *ArticleClient) CreateBulk(builders ...*ArticleCreate) *ArticleCreateBulk {
	return &ArticleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ArticleClient) MapCreateBulk(slice any, setFunc func(*ArticleCreate, int)) *ArticleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ArticleCreateBulk{err: fmt.Errorf("calling to ArticleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ArticleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ArticleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Article.
func (c *ArticleClient) Update() *ArticleUpdate {
	mutation := newArticleMutation(c.config, OpUpdate)
	return &ArticleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ArticleClient) UpdateOne(_m *Article) *ArticleUpdateOne {
	mutation := newArticleMutation(c.config, OpUpdateOne, withArticle(_m))
	return &ArticleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ArticleClient) UpdateOneID(id int) *ArticleUpdateOne {
	mutation := newArticleMutation(c.config, OpUpdateOne, withArticleID(id))
	return &ArticleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Article.
func (c *ArticleClient) Delete() *ArticleDelete {
	mutation := newArticleMutation(c.config, OpDelete)
	return &ArticleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ArticleClient) DeleteOne(_m *Article) *ArticleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ArticleClient) DeleteOneID(id int) *ArticleDeleteOne {
	builder := c.Delete().Where(article.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ArticleDeleteOne{builder}
}

// Query returns a query builder for Article.
func (c *ArticleClient) Query() *ArticleQuery {
	return &ArticleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeArticle},
		inters: c.Interceptors(),
	}
}

// Get returns a Article entity by its id.
func (c *ArticleClient) Get(ctx context.Context, id int) (*Article, error) {
	return c.Query().Where(article.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ArticleClient) GetX(ctx context.Context, id int) *Article {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryDomainReport queries the domain_report edge of a Article.
func (c *ArticleClient) QueryDomainReport(_m *Article) *DomainReportQuery {
	query := (&DomainReportClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(article.Table, article.FieldID, id),
			sqlgraph.To(domainreport.Table, domainreport.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, article.DomainReportTable, article.DomainReportColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ArticleClient) Hooks() []Hook {
	return c.hooks.Article
}

// Interceptors returns the client interceptors.
func (c *ArticleClient) Interceptors() []Interceptor {
	return c.inters.Article
}

func (c *ArticleClient) mutate(ctx context.Context, m *ArticleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ArticleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ArticleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ArticleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ArticleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Article mutation op: %q", m.Op())
	}
}

// DeepAnalysisResultClient is a client for the DeepAnalysisResult schema.
type DeepAnalysisResultClient struct {
	config
}

// NewDeepAnalysisResultClient returns a client for the DeepAnalysisResult from the given config.
func NewDeepAnalysisResultClient(c config) *DeepAnalysisResultClient {
	return &DeepAnalysisResultClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `deepanalysisresult.Hooks(f(g(h())))`.
func (c *DeepAnalysisResultClient) Use(hooks ...Hook) {
	c.hooks.DeepAnalysisResult = append(c.hooks.DeepAnalysisResult, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `deepanalysisresult.Intercept(f(g(h())))`.
func (c *DeepAnalysisResultClient) Intercept(interceptors ...Interceptor) {
	c.inters.DeepAnalysisResult = append(c.inters.DeepAnalysisResult, interceptors...)
}

// Create returns a builder for creating a DeepAnalysisResult entity.
func (c *DeepAnalysisResultClient) Create() *DeepAnalysisResultCreate {
	mutation := newDeepAnalysisResultMutation(c.config, OpCreate)
	return &DeepAnalysisResultCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DeepAnalysisResult entities.
func (c *DeepAnalysisResultClient) CreateBulk(builders ...*DeepAnalysisResultCreate) *DeepAnalysisResultCreateBulk {
	return &DeepAnalysisResultCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DeepAnalysisResultClient) MapCreateBulk(slice any, setFunc func(*DeepAnalysisResultCreate, int)) *DeepAnalysisResultCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DeepAnalysisResultCreateBulk{err: fmt.Errorf("calling to DeepAnalysisResultClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DeepAnalysisResultCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DeepAnalysisResultCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DeepAnalysisResult.
func (c *DeepAnalysisResultClient) Update() *DeepAnalysisResultUpdate {
	mutation := newDeepAnalysisResultMutation(c.config, OpUpdate)
	return &DeepAnalysisResultUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DeepAnalysisResultClient) UpdateOne(_m *DeepAnalysisResult) *DeepAnalysisResultUpdateOne {
	mutation := newDeepAnalysisResultMutation(c.config, OpUpdateOne, withDeepAnalysisResult(_m))
	return &DeepAnalysisResultUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DeepAnalysisResultClient) UpdateOneID(id int) *DeepAnalysisResultUpdateOne {
	mutation := newDeepAnalysisResultMutation(c.config, OpUpdateOne, withDeepAnalysisResultID(id))
	return &DeepAnalysisResultUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DeepAnalysisResult.
func (c *DeepAnalysisResultClient) Delete() *DeepAnalysisResultDelete {
	mutation := newDeepAnalysisResultMutation(c.config, OpDelete)
	return &DeepAnalysisResultDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DeepAnalysisResultClient) DeleteOne(_m *DeepAnalysisResult) *DeepAnalysisResultDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DeepAnalysisResultClient) DeleteOneID(id int) *DeepAnalysisResultDeleteOne {
	builder := c.Delete().Where(deepanalysisresult.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DeepAnalysisResultDeleteOne{builder}
}

// Query returns a query builder for DeepAnalysisResult.
func (c *DeepAnalysisResultClient) Query() *DeepAnalysisResultQuery {
	return &DeepAnalysisResultQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDeepAnalysisResult},
		inters: c.Interceptors(),
	}
}

// Get returns a DeepAnalysisResult entity by its id.
func (c *DeepAnalysisResultClient) Get(ctx context.Context, id int) (*DeepAnalysisResult, error) {
	return c.Query().Where(deepanalysisresult.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DeepAnalysisResultClient) GetX(ctx context.Context, id int) *DeepAnalysisResult {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryReportRun queries the report_run edge of a DeepAnalysisResult.
func (c *DeepAnalysisResultClient) QueryReportRun(_m *DeepAnalysisResult) *ReportRunQuery {
	query := (&ReportRunClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(deepanalysisresult.Table, deepanalysisresult.FieldID, id),
			sqlgraph.To(reportrun.Table, reportrun.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, deepanalysisresult.ReportRunTable, deepanalysisresult.ReportRunColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryActionGuides queries the action_guides edge of a DeepAnalysisResult.
func (c *DeepAnalysisResultClient) QueryActionGuides(_m *DeepAnalysisResult) *ActionGuideQuery {
	query := (&ActionGuideClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(deepanalysisresult.Table, deepanalysisresult.FieldID, id),
			sqlgraph.To(actionguide.Table, actionguide.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, deepanalysisresult.ActionGuidesTable, deepanalysisresult.ActionGuidesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DeepAnalysisResultClient) Hooks() []Hook {
	return c.hooks.DeepAnalysisResult
}

// Interceptors returns the client interceptors.
func (c *DeepAnalysisResultClient) Interceptors() []Interceptor {
	return c.inters.DeepAnalysisResult
}

func (c *DeepAnalysisResultClient) mutate(ctx context.Context, m *DeepAnalysisResultMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DeepAnalysisResultCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DeepAnalysisResultUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DeepAnalysisResultUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DeepAnalysisResultDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DeepAnalysisResult mutation op: %q", m.Op())
	}
}

// DomainReportClient is a client for the DomainReport schema.
type DomainReportClient struct {
	config
}

// NewDomainReportClient returns a client for the DomainReport from the given config.
func NewDomainReportClient(c config) *DomainReportClient {
	return &DomainReportClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `domainreport.Hooks(f(g(h())))`.
func (c *DomainReportClient) Use(hooks ...Hook) {
	c.hooks.DomainReport = append(c.hooks.DomainReport, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `domainreport.Intercept(f(g(h())))`.
func (c *DomainReportClient) Intercept(interceptors ...Interceptor) {
	c.inters.DomainReport = append(c.inters.DomainReport, interceptors...)
}

// Create returns a builder for creating a DomainReport entity.
func (c *DomainReportClient) Create() *DomainReportCreate {
	mutation := newDomainReportMutation(c.config, OpCreate)
	return &DomainReportCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DomainReport entities.
func (c *DomainReportClient) CreateBulk(builders ...*DomainReportCreate) *DomainReportCreateBulk {
	return &DomainReportCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DomainReportClient) MapCreateBulk(slice any, setFunc func(*DomainReportCreate, int)) *DomainReportCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DomainReportCreateBulk{err: fmt.Errorf("calling to DomainReportClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DomainReportCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DomainReportCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DomainReport.
func (c *DomainReportClient) Update() *DomainReportUpdate {
	mutation := newDomainReportMutation(c.config, OpUpdate)
	return &DomainReportUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DomainReportClient) UpdateOne(_m *DomainReport) *DomainReportUpdateOne {
	mutation := newDomainReportMutation(c.config, OpUpdateOne, withDomainReport(_m))
	return &DomainReportUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DomainReportClient) UpdateOneID(id int) *DomainReportUpdateOne {
	mutation := newDomainReportMutation(c.config, OpUpdateOne, withDomainReportID(id))
	return &DomainReportUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DomainReport.
func (c *DomainReportClient) Delete() *DomainReportDelete {
	mutation := newDomainReportMutation(c.config, OpDelete)
	return &DomainReportDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DomainReportClient) DeleteOne(_m *DomainReport) *DomainReportDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DomainReportClient) DeleteOneID(id int) *DomainReportDeleteOne {
	builder := c.Delete().Where(domainreport.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DomainReportDeleteOne{builder}
}

// Query returns a query builder for DomainReport.
func (c *DomainReportClient) Query() *DomainReportQuery {
	return &DomainReportQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDomainReport},
		inters: c.Interceptors(),
	}
}

// Get returns a DomainReport entity by its id.
func (c *DomainReportClient) Get(ctx context.Context, id int) (*DomainReport, error) {
	return c.Query().Where(domainreport.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DomainReportClient) GetX(ctx context.Context, id int) *DomainReport {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryReportRun queries the report_run edge of a DomainReport.
func (c *DomainReportClient) QueryReportRun(_m *DomainReport) *ReportRunQuery {
	query := (&ReportRunClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(domainreport.Table, domainreport.FieldID, id),
			sqlgraph.To(reportrun.Table, reportrun.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, domainreport.ReportRunTable, domainreport.ReportRunColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryArticles queries the articles edge of a DomainReport.
func (c *DomainReportClient) QueryArticles(_m *DomainReport) *ArticleQuery {
	query := (&ArticleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(domainreport.Table, domainreport.FieldID, id),
			sqlgraph.To(article.Table, article.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, domainreport.ArticlesTable, domainreport.ArticlesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryKeyEvents queries the key_events edge of a DomainReport.
func (c *DomainReportClient) QueryKeyEvents(_m *DomainReport) *KeyEventQuery {
	query := (&KeyEventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(domainreport.Table, domainreport.FieldID, id),
			sqlgraph.To(keyevent.Table, keyevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, domainreport.KeyEventsTable, domainreport.KeyEventsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DomainReportClient) Hooks() []Hook {
	return c.hooks.DomainReport
}

// Interceptors returns the client interceptors.
func (c *DomainReportClient) Interceptors() []Interceptor {
	return c.inters.DomainReport
}

func (c *DomainReportClient) mutate(ctx context.Context, m *DomainReportMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DomainReportCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DomainReportUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DomainReportUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DomainReportDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DomainReport mutation op: %q", m.Op())
	}
}

// KeyEventClient is a client for the KeyEvent schema.
type KeyEventClient struct {
	config
}

// NewKeyEventClient returns a client for the KeyEvent from the given config.
func NewKeyEventClient(c config) *KeyEventClient {
	return &KeyEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `keyevent.Hooks(f(g(h())))`.
func (c *KeyEventClient) Use(hooks ...Hook) {
	c.hooks.KeyEvent = append(c.hooks.KeyEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `keyevent.Intercept(f(g(h())))`.
func (c *KeyEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.KeyEvent = append(c.inters.KeyEvent, interceptors...)
}

// Create returns a builder for creating a KeyEvent entity.
func (c *KeyEventClient) Create() *KeyEventCreate {
	mutation := newKeyEventMutation(c.config, OpCreate)
	return &KeyEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of KeyEvent entities.
func (c *KeyEventClient) CreateBulk(builders ...*KeyEventCreate) *KeyEventCreateBulk {
	return &KeyEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *KeyEventClient) MapCreateBulk(slice any, setFunc func(*KeyEventCreate, int)) *KeyEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &KeyEventCreateBulk{err: fmt.Errorf("calling to KeyEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*KeyEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &KeyEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for KeyEvent.
func (c *KeyEventClient) Update() *KeyEventUpdate {
	mutation := newKeyEventMutation(c.config, OpUpdate)
	return &KeyEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *KeyEventClient) UpdateOne(_m *KeyEvent) *KeyEventUpdateOne {
	mutation := newKeyEventMutation(c.config, OpUpdateOne, withKeyEvent(_m))
	return &KeyEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *KeyEventClient) UpdateOneID(id int) *KeyEventUpdateOne {
	mutation := newKeyEventMutation(c.config, OpUpdateOne, withKeyEventID(id))
	return &KeyEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for KeyEvent.
func (c *KeyEventClient) Delete() *KeyEventDelete {
	mutation := newKeyEventMutation(c.config, OpDelete)
	return &KeyEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *KeyEventClient) DeleteOne(_m *KeyEvent) *KeyEventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *KeyEventClient) DeleteOneID(id int) *KeyEventDeleteOne {
	builder := c.Delete().Where(keyevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &KeyEventDeleteOne{builder}
}

// Query returns a query builder for KeyEvent.
func (c *KeyEventClient) Query() *KeyEventQuery {
	return &KeyEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeKeyEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a KeyEvent entity by its id.
func (c *KeyEventClient) Get(ctx context.Context, id int) (*KeyEvent, error) {
	return c.Query().Where(keyevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *KeyEventClient) GetX(ctx context.Context, id int) *KeyEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryDomainReport queries the domain_report edge of a KeyEvent.
func (c *KeyEventClient) QueryDomainReport(_m *KeyEvent) *DomainReportQuery {
	query := (&DomainReportClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(keyevent.Table, keyevent.FieldID, id),
			sqlgraph.To(domainreport.Table, domainreport.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, keyevent.DomainReportTable, keyevent.DomainReportColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *KeyEventClient) Hooks() []Hook {
	return c.hooks.KeyEvent
}

// Interceptors returns the client interceptors.
func (c *KeyEventClient) Interceptors() []Interceptor {
	return c.inters.KeyEvent
}

func (c *KeyEventClient) mutate(ctx context.Context, m *KeyEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&KeyEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&KeyEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&KeyEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&KeyEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown KeyEvent mutation op: %q", m.Op())
	}
}

// ReportRunClient is a client for the ReportRun schema.
type ReportRunClient struct {
	config
}

// NewReportRunClient returns a client for the ReportRun from the given config.
func NewReportRunClient(c config) *ReportRunClient {
	return &ReportRunClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `reportrun.Hooks(f(g(h())))`.
func (c *ReportRunClient) Use(hooks ...Hook) {
	c.hooks.ReportRun = append(c.hooks.ReportRun, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `reportrun.Intercept(f(g(h())))`.
func (c *ReportRunClient) Intercept(interceptors ...Interceptor) {
	c.inters.ReportRun = append(c.inters.ReportRun, interceptors...)
}

// Create returns a builder for creating a ReportRun entity.
func (c *ReportRunClient) Create() *ReportRunCreate {
	mutation := newReportRunMutation(c.config, OpCreate)
	return &ReportRunCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ReportRun entities.
func (c *ReportRunClient) CreateBulk(builders ...*ReportRunCreate) *ReportRunCreateBulk {
	return &ReportRunCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ReportRunClient) MapCreateBulk(slice any, setFunc func(*ReportRunCreate, int)) *ReportRunCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ReportRunCreateBulk{err: fmt.Errorf("calling to ReportRunClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ReportRunCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ReportRunCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ReportRun.
func (c *ReportRunClient) Update() *ReportRunUpdate {
	mutation := newReportRunMutation(c.config, OpUpdate)
	return &ReportRunUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ReportRunClient) UpdateOne(_m *ReportRun) *ReportRunUpdateOne {
	mutation := newReportRunMutation(c.config, OpUpdateOne, withReportRun(_m))
	return &ReportRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ReportRunClient) UpdateOneID(id int) *ReportRunUpdateOne {
	mutation := newReportRunMutation(c.config, OpUpdateOne, withReportRunID(id))
	return &ReportRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ReportRun.
func (c *ReportRunClient) Delete() *ReportRunDelete {
	mutation := newReportRunMutation(c.config, OpDelete)
	return &ReportRunDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ReportRunClient) DeleteOne(_m *ReportRun) *ReportRunDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ReportRunClient) DeleteOneID(id int) *ReportRunDeleteOne {
	builder := c.Delete().Where(reportrun.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ReportRunDeleteOne{builder}
}

// Query returns a query builder for ReportRun.
func (c *ReportRunClient) Query() *ReportRunQuery {
	return &ReportRunQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeReportRun},
		inters: c.Interceptors(),
	}
}

// Get returns a ReportRun entity by its id.
func (c *ReportRunClient) Get(ctx context.Context, id int) (*ReportRun, error) {
	return c.Query().Where(reportrun.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ReportRunClient) GetX(ctx context.Context, id int) *ReportRun {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryDomainReports queries the domain_reports edge of a ReportRun.
func (c *ReportRunClient) QueryDomainReports(_m *ReportRun) *DomainReportQuery {
	query := (&DomainReportClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(reportrun.Table, reportrun.FieldID, id),
			sqlgraph.To(domainreport.Table, domainreport.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, reportrun.DomainReportsTable, reportrun.DomainReportsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDeepAnalysisResults queries the deep_analysis_results edge of a ReportRun.
func (c *ReportRunClient) QueryDeepAnalysisResults(_m *ReportRun) *DeepAnalysisResultQuery {
	query := (&DeepAnalysisResultClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(reportrun.Table, reportrun.FieldID, id),
			sqlgraph.To(deepanalysisresult.Table, deepanalysisresult.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, reportrun.DeepAnalysisResultsTable, reportrun.DeepAnalysisResultsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ReportRunClient) Hooks() []Hook {
	return c.hooks.ReportRun
}

// Interceptors returns the client interceptors.
func (c *ReportRunClient) Interceptors() []Interceptor {
	return c.inters.ReportRun
}

func (c *ReportRunClient) mutate(ctx context.Context, m *ReportRunMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ReportRunCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ReportRunUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ReportRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ReportRunDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ReportRun mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		ActionGuide, Article, DeepAnalysisResult, DomainReport, KeyEvent, ReportRun,
		User []ent.Hook
	}
	inters struct {
		ActionGuide, Article, DeepAnalysisResult, DomainReport, KeyEvent, ReportRun,
		User []ent.Interceptor
	}
)
