// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iWorld-y/domain_radar/app/common/ent/actionguide"
	"github.com/iWorld-y/domain_radar/app/common/ent/deepanalysisresult"
	"github.com/iWorld-y/domain_radar/app/common/ent/reportrun"
)

// DeepAnalysisResultCreate is the builder for creating a DeepAnalysisResult entity.
type DeepAnalysisResultCreate struct {
	config
	mutation *DeepAnalysisResultMutation
	hooks    []Hook
}

// SetRunID sets the "run_id" field.
func (_c *DeepAnalysisResultCreate) SetRunID(v int) *DeepAnalysisResultCreate {
	_c.mutation.SetRunID(v)
	return _c
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_c *DeepAnalysisResultCreate) SetNillableRunID(v *int) *DeepAnalysisResultCreate {
	if v != nil {
		_c.SetRunID(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *DeepAnalysisResultCreate) SetUserID(v int) *DeepAnalysisResultCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *DeepAnalysisResultCreate) SetNillableUserID(v *int) *DeepAnalysisResultCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetMacroTrends sets the "macro_trends" field.
func (_c *DeepAnalysisResultCreate) SetMacroTrends(v string) *DeepAnalysisResultCreate {
	_c.mutation.SetMacroTrends(v)
	return _c
}

// SetNillableMacroTrends sets the "macro_trends" field if the given value is not nil.
func (_c *DeepAnalysisResultCreate) SetNillableMacroTrends(v *string) *DeepAnalysisResultCreate {
	if v != nil {
		_c.SetMacroTrends(*v)
	}
	return _c
}

// SetOpportunities sets the "opportunities" field.
func (_c *DeepAnalysisResultCreate) SetOpportunities(v string) *DeepAnalysisResultCreate {
	_c.mutation.SetOpportunities(v)
	return _c
}

// SetNillableOpportunities sets the "opportunities" field if the given value is not nil.
func (_c *DeepAnalysisResultCreate) SetNillableOpportunities(v *string) *DeepAnalysisResultCreate {
	if v != nil {
		_c.SetOpportunities(*v)
	}
	return _c
}

// SetRisks sets the "risks" field.
func (_c *DeepAnalysisResultCreate) SetRisks(v string) *DeepAnalysisResultCreate {
	_c.mutation.SetRisks(v)
	return _c
}

// SetNillableRisks sets the "risks" field if the given value is not nil.
func (_c *DeepAnalysisResultCreate) SetNillableRisks(v *string) *DeepAnalysisResultCreate {
	if v != nil {
		_c.SetRisks(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeepAnalysisResultCreate) SetCreatedAt(v time.Time) *DeepAnalysisResultCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeepAnalysisResultCreate) SetNillableCreatedAt(v *time.Time) *DeepAnalysisResultCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DeepAnalysisResultCreate) SetID(v int) *DeepAnalysisResultCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetReportRunID sets the "report_run" edge to the ReportRun entity by ID.
func (_c *DeepAnalysisResultCreate) SetReportRunID(id int) *DeepAnalysisResultCreate {
	_c.mutation.SetReportRunID(id)
	return _c
}

// SetNillableReportRunID sets the "report_run" edge to the ReportRun entity by ID if the given value is not nil.
func (_c *DeepAnalysisResultCreate) SetNillableReportRunID(id *int) *DeepAnalysisResultCreate {
	if id != nil {
		_c = _c.SetReportRunID(*id)
	}
	return _c
}

// SetReportRun sets the "report_run" edge to the ReportRun entity.
func (_c *DeepAnalysisResultCreate) SetReportRun(v *ReportRun) *DeepAnalysisResultCreate {
	return _c.SetReportRunID(v.ID)
}

// AddActionGuideIDs adds the "action_guides" edge to the ActionGuide entity by IDs.
func (_c *DeepAnalysisResultCreate) AddActionGuideIDs(ids ...int) *DeepAnalysisResultCreate {
	_c.mutation.AddActionGuideIDs(ids...)
	return _c
}

// AddActionGuides adds the "action_guides" edges to the ActionGuide entity.
func (_c *DeepAnalysisResultCreate) AddActionGuides(v ...*ActionGuide) *DeepAnalysisResultCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddActionGuideIDs(ids...)
}

// Mutation returns the DeepAnalysisResultMutation object of the builder.
func (_c *DeepAnalysisResultCreate) Mutation() *DeepAnalysisResultMutation {
	return _c.mutation
}

// Save creates the DeepAnalysisResult in the database.
func (_c *DeepAnalysisResultCreate) Save(ctx context.Context) (*DeepAnalysisResult, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeepAnalysisResultCreate) SaveX(ctx context.Context) *DeepAnalysisResult {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeepAnalysisResultCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeepAnalysisResultCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeepAnalysisResultCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := deepanalysisresult.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeepAnalysisResultCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DeepAnalysisResult.created_at"`)}
	}
	return nil
}

func (_c *DeepAnalysisResultCreate) sqlSave(ctx context.Context) (*DeepAnalysisResult, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeepAnalysisResultCreate) createSpec() (*DeepAnalysisResult, *sqlgraph.CreateSpec) {
	var (
		_node = &DeepAnalysisResult{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(deepanalysisresult.Table, sqlgraph.NewFieldSpec(deepanalysisresult.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(deepanalysisresult.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.MacroTrends(); ok {
		_spec.SetField(deepanalysisresult.FieldMacroTrends, field.TypeString, value)
		_node.MacroTrends = value
	}
	if value, ok := _c.mutation.Opportunities(); ok {
		_spec.SetField(deepanalysisresult.FieldOpportunities, field.TypeString, value)
		_node.Opportunities = value
	}
	if value, ok := _c.mutation.Risks(); ok {
		_spec.SetField(deepanalysisresult.FieldRisks, field.TypeString, value)
		_node.Risks = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(deepanalysisresult.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ReportRunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deepanalysisresult.ReportRunTable,
			Columns: []string{deepanalysisresult.ReportRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportrun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RunID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ActionGuidesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deepanalysisresult.ActionGuidesTable,
			Columns: []string{deepanalysisresult.ActionGuidesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionguide.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DeepAnalysisResultCreateBulk is the builder for creating many DeepAnalysisResult entities in bulk.
type DeepAnalysisResultCreateBulk struct {
	config
	err      error
	builders []*DeepAnalysisResultCreate
}

// Save creates the DeepAnalysisResult entities in the database.
func (_c *DeepAnalysisResultCreateBulk) Save(ctx context.Context) ([]*DeepAnalysisResult, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DeepAnalysisResult, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeepAnalysisResultMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeepAnalysisResultCreateBulk) SaveX(ctx context.Context) []*DeepAnalysisResult {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeepAnalysisResultCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeepAnalysisResultCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
