// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/iWorld-y/domain_radar/app/common/ent/deepanalysisresult"
	"github.com/iWorld-y/domain_radar/app/common/ent/reportrun"
)

// DeepAnalysisResult is the model entity for the DeepAnalysisResult schema.
type DeepAnalysisResult struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RunID holds the value of the "run_id" field.
	RunID int `json:"run_id,omitempty"`
	// MacroTrends holds the value of the "macro_trends" field.
	MacroTrends string `json:"macro_trends,omitempty"`
	// Opportunities holds the value of the "opportunities" field.
	Opportunities string `json:"opportunities,omitempty"`
	// Risks holds the value of the "risks" field.
	Risks string `json:"risks,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DeepAnalysisResultQuery when eager-loading is set.
	Edges        DeepAnalysisResultEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DeepAnalysisResultEdges holds the relations/edges for other nodes in the graph.
type DeepAnalysisResultEdges struct {
	// ReportRun holds the value of the report_run edge.
	ReportRun *ReportRun `json:"report_run,omitempty"`
	// ActionGuides holds the value of the action_guides edge.
	ActionGuides []*ActionGuide `json:"action_guides,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ReportRunOrErr returns the ReportRun value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeepAnalysisResultEdges) ReportRunOrErr() (*ReportRun, error) {
	if e.ReportRun != nil {
		return e.ReportRun, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: reportrun.Label}
	}
	return nil, &NotLoadedError{edge: "report_run"}
}

// ActionGuidesOrErr returns the ActionGuides value or an error if the edge
// was not loaded in eager-loading.
func (e DeepAnalysisResultEdges) ActionGuidesOrErr() ([]*ActionGuide, error) {
	if e.loadedTypes[1] {
		return e.ActionGuides, nil
	}
	return nil, &NotLoadedError{edge: "action_guides"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DeepAnalysisResult) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case deepanalysisresult.FieldID, deepanalysisresult.FieldRunID:
			values[i] = new(sql.NullInt64)
		case deepanalysisresult.FieldMacroTrends, deepanalysisresult.FieldOpportunities, deepanalysisresult.FieldRisks:
			values[i] = new(sql.NullString)
		case deepanalysisresult.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DeepAnalysisResult fields.
func (_m *DeepAnalysisResult) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case deepanalysisresult.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case deepanalysisresult.FieldRunID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field run_id", values[i])
			} else if value.Valid {
				_m.RunID = int(value.Int64)
			}
		case deepanalysisresult.FieldMacroTrends:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field macro_trends", values[i])
			} else if value.Valid {
				_m.MacroTrends = value.String
			}
		case deepanalysisresult.FieldOpportunities:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field opportunities", values[i])
			} else if value.Valid {
				_m.Opportunities = value.String
			}
		case deepanalysisresult.FieldRisks:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field risks", values[i])
			} else if value.Valid {
				_m.Risks = value.String
			}
		case deepanalysisresult.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DeepAnalysisResult.
// This includes values selected through modifiers, order, etc.
func (_m *DeepAnalysisResult) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryReportRun queries the "report_run" edge of the DeepAnalysisResult entity.
func (_m *DeepAnalysisResult) QueryReportRun() *ReportRunQuery {
	return NewDeepAnalysisResultClient(_m.config).QueryReportRun(_m)
}

// QueryActionGuides queries the "action_guides" edge of the DeepAnalysisResult entity.
func (_m *DeepAnalysisResult) QueryActionGuides() *ActionGuideQuery {
	return NewDeepAnalysisResultClient(_m.config).QueryActionGuides(_m)
}

// Update returns a builder for updating this DeepAnalysisResult.
// Note that you need to call DeepAnalysisResult.Unwrap() before calling this method if this DeepAnalysisResult
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DeepAnalysisResult) Update() *DeepAnalysisResultUpdateOne {
	return NewDeepAnalysisResultClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DeepAnalysisResult entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DeepAnalysisResult) Unwrap() *DeepAnalysisResult {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DeepAnalysisResult is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DeepAnalysisResult) String() string {
	var builder strings.Builder
	builder.WriteString("DeepAnalysisResult(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("run_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RunID))
	builder.WriteString(", ")
	builder.WriteString("macro_trends=")
	builder.WriteString(_m.MacroTrends)
	builder.WriteString(", ")
	builder.WriteString("opportunities=")
	builder.WriteString(_m.Opportunities)
	builder.WriteString(", ")
	builder.WriteString("risks=")
	builder.WriteString(_m.Risks)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DeepAnalysisResults is a parsable slice of DeepAnalysisResult.
type DeepAnalysisResults []*DeepAnalysisResult
