// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iWorld-y/domain_radar/app/common/ent/article"
	"github.com/iWorld-y/domain_radar/app/common/ent/domainreport"
	"github.com/iWorld-y/domain_radar/app/common/ent/keyevent"
	"github.com/iWorld-y/domain_radar/app/common/ent/reportrun"
)

// DomainReportCreate is the builder for creating a DomainReport entity.
type DomainReportCreate struct {
	config
	mutation *DomainReportMutation
	hooks    []Hook
}

// SetRunID sets the "run_id" field.
func (_c *DomainReportCreate) SetRunID(v int) *DomainReportCreate {
	_c.mutation.SetRunID(v)
	return _c
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_c *DomainReportCreate) SetNillableRunID(v *int) *DomainReportCreate {
	if v != nil {
		_c.SetRunID(*v)
	}
	return _c
}

// SetDomainName sets the "domain_name" field.
func (_c *DomainReportCreate) SetDomainName(v string) *DomainReportCreate {
	_c.mutation.SetDomainName(v)
	return _c
}

// SetOverview sets the "overview" field.
func (_c *DomainReportCreate) SetOverview(v string) *DomainReportCreate {
	_c.mutation.SetOverview(v)
	return _c
}

// SetNillableOverview sets the "overview" field if the given value is not nil.
func (_c *DomainReportCreate) SetNillableOverview(v *string) *DomainReportCreate {
	if v != nil {
		_c.SetOverview(*v)
	}
	return _c
}

// SetTrends sets the "trends" field.
func (_c *DomainReportCreate) SetTrends(v string) *DomainReportCreate {
	_c.mutation.SetTrends(v)
	return _c
}

// SetNillableTrends sets the "trends" field if the given value is not nil.
func (_c *DomainReportCreate) SetNillableTrends(v *string) *DomainReportCreate {
	if v != nil {
		_c.SetTrends(*v)
	}
	return _c
}

// SetScore sets the "score" field.
func (_c *DomainReportCreate) SetScore(v int) *DomainReportCreate {
	_c.mutation.SetScore(v)
	return _c
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_c *DomainReportCreate) SetNillableScore(v *int) *DomainReportCreate {
	if v != nil {
		_c.SetScore(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DomainReportCreate) SetCreatedAt(v time.Time) *DomainReportCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DomainReportCreate) SetNillableCreatedAt(v *time.Time) *DomainReportCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DomainReportCreate) SetID(v int) *DomainReportCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetReportRunID sets the "report_run" edge to the ReportRun entity by ID.
func (_c *DomainReportCreate) SetReportRunID(id int) *DomainReportCreate {
	_c.mutation.SetReportRunID(id)
	return _c
}

// SetNillableReportRunID sets the "report_run" edge to the ReportRun entity by ID if the given value is not nil.
func (_c *DomainReportCreate) SetNillableReportRunID(id *int) *DomainReportCreate {
	if id != nil {
		_c = _c.SetReportRunID(*id)
	}
	return _c
}

// SetReportRun sets the "report_run" edge to the ReportRun entity.
func (_c *DomainReportCreate) SetReportRun(v *ReportRun) *DomainReportCreate {
	return _c.SetReportRunID(v.ID)
}

// AddArticleIDs adds the "articles" edge to the Article entity by IDs.
func (_c *DomainReportCreate) AddArticleIDs(ids ...int) *DomainReportCreate {
	_c.mutation.AddArticleIDs(ids...)
	return _c
}

// AddArticles adds the "articles" edges to the Article entity.
func (_c *DomainReportCreate) AddArticles(v ...*Article) *DomainReportCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddArticleIDs(ids...)
}

// AddKeyEventIDs adds the "key_events" edge to the KeyEvent entity by IDs.
func (_c *DomainReportCreate) AddKeyEventIDs(ids ...int) *DomainReportCreate {
	_c.mutation.AddKeyEventIDs(ids...)
	return _c
}

// AddKeyEvents adds the "key_events" edges to the KeyEvent entity.
func (_c *DomainReportCreate) AddKeyEvents(v ...*KeyEvent) *DomainReportCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddKeyEventIDs(ids...)
}

// Mutation returns the DomainReportMutation object of the builder.
func (_c *DomainReportCreate) Mutation() *DomainReportMutation {
	return _c.mutation
}

// Save creates the DomainReport in the database.
func (_c *DomainReportCreate) Save(ctx context.Context) (*DomainReport, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DomainReportCreate) SaveX(ctx context.Context) *DomainReport {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DomainReportCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DomainReportCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DomainReportCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := domainreport.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DomainReportCreate) check() error {
	if _, ok := _c.mutation.DomainName(); !ok {
		return &ValidationError{Name: "domain_name", err: errors.New(`ent: missing required field "DomainReport.domain_name"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DomainReport.created_at"`)}
	}
	return nil
}

func (_c *DomainReportCreate) sqlSave(ctx context.Context) (*DomainReport, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DomainReportCreate) createSpec() (*DomainReport, *sqlgraph.CreateSpec) {
	var (
		_node = &DomainReport{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(domainreport.Table, sqlgraph.NewFieldSpec(domainreport.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.DomainName(); ok {
		_spec.SetField(domainreport.FieldDomainName, field.TypeString, value)
		_node.DomainName = value
	}
	if value, ok := _c.mutation.Overview(); ok {
		_spec.SetField(domainreport.FieldOverview, field.TypeString, value)
		_node.Overview = value
	}
	if value, ok := _c.mutation.Trends(); ok {
		_spec.SetField(domainreport.FieldTrends, field.TypeString, value)
		_node.Trends = value
	}
	if value, ok := _c.mutation.Score(); ok {
		_spec.SetField(domainreport.FieldScore, field.TypeInt, value)
		_node.Score = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(domainreport.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ReportRunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   domainreport.ReportRunTable,
			Columns: []string{domainreport.ReportRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportrun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RunID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ArticlesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   domainreport.ArticlesTable,
			Columns: []string{domainreport.ArticlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.KeyEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   domainreport.KeyEventsTable,
			Columns: []string{domainreport.KeyEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(keyevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DomainReportCreateBulk is the builder for creating many DomainReport entities in bulk.
type DomainReportCreateBulk struct {
	config
	err      error
	builders []*DomainReportCreate
}

// Save creates the DomainReport entities in the database.
func (_c *DomainReportCreateBulk) Save(ctx context.Context) ([]*DomainReport, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DomainReport, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DomainReportMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DomainReportCreateBulk) SaveX(ctx context.Context) []*DomainReport {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DomainReportCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DomainReportCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
