// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iWorld-y/domain_radar/app/common/ent/article"
	"github.com/iWorld-y/domain_radar/app/common/ent/domainreport"
	"github.com/iWorld-y/domain_radar/app/common/ent/keyevent"
	"github.com/iWorld-y/domain_radar/app/common/ent/predicate"
	"github.com/iWorld-y/domain_radar/app/common/ent/reportrun"
)

// DomainReportQuery is the builder for querying DomainReport entities.
type DomainReportQuery struct {
	config
	ctx           *QueryContext
	order         []domainreport.OrderOption
	inters        []Interceptor
	predicates    []predicate.DomainReport
	withReportRun *ReportRunQuery
	withArticles  *ArticleQuery
	withKeyEvents *KeyEventQuery
	modifiers     []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DomainReportQuery builder.
func (_q *DomainReportQuery) Where(ps ...predicate.DomainReport) *DomainReportQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DomainReportQuery) Limit(limit int) *DomainReportQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DomainReportQuery) Offset(offset int) *DomainReportQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DomainReportQuery) Unique(unique bool) *DomainReportQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DomainReportQuery) Order(o ...domainreport.OrderOption) *DomainReportQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryReportRun chains the current query on the "report_run" edge.
func (_q *DomainReportQuery) QueryReportRun() *ReportRunQuery {
	query := (&ReportRunClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(domainreport.Table, domainreport.FieldID, selector),
			sqlgraph.To(reportrun.Table, reportrun.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, domainreport.ReportRunTable, domainreport.ReportRunColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryArticles chains the current query on the "articles" edge.
func (_q *DomainReportQuery) QueryArticles() *ArticleQuery {
	query := (&ArticleClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(domainreport.Table, domainreport.FieldID, selector),
			sqlgraph.To(article.Table, article.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, domainreport.ArticlesTable, domainreport.ArticlesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryKeyEvents chains the current query on the "key_events" edge.
func (_q *DomainReportQuery) QueryKeyEvents() *KeyEventQuery {
	query := (&KeyEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(domainreport.Table, domainreport.FieldID, selector),
			sqlgraph.To(keyevent.Table, keyevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, domainreport.KeyEventsTable, domainreport.KeyEventsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DomainReport entity from the query.
// Returns a *NotFoundError when no DomainReport was found.
func (_q *DomainReportQuery) First(ctx context.Context) (*DomainReport, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{domainreport.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DomainReportQuery) FirstX(ctx context.Context) *DomainReport {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DomainReport ID from the query.
// Returns a *NotFoundError when no DomainReport ID was found.
func (_q *DomainReportQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{domainreport.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DomainReportQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DomainReport entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DomainReport entity is found.
// Returns a *NotFoundError when no DomainReport entities are found.
func (_q *DomainReportQuery) Only(ctx context.Context) (*DomainReport, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{domainreport.Label}
	default:
		return nil, &NotSingularError{domainreport.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DomainReportQuery) OnlyX(ctx context.Context) *DomainReport {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DomainReport ID in the query.
// Returns a *NotSingularError when more than one DomainReport ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DomainReportQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{domainreport.Label}
	default:
		err = &NotSingularError{domainreport.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DomainReportQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DomainReports.
func (_q *DomainReportQuery) All(ctx context.Context) ([]*DomainReport, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DomainReport, *DomainReportQuery]()
	return withInterceptors[[]*DomainReport](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DomainReportQuery) AllX(ctx context.Context) []*DomainReport {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DomainReport IDs.
func (_q *DomainReportQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(domainreport.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DomainReportQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DomainReportQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DomainReportQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DomainReportQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DomainReportQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DomainReportQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DomainReportQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DomainReportQuery) Clone() *DomainReportQuery {
	if _q == nil {
		return nil
	}
	return &DomainReportQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]domainreport.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.DomainReport{}, _q.predicates...),
		withReportRun: _q.withReportRun.Clone(),
		withArticles:  _q.withArticles.Clone(),
		withKeyEvents: _q.withKeyEvents.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithReportRun tells the query-builder to eager-load the nodes that are connected to
// the "report_run" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DomainReportQuery) WithReportRun(opts ...func(*ReportRunQuery)) *DomainReportQuery {
	query := (&ReportRunClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withReportRun = query
	return _q
}

// WithArticles tells the query-builder to eager-load the nodes that are connected to
// the "articles" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DomainReportQuery) WithArticles(opts ...func(*ArticleQuery)) *DomainReportQuery {
	query := (&ArticleClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withArticles = query
	return _q
}

// WithKeyEvents tells the query-builder to eager-load the nodes that are connected to
// the "key_events" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DomainReportQuery) WithKeyEvents(opts ...func(*KeyEventQuery)) *DomainReportQuery {
	query := (&KeyEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withKeyEvents = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RunID int `json:"run_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DomainReport.Query().
//		GroupBy(domainreport.FieldRunID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DomainReportQuery) GroupBy(field string, fields ...string) *DomainReportGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DomainReportGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = domainreport.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RunID int `json:"run_id,omitempty"`
//	}
//
//	client.DomainReport.Query().
//		Select(domainreport.FieldRunID).
//		Scan(ctx, &v)
func (_q *DomainReportQuery) Select(fields ...string) *DomainReportSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DomainReportSelect{DomainReportQuery: _q}
	sbuild.label = domainreport.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DomainReportSelect configured with the given aggregations.
func (_q *DomainReportQuery) Aggregate(fns ...AggregateFunc) *DomainReportSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DomainReportQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !domainreport.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DomainReportQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DomainReport, error) {
	var (
		nodes       = []*DomainReport{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withReportRun != nil,
			_q.withArticles != nil,
			_q.withKeyEvents != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DomainReport).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DomainReport{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withReportRun; query != nil {
		if err := _q.loadReportRun(ctx, query, nodes, nil,
			func(n *DomainReport, e *ReportRun) { n.Edges.ReportRun = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withArticles; query != nil {
		if err := _q.loadArticles(ctx, query, nodes,
			func(n *DomainReport) { n.Edges.Articles = []*Article{} },
			func(n *DomainReport, e *Article) { n.Edges.Articles = append(n.Edges.Articles, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withKeyEvents; query != nil {
		if err := _q.loadKeyEvents(ctx, query, nodes,
			func(n *DomainReport) { n.Edges.KeyEvents = []*KeyEvent{} },
			func(n *DomainReport, e *KeyEvent) { n.Edges.KeyEvents = append(n.Edges.KeyEvents, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DomainReportQuery) loadReportRun(ctx context.Context, query *ReportRunQuery, nodes []*DomainReport, init func(*DomainReport), assign func(*DomainReport, *ReportRun)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*DomainReport)
	for i := range nodes {
		fk := nodes[i].RunID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(reportrun.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "run_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DomainReportQuery) loadArticles(ctx context.Context, query *ArticleQuery, nodes []*DomainReport, init func(*DomainReport), assign func(*DomainReport, *Article)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*DomainReport)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(article.FieldDomainReportID)
	}
	query.Where(predicate.Article(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(domainreport.ArticlesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DomainReportID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "domain_report_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *DomainReportQuery) loadKeyEvents(ctx context.Context, query *KeyEventQuery, nodes []*DomainReport, init func(*DomainReport), assign func(*DomainReport, *KeyEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*DomainReport)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(keyevent.FieldDomainReportID)
	}
	query.Where(predicate.KeyEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(domainreport.KeyEventsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DomainReportID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "domain_report_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *DomainReportQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DomainReportQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(domainreport.Table, domainreport.Columns, sqlgraph.NewFieldSpec(domainreport.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, domainreport.FieldID)
		for i := range fields {
			if fields[i] != domainreport.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withReportRun != nil {
			_spec.Node.AddColumnOnce(domainreport.FieldRunID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DomainReportQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(domainreport.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = domainreport.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *DomainReportQuery) Modify(modifiers ...func(s *sql.Selector)) *DomainReportSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// DomainReportGroupBy is the group-by builder for DomainReport entities.
type DomainReportGroupBy struct {
	selector
	build *DomainReportQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DomainReportGroupBy) Aggregate(fns ...AggregateFunc) *DomainReportGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DomainReportGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DomainReportQuery, *DomainReportGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DomainReportGroupBy) sqlScan(ctx context.Context, root *DomainReportQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DomainReportSelect is the builder for selecting fields of DomainReport entities.
type DomainReportSelect struct {
	*DomainReportQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DomainReportSelect) Aggregate(fns ...AggregateFunc) *DomainReportSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DomainReportSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DomainReportQuery, *DomainReportSelect](ctx, _s.DomainReportQuery, _s, _s.inters, v)
}

func (_s *DomainReportSelect) sqlScan(ctx context.Context, root *DomainReportQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *DomainReportSelect) Modify(modifiers ...func(s *sql.Selector)) *DomainReportSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
