// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iWorld-y/domain_radar/app/common/ent/article"
	"github.com/iWorld-y/domain_radar/app/common/ent/domainreport"
	"github.com/iWorld-y/domain_radar/app/common/ent/keyevent"
	"github.com/iWorld-y/domain_radar/app/common/ent/predicate"
	"github.com/iWorld-y/domain_radar/app/common/ent/reportrun"
)

// DomainReportUpdate is the builder for updating DomainReport entities.
type DomainReportUpdate struct {
	config
	hooks     []Hook
	mutation  *DomainReportMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DomainReportUpdate builder.
func (_u *DomainReportUpdate) Where(ps ...predicate.DomainReport) *DomainReportUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRunID sets the "run_id" field.
func (_u *DomainReportUpdate) SetRunID(v int) *DomainReportUpdate {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *DomainReportUpdate) SetNillableRunID(v *int) *DomainReportUpdate {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// ClearRunID clears the value of the "run_id" field.
func (_u *DomainReportUpdate) ClearRunID() *DomainReportUpdate {
	_u.mutation.ClearRunID()
	return _u
}

// SetDomainName sets the "domain_name" field.
func (_u *DomainReportUpdate) SetDomainName(v string) *DomainReportUpdate {
	_u.mutation.SetDomainName(v)
	return _u
}

// SetNillableDomainName sets the "domain_name" field if the given value is not nil.
func (_u *DomainReportUpdate) SetNillableDomainName(v *string) *DomainReportUpdate {
	if v != nil {
		_u.SetDomainName(*v)
	}
	return _u
}

// SetOverview sets the "overview" field.
func (_u *DomainReportUpdate) SetOverview(v string) *DomainReportUpdate {
	_u.mutation.SetOverview(v)
	return _u
}

// SetNillableOverview sets the "overview" field if the given value is not nil.
func (_u *DomainReportUpdate) SetNillableOverview(v *string) *DomainReportUpdate {
	if v != nil {
		_u.SetOverview(*v)
	}
	return _u
}

// ClearOverview clears the value of the "overview" field.
func (_u *DomainReportUpdate) ClearOverview() *DomainReportUpdate {
	_u.mutation.ClearOverview()
	return _u
}

// SetTrends sets the "trends" field.
func (_u *DomainReportUpdate) SetTrends(v string) *DomainReportUpdate {
	_u.mutation.SetTrends(v)
	return _u
}

// SetNillableTrends sets the "trends" field if the given value is not nil.
func (_u *DomainReportUpdate) SetNillableTrends(v *string) *DomainReportUpdate {
	if v != nil {
		_u.SetTrends(*v)
	}
	return _u
}

// ClearTrends clears the value of the "trends" field.
func (_u *DomainReportUpdate) ClearTrends() *DomainReportUpdate {
	_u.mutation.ClearTrends()
	return _u
}

// SetScore sets the "score" field.
func (_u *DomainReportUpdate) SetScore(v int) *DomainReportUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *DomainReportUpdate) SetNillableScore(v *int) *DomainReportUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *DomainReportUpdate) AddScore(v int) *DomainReportUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// ClearScore clears the value of the "score" field.
func (_u *DomainReportUpdate) ClearScore() *DomainReportUpdate {
	_u.mutation.ClearScore()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DomainReportUpdate) SetCreatedAt(v time.Time) *DomainReportUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DomainReportUpdate) SetNillableCreatedAt(v *time.Time) *DomainReportUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetReportRunID sets the "report_run" edge to the ReportRun entity by ID.
func (_u *DomainReportUpdate) SetReportRunID(id int) *DomainReportUpdate {
	_u.mutation.SetReportRunID(id)
	return _u
}

// SetNillableReportRunID sets the "report_run" edge to the ReportRun entity by ID if the given value is not nil.
func (_u *DomainReportUpdate) SetNillableReportRunID(id *int) *DomainReportUpdate {
	if id != nil {
		_u = _u.SetReportRunID(*id)
	}
	return _u
}

// SetReportRun sets the "report_run" edge to the ReportRun entity.
func (_u *DomainReportUpdate) SetReportRun(v *ReportRun) *DomainReportUpdate {
	return _u.SetReportRunID(v.ID)
}

// AddArticleIDs adds the "articles" edge to the Article entity by IDs.
func (_u *DomainReportUpdate) AddArticleIDs(ids ...int) *DomainReportUpdate {
	_u.mutation.AddArticleIDs(ids...)
	return _u
}

// AddArticles adds the "articles" edges to the Article entity.
func (_u *DomainReportUpdate) AddArticles(v ...*Article) *DomainReportUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddArticleIDs(ids...)
}

// AddKeyEventIDs adds the "key_events" edge to the KeyEvent entity by IDs.
func (_u *DomainReportUpdate) AddKeyEventIDs(ids ...int) *DomainReportUpdate {
	_u.mutation.AddKeyEventIDs(ids...)
	return _u
}

// AddKeyEvents adds the "key_events" edges to the KeyEvent entity.
func (_u *DomainReportUpdate) AddKeyEvents(v ...*KeyEvent) *DomainReportUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddKeyEventIDs(ids...)
}

// Mutation returns the DomainReportMutation object of the builder.
func (_u *DomainReportUpdate) Mutation() *DomainReportMutation {
	return _u.mutation
}

// ClearReportRun clears the "report_run" edge to the ReportRun entity.
func (_u *DomainReportUpdate) ClearReportRun() *DomainReportUpdate {
	_u.mutation.ClearReportRun()
	return _u
}

// ClearArticles clears all "articles" edges to the Article entity.
func (_u *DomainReportUpdate) ClearArticles() *DomainReportUpdate {
	_u.mutation.ClearArticles()
	return _u
}

// RemoveArticleIDs removes the "articles" edge to Article entities by IDs.
func (_u *DomainReportUpdate) RemoveArticleIDs(ids ...int) *DomainReportUpdate {
	_u.mutation.RemoveArticleIDs(ids...)
	return _u
}

// RemoveArticles removes "articles" edges to Article entities.
func (_u *DomainReportUpdate) RemoveArticles(v ...*Article) *DomainReportUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveArticleIDs(ids...)
}

// ClearKeyEvents clears all "key_events" edges to the KeyEvent entity.
func (_u *DomainReportUpdate) ClearKeyEvents() *DomainReportUpdate {
	_u.mutation.ClearKeyEvents()
	return _u
}

// RemoveKeyEventIDs removes the "key_events" edge to KeyEvent entities by IDs.
func (_u *DomainReportUpdate) RemoveKeyEventIDs(ids ...int) *DomainReportUpdate {
	_u.mutation.RemoveKeyEventIDs(ids...)
	return _u
}

// RemoveKeyEvents removes "key_events" edges to KeyEvent entities.
func (_u *DomainReportUpdate) RemoveKeyEvents(v ...*KeyEvent) *DomainReportUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveKeyEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DomainReportUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DomainReportUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DomainReportUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DomainReportUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DomainReportUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DomainReportUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DomainReportUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(domainreport.Table, domainreport.Columns, sqlgraph.NewFieldSpec(domainreport.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DomainName(); ok {
		_spec.SetField(domainreport.FieldDomainName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Overview(); ok {
		_spec.SetField(domainreport.FieldOverview, field.TypeString, value)
	}
	if _u.mutation.OverviewCleared() {
		_spec.ClearField(domainreport.FieldOverview, field.TypeString)
	}
	if value, ok := _u.mutation.Trends(); ok {
		_spec.SetField(domainreport.FieldTrends, field.TypeString, value)
	}
	if _u.mutation.TrendsCleared() {
		_spec.ClearField(domainreport.FieldTrends, field.TypeString)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(domainreport.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(domainreport.FieldScore, field.TypeInt, value)
	}
	if _u.mutation.ScoreCleared() {
		_spec.ClearField(domainreport.FieldScore, field.TypeInt)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(domainreport.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ReportRunCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   domainreport.ReportRunTable,
			Columns: []string{domainreport.ReportRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportrun.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReportRunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   domainreport.ReportRunTable,
			Columns: []string{domainreport.ReportRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportrun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ArticlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   domainreport.ArticlesTable,
			Columns: []string{domainreport.ArticlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedArticlesIDs(); len(nodes) > 0 && !_u.mutation.ArticlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   domainreport.ArticlesTable,
			Columns: []string{domainreport.ArticlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArticlesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   domainreport.ArticlesTable,
			Columns: []string{domainreport.ArticlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.KeyEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   domainreport.KeyEventsTable,
			Columns: []string{domainreport.KeyEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(keyevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedKeyEventsIDs(); len(nodes) > 0 && !_u.mutation.KeyEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   domainreport.KeyEventsTable,
			Columns: []string{domainreport.KeyEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(keyevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.KeyEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   domainreport.KeyEventsTable,
			Columns: []string{domainreport.KeyEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(keyevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{domainreport.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DomainReportUpdateOne is the builder for updating a single DomainReport entity.
type DomainReportUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DomainReportMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetRunID sets the "run_id" field.
func (_u *DomainReportUpdateOne) SetRunID(v int) *DomainReportUpdateOne {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *DomainReportUpdateOne) SetNillableRunID(v *int) *DomainReportUpdateOne {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// ClearRunID clears the value of the "run_id" field.
func (_u *DomainReportUpdateOne) ClearRunID() *DomainReportUpdateOne {
	_u.mutation.ClearRunID()
	return _u
}

// SetDomainName sets the "domain_name" field.
func (_u *DomainReportUpdateOne) SetDomainName(v string) *DomainReportUpdateOne {
	_u.mutation.SetDomainName(v)
	return _u
}

// SetNillableDomainName sets the "domain_name" field if the given value is not nil.
func (_u *DomainReportUpdateOne) SetNillableDomainName(v *string) *DomainReportUpdateOne {
	if v != nil {
		_u.SetDomainName(*v)
	}
	return _u
}

// SetOverview sets the "overview" field.
func (_u *DomainReportUpdateOne) SetOverview(v string) *DomainReportUpdateOne {
	_u.mutation.SetOverview(v)
	return _u
}

// SetNillableOverview sets the "overview" field if the given value is not nil.
func (_u *DomainReportUpdateOne) SetNillableOverview(v *string) *DomainReportUpdateOne {
	if v != nil {
		_u.SetOverview(*v)
	}
	return _u
}

// ClearOverview clears the value of the "overview" field.
func (_u *DomainReportUpdateOne) ClearOverview() *DomainReportUpdateOne {
	_u.mutation.ClearOverview()
	return _u
}

// SetTrends sets the "trends" field.
func (_u *DomainReportUpdateOne) SetTrends(v string) *DomainReportUpdateOne {
	_u.mutation.SetTrends(v)
	return _u
}

// SetNillableTrends sets the "trends" field if the given value is not nil.
func (_u *DomainReportUpdateOne) SetNillableTrends(v *string) *DomainReportUpdateOne {
	if v != nil {
		_u.SetTrends(*v)
	}
	return _u
}

// ClearTrends clears the value of the "trends" field.
func (_u *DomainReportUpdateOne) ClearTrends() *DomainReportUpdateOne {
	_u.mutation.ClearTrends()
	return _u
}

// SetScore sets the "score" field.
func (_u *DomainReportUpdateOne) SetScore(v int) *DomainReportUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *DomainReportUpdateOne) SetNillableScore(v *int) *DomainReportUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *DomainReportUpdateOne) AddScore(v int) *DomainReportUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// ClearScore clears the value of the "score" field.
func (_u *DomainReportUpdateOne) ClearScore() *DomainReportUpdateOne {
	_u.mutation.ClearScore()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DomainReportUpdateOne) SetCreatedAt(v time.Time) *DomainReportUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DomainReportUpdateOne) SetNillableCreatedAt(v *time.Time) *DomainReportUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetReportRunID sets the "report_run" edge to the ReportRun entity by ID.
func (_u *DomainReportUpdateOne) SetReportRunID(id int) *DomainReportUpdateOne {
	_u.mutation.SetReportRunID(id)
	return _u
}

// SetNillableReportRunID sets the "report_run" edge to the ReportRun entity by ID if the given value is not nil.
func (_u *DomainReportUpdateOne) SetNillableReportRunID(id *int) *DomainReportUpdateOne {
	if id != nil {
		_u = _u.SetReportRunID(*id)
	}
	return _u
}

// SetReportRun sets the "report_run" edge to the ReportRun entity.
func (_u *DomainReportUpdateOne) SetReportRun(v *ReportRun) *DomainReportUpdateOne {
	return _u.SetReportRunID(v.ID)
}

// AddArticleIDs adds the "articles" edge to the Article entity by IDs.
func (_u *DomainReportUpdateOne) AddArticleIDs(ids ...int) *DomainReportUpdateOne {
	_u.mutation.AddArticleIDs(ids...)
	return _u
}

// AddArticles adds the "articles" edges to the Article entity.
func (_u *DomainReportUpdateOne) AddArticles(v ...*Article) *DomainReportUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddArticleIDs(ids...)
}

// AddKeyEventIDs adds the "key_events" edge to the KeyEvent entity by IDs.
func (_u *DomainReportUpdateOne) AddKeyEventIDs(ids ...int) *DomainReportUpdateOne {
	_u.mutation.AddKeyEventIDs(ids...)
	return _u
}

// AddKeyEvents adds the "key_events" edges to the KeyEvent entity.
func (_u *DomainReportUpdateOne) AddKeyEvents(v ...*KeyEvent) *DomainReportUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddKeyEventIDs(ids...)
}

// Mutation returns the DomainReportMutation object of the builder.
func (_u *DomainReportUpdateOne) Mutation() *DomainReportMutation {
	return _u.mutation
}

// ClearReportRun clears the "report_run" edge to the ReportRun entity.
func (_u *DomainReportUpdateOne) ClearReportRun() *DomainReportUpdateOne {
	_u.mutation.ClearReportRun()
	return _u
}

// ClearArticles clears all "articles" edges to the Article entity.
func (_u *DomainReportUpdateOne) ClearArticles() *DomainReportUpdateOne {
	_u.mutation.ClearArticles()
	return _u
}

// RemoveArticleIDs removes the "articles" edge to Article entities by IDs.
func (_u *DomainReportUpdateOne) RemoveArticleIDs(ids ...int) *DomainReportUpdateOne {
	_u.mutation.RemoveArticleIDs(ids...)
	return _u
}

// RemoveArticles removes "articles" edges to Article entities.
func (_u *DomainReportUpdateOne) RemoveArticles(v ...*Article) *DomainReportUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveArticleIDs(ids...)
}

// ClearKeyEvents clears all "key_events" edges to the KeyEvent entity.
func (_u *DomainReportUpdateOne) ClearKeyEvents() *DomainReportUpdateOne {
	_u.mutation.ClearKeyEvents()
	return _u
}

// RemoveKeyEventIDs removes the "key_events" edge to KeyEvent entities by IDs.
func (_u *DomainReportUpdateOne) RemoveKeyEventIDs(ids ...int) *DomainReportUpdateOne {
	_u.mutation.RemoveKeyEventIDs(ids...)
	return _u
}

// RemoveKeyEvents removes "key_events" edges to KeyEvent entities.
func (_u *DomainReportUpdateOne) RemoveKeyEvents(v ...*KeyEvent) *DomainReportUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveKeyEventIDs(ids...)
}

// Where appends a list predicates to the DomainReportUpdate builder.
func (_u *DomainReportUpdateOne) Where(ps ...predicate.DomainReport) *DomainReportUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DomainReportUpdateOne) Select(field string, fields ...string) *DomainReportUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DomainReport entity.
func (_u *DomainReportUpdateOne) Save(ctx context.Context) (*DomainReport, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DomainReportUpdateOne) SaveX(ctx context.Context) *DomainReport {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DomainReportUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DomainReportUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DomainReportUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DomainReportUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DomainReportUpdateOne) sqlSave(ctx context.Context) (_node *DomainReport, err error) {
	_spec := sqlgraph.NewUpdateSpec(domainreport.Table, domainreport.Columns, sqlgraph.NewFieldSpec(domainreport.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DomainReport.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, domainreport.FieldID)
		for _, f := range fields {
			if !domainreport.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != domainreport.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DomainName(); ok {
		_spec.SetField(domainreport.FieldDomainName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Overview(); ok {
		_spec.SetField(domainreport.FieldOverview, field.TypeString, value)
	}
	if _u.mutation.OverviewCleared() {
		_spec.ClearField(domainreport.FieldOverview, field.TypeString)
	}
	if value, ok := _u.mutation.Trends(); ok {
		_spec.SetField(domainreport.FieldTrends, field.TypeString, value)
	}
	if _u.mutation.TrendsCleared() {
		_spec.ClearField(domainreport.FieldTrends, field.TypeString)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(domainreport.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(domainreport.FieldScore, field.TypeInt, value)
	}
	if _u.mutation.ScoreCleared() {
		_spec.ClearField(domainreport.FieldScore, field.TypeInt)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(domainreport.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ReportRunCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   domainreport.ReportRunTable,
			Columns: []string{domainreport.ReportRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportrun.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReportRunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   domainreport.ReportRunTable,
			Columns: []string{domainreport.ReportRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportrun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ArticlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   domainreport.ArticlesTable,
			Columns: []string{domainreport.ArticlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedArticlesIDs(); len(nodes) > 0 && !_u.mutation.ArticlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   domainreport.ArticlesTable,
			Columns: []string{domainreport.ArticlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArticlesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   domainreport.ArticlesTable,
			Columns: []string{domainreport.ArticlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.KeyEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   domainreport.KeyEventsTable,
			Columns: []string{domainreport.KeyEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(keyevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedKeyEventsIDs(); len(nodes) > 0 && !_u.mutation.KeyEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   domainreport.KeyEventsTable,
			Columns: []string{domainreport.KeyEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(keyevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.KeyEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   domainreport.KeyEventsTable,
			Columns: []string{domainreport.KeyEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(keyevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &DomainReport{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{domainreport.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
