// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iWorld-y/domain_radar/app/common/ent/domainreport"
	"github.com/iWorld-y/domain_radar/app/common/ent/keyevent"
	"github.com/iWorld-y/domain_radar/app/common/ent/predicate"
)

// KeyEventUpdate is the builder for updating KeyEvent entities.
type KeyEventUpdate struct {
	config
	hooks     []Hook
	mutation  *KeyEventMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the KeyEventUpdate builder.
func (_u *KeyEventUpdate) Where(ps ...predicate.KeyEvent) *KeyEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDomainReportID sets the "domain_report_id" field.
func (_u *KeyEventUpdate) SetDomainReportID(v int) *KeyEventUpdate {
	_u.mutation.SetDomainReportID(v)
	return _u
}

// SetNillableDomainReportID sets the "domain_report_id" field if the given value is not nil.
func (_u *KeyEventUpdate) SetNillableDomainReportID(v *int) *KeyEventUpdate {
	if v != nil {
		_u.SetDomainReportID(*v)
	}
	return _u
}

// ClearDomainReportID clears the value of the "domain_report_id" field.
func (_u *KeyEventUpdate) ClearDomainReportID() *KeyEventUpdate {
	_u.mutation.ClearDomainReportID()
	return _u
}

// SetEventContent sets the "event_content" field.
func (_u *KeyEventUpdate) SetEventContent(v string) *KeyEventUpdate {
	_u.mutation.SetEventContent(v)
	return _u
}

// SetNillableEventContent sets the "event_content" field if the given value is not nil.
func (_u *KeyEventUpdate) SetNillableEventContent(v *string) *KeyEventUpdate {
	if v != nil {
		_u.SetEventContent(*v)
	}
	return _u
}

// ClearEventContent clears the value of the "event_content" field.
func (_u *KeyEventUpdate) ClearEventContent() *KeyEventUpdate {
	_u.mutation.ClearEventContent()
	return _u
}

// SetDomainReport sets the "domain_report" edge to the DomainReport entity.
func (_u *KeyEventUpdate) SetDomainReport(v *DomainReport) *KeyEventUpdate {
	return _u.SetDomainReportID(v.ID)
}

// Mutation returns the KeyEventMutation object of the builder.
func (_u *KeyEventUpdate) Mutation() *KeyEventMutation {
	return _u.mutation
}

// ClearDomainReport clears the "domain_report" edge to the DomainReport entity.
func (_u *KeyEventUpdate) ClearDomainReport() *KeyEventUpdate {
	_u.mutation.ClearDomainReport()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KeyEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KeyEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KeyEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KeyEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *KeyEventUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *KeyEventUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *KeyEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(keyevent.Table, keyevent.Columns, sqlgraph.NewFieldSpec(keyevent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventContent(); ok {
		_spec.SetField(keyevent.FieldEventContent, field.TypeString, value)
	}
	if _u.mutation.EventContentCleared() {
		_spec.ClearField(keyevent.FieldEventContent, field.TypeString)
	}
	if _u.mutation.DomainReportCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   keyevent.DomainReportTable,
			Columns: []string{keyevent.DomainReportColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domainreport.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DomainReportIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   keyevent.DomainReportTable,
			Columns: []string{keyevent.DomainReportColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domainreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{keyevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KeyEventUpdateOne is the builder for updating a single KeyEvent entity.
type KeyEventUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *KeyEventMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDomainReportID sets the "domain_report_id" field.
func (_u *KeyEventUpdateOne) SetDomainReportID(v int) *KeyEventUpdateOne {
	_u.mutation.SetDomainReportID(v)
	return _u
}

// SetNillableDomainReportID sets the "domain_report_id" field if the given value is not nil.
func (_u *KeyEventUpdateOne) SetNillableDomainReportID(v *int) *KeyEventUpdateOne {
	if v != nil {
		_u.SetDomainReportID(*v)
	}
	return _u
}

// ClearDomainReportID clears the value of the "domain_report_id" field.
func (_u *KeyEventUpdateOne) ClearDomainReportID() *KeyEventUpdateOne {
	_u.mutation.ClearDomainReportID()
	return _u
}

// SetEventContent sets the "event_content" field.
func (_u *KeyEventUpdateOne) SetEventContent(v string) *KeyEventUpdateOne {
	_u.mutation.SetEventContent(v)
	return _u
}

// SetNillableEventContent sets the "event_content" field if the given value is not nil.
func (_u *KeyEventUpdateOne) SetNillableEventContent(v *string) *KeyEventUpdateOne {
	if v != nil {
		_u.SetEventContent(*v)
	}
	return _u
}

// ClearEventContent clears the value of the "event_content" field.
func (_u *KeyEventUpdateOne) ClearEventContent() *KeyEventUpdateOne {
	_u.mutation.ClearEventContent()
	return _u
}

// SetDomainReport sets the "domain_report" edge to the DomainReport entity.
func (_u *KeyEventUpdateOne) SetDomainReport(v *DomainReport) *KeyEventUpdateOne {
	return _u.SetDomainReportID(v.ID)
}

// Mutation returns the KeyEventMutation object of the builder.
func (_u *KeyEventUpdateOne) Mutation() *KeyEventMutation {
	return _u.mutation
}

// ClearDomainReport clears the "domain_report" edge to the DomainReport entity.
func (_u *KeyEventUpdateOne) ClearDomainReport() *KeyEventUpdateOne {
	_u.mutation.ClearDomainReport()
	return _u
}

// Where appends a list predicates to the KeyEventUpdate builder.
func (_u *KeyEventUpdateOne) Where(ps ...predicate.KeyEvent) *KeyEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KeyEventUpdateOne) Select(field string, fields ...string) *KeyEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated KeyEvent entity.
func (_u *KeyEventUpdateOne) Save(ctx context.Context) (*KeyEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KeyEventUpdateOne) SaveX(ctx context.Context) *KeyEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KeyEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KeyEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *KeyEventUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *KeyEventUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *KeyEventUpdateOne) sqlSave(ctx context.Context) (_node *KeyEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(keyevent.Table, keyevent.Columns, sqlgraph.NewFieldSpec(keyevent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "KeyEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, keyevent.FieldID)
		for _, f := range fields {
			if !keyevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != keyevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventContent(); ok {
		_spec.SetField(keyevent.FieldEventContent, field.TypeString, value)
	}
	if _u.mutation.EventContentCleared() {
		_spec.ClearField(keyevent.FieldEventContent, field.TypeString)
	}
	if _u.mutation.DomainReportCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   keyevent.DomainReportTable,
			Columns: []string{keyevent.DomainReportColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domainreport.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DomainReportIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   keyevent.DomainReportTable,
			Columns: []string{keyevent.DomainReportColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domainreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &KeyEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{keyevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
