// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/iWorld-y/domain_radar/app/common/ent/domainreport"
	"github.com/iWorld-y/domain_radar/app/common/ent/keyevent"
)

// KeyEvent is the model entity for the KeyEvent schema.
type KeyEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// DomainReportID holds the value of the "domain_report_id" field.
	DomainReportID int `json:"domain_report_id,omitempty"`
	// EventContent holds the value of the "event_content" field.
	EventContent string `json:"event_content,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the KeyEventQuery when eager-loading is set.
	Edges        KeyEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// KeyEventEdges holds the relations/edges for other nodes in the graph.
type KeyEventEdges struct {
	// DomainReport holds the value of the domain_report edge.
	DomainReport *DomainReport `json:"domain_report,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DomainReportOrErr returns the DomainReport value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e KeyEventEdges) DomainReportOrErr() (*DomainReport, error) {
	if e.DomainReport != nil {
		return e.DomainReport, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: domainreport.Label}
	}
	return nil, &NotLoadedError{edge: "domain_report"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*KeyEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case keyevent.FieldID, keyevent.FieldDomainReportID:
			values[i] = new(sql.NullInt64)
		case keyevent.FieldEventContent:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the KeyEvent fields.
func (_m *KeyEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case keyevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case keyevent.FieldDomainReportID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field domain_report_id", values[i])
			} else if value.Valid {
				_m.DomainReportID = int(value.Int64)
			}
		case keyevent.FieldEventContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_content", values[i])
			} else if value.Valid {
				_m.EventContent = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the KeyEvent.
// This includes values selected through modifiers, order, etc.
func (_m *KeyEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDomainReport queries the "domain_report" edge of the KeyEvent entity.
func (_m *KeyEvent) QueryDomainReport() *DomainReportQuery {
	return NewKeyEventClient(_m.config).QueryDomainReport(_m)
}

// Update returns a builder for updating this KeyEvent.
// Note that you need to call KeyEvent.Unwrap() before calling this method if this KeyEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *KeyEvent) Update() *KeyEventUpdateOne {
	return NewKeyEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the KeyEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *KeyEvent) Unwrap() *KeyEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: KeyEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *KeyEvent) String() string {
	var builder strings.Builder
	builder.WriteString("KeyEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("domain_report_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DomainReportID))
	builder.WriteString(", ")
	builder.WriteString("event_content=")
	builder.WriteString(_m.EventContent)
	builder.WriteByte(')')
	return builder.String()
}

// KeyEvents is a parsable slice of KeyEvent.
type KeyEvents []*KeyEvent
