// Code generated by ent, DO NOT EDIT.

package actionguide

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the actionguide type in the database.
	Label = "action_guide"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeepAnalysisID holds the string denoting the deep_analysis_id field in the database.
	FieldDeepAnalysisID = "deep_analysis_id"
	// FieldGuideContent holds the string denoting the guide_content field in the database.
	FieldGuideContent = "guide_content"
	// EdgeDeepAnalysisResult holds the string denoting the deep_analysis_result edge name in mutations.
	EdgeDeepAnalysisResult = "deep_analysis_result"
	// Table holds the table name of the actionguide in the database.
	Table = "action_guides"
	// DeepAnalysisResultTable is the table that holds the deep_analysis_result relation/edge.
	DeepAnalysisResultTable = "action_guides"
	// DeepAnalysisResultInverseTable is the table name for the DeepAnalysisResult entity.
	// It exists in this package in order to avoid circular dependency with the "deepanalysisresult" package.
	DeepAnalysisResultInverseTable = "deep_analysis_results"
	// DeepAnalysisResultColumn is the table column denoting the deep_analysis_result relation/edge.
	DeepAnalysisResultColumn = "deep_analysis_id"
)

// Columns holds all SQL columns for actionguide fields.
var Columns = []string{
	FieldID,
	FieldDeepAnalysisID,
	FieldGuideContent,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the ActionGuide queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeepAnalysisID orders the results by the deep_analysis_id field.
func ByDeepAnalysisID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeepAnalysisID, opts...).ToFunc()
}

// ByGuideContent orders the results by the guide_content field.
func ByGuideContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGuideContent, opts...).ToFunc()
}

// ByDeepAnalysisResultField orders the results by deep_analysis_result field.
func ByDeepAnalysisResultField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDeepAnalysisResultStep(), sql.OrderByField(field, opts...))
	}
}
func newDeepAnalysisResultStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DeepAnalysisResultInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DeepAnalysisResultTable, DeepAnalysisResultColumn),
	)
}
