// Code generated by ent, DO NOT EDIT.

package actionguide

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/iWorld-y/domain_radar/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldLTE(FieldID, id))
}

// DeepAnalysisID applies equality check predicate on the "deep_analysis_id" field. It's identical to DeepAnalysisIDEQ.
func DeepAnalysisID(v int) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldEQ(FieldDeepAnalysisID, v))
}

// GuideContent applies equality check predicate on the "guide_content" field. It's identical to GuideContentEQ.
func GuideContent(v string) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldEQ(FieldGuideContent, v))
}

// DeepAnalysisIDEQ applies the EQ predicate on the "deep_analysis_id" field.
func DeepAnalysisIDEQ(v int) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldEQ(FieldDeepAnalysisID, v))
}

// DeepAnalysisIDNEQ applies the NEQ predicate on the "deep_analysis_id" field.
func DeepAnalysisIDNEQ(v int) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldNEQ(FieldDeepAnalysisID, v))
}

// DeepAnalysisIDIn applies the In predicate on the "deep_analysis_id" field.
func DeepAnalysisIDIn(vs ...int) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldIn(FieldDeepAnalysisID, vs...))
}

// DeepAnalysisIDNotIn applies the NotIn predicate on the "deep_analysis_id" field.
func DeepAnalysisIDNotIn(vs ...int) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldNotIn(FieldDeepAnalysisID, vs...))
}

// DeepAnalysisIDIsNil applies the IsNil predicate on the "deep_analysis_id" field.
func DeepAnalysisIDIsNil() predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldIsNull(FieldDeepAnalysisID))
}

// DeepAnalysisIDNotNil applies the NotNil predicate on the "deep_analysis_id" field.
func DeepAnalysisIDNotNil() predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldNotNull(FieldDeepAnalysisID))
}

// GuideContentEQ applies the EQ predicate on the "guide_content" field.
func GuideContentEQ(v string) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldEQ(FieldGuideContent, v))
}

// GuideContentNEQ applies the NEQ predicate on the "guide_content" field.
func GuideContentNEQ(v string) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldNEQ(FieldGuideContent, v))
}

// GuideContentIn applies the In predicate on the "guide_content" field.
func GuideContentIn(vs ...string) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldIn(FieldGuideContent, vs...))
}

// GuideContentNotIn applies the NotIn predicate on the "guide_content" field.
func GuideContentNotIn(vs ...string) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldNotIn(FieldGuideContent, vs...))
}

// GuideContentGT applies the GT predicate on the "guide_content" field.
func GuideContentGT(v string) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldGT(FieldGuideContent, v))
}

// GuideContentGTE applies the GTE predicate on the "guide_content" field.
func GuideContentGTE(v string) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldGTE(FieldGuideContent, v))
}

// GuideContentLT applies the LT predicate on the "guide_content" field.
func GuideContentLT(v string) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldLT(FieldGuideContent, v))
}

// GuideContentLTE applies the LTE predicate on the "guide_content" field.
func GuideContentLTE(v string) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldLTE(FieldGuideContent, v))
}

// GuideContentContains applies the Contains predicate on the "guide_content" field.
func GuideContentContains(v string) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldContains(FieldGuideContent, v))
}

// GuideContentHasPrefix applies the HasPrefix predicate on the "guide_content" field.
func GuideContentHasPrefix(v string) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldHasPrefix(FieldGuideContent, v))
}

// GuideContentHasSuffix applies the HasSuffix predicate on the "guide_content" field.
func GuideContentHasSuffix(v string) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldHasSuffix(FieldGuideContent, v))
}

// GuideContentIsNil applies the IsNil predicate on the "guide_content" field.
func GuideContentIsNil() predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldIsNull(FieldGuideContent))
}

// GuideContentNotNil applies the NotNil predicate on the "guide_content" field.
func GuideContentNotNil() predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldNotNull(FieldGuideContent))
}

// GuideContentEqualFold applies the EqualFold predicate on the "guide_content" field.
func GuideContentEqualFold(v string) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldEqualFold(FieldGuideContent, v))
}

// GuideContentContainsFold applies the ContainsFold predicate on the "guide_content" field.
func GuideContentContainsFold(v string) predicate.ActionGuide {
	return predicate.ActionGuide(sql.FieldContainsFold(FieldGuideContent, v))
}

// HasDeepAnalysisResult applies the HasEdge predicate on the "deep_analysis_result" edge.
func HasDeepAnalysisResult() predicate.ActionGuide {
	return predicate.ActionGuide(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DeepAnalysisResultTable, DeepAnalysisResultColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeepAnalysisResultWith applies the HasEdge predicate on the "deep_analysis_result" edge with a given conditions (other predicates).
func HasDeepAnalysisResultWith(preds ...predicate.DeepAnalysisResult) predicate.ActionGuide {
	return predicate.ActionGuide(func(s *sql.Selector) {
		step := newDeepAnalysisResultStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ActionGuide) predicate.ActionGuide {
	return predicate.ActionGuide(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ActionGuide) predicate.ActionGuide {
	return predicate.ActionGuide(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ActionGuide) predicate.ActionGuide {
	return predicate.ActionGuide(sql.NotPredicates(p))
}
