// Code generated by ent, DO NOT EDIT.

package deepanalysisresult

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/iWorld-y/domain_radar/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldLTE(FieldID, id))
}

// RunID applies equality check predicate on the "run_id" field. It's identical to RunIDEQ.
func RunID(v int) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldEQ(FieldRunID, v))
}

// MacroTrends applies equality check predicate on the "macro_trends" field. It's identical to MacroTrendsEQ.
func MacroTrends(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldEQ(FieldMacroTrends, v))
}

// Opportunities applies equality check predicate on the "opportunities" field. It's identical to OpportunitiesEQ.
func Opportunities(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldEQ(FieldOpportunities, v))
}

// Risks applies equality check predicate on the "risks" field. It's identical to RisksEQ.
func Risks(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldEQ(FieldRisks, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldEQ(FieldCreatedAt, v))
}

// RunIDEQ applies the EQ predicate on the "run_id" field.
func RunIDEQ(v int) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldEQ(FieldRunID, v))
}

// RunIDNEQ applies the NEQ predicate on the "run_id" field.
func RunIDNEQ(v int) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldNEQ(FieldRunID, v))
}

// RunIDIn applies the In predicate on the "run_id" field.
func RunIDIn(vs ...int) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldIn(FieldRunID, vs...))
}

// RunIDNotIn applies the NotIn predicate on the "run_id" field.
func RunIDNotIn(vs ...int) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldNotIn(FieldRunID, vs...))
}

// RunIDIsNil applies the IsNil predicate on the "run_id" field.
func RunIDIsNil() predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldIsNull(FieldRunID))
}

// RunIDNotNil applies the NotNil predicate on the "run_id" field.
func RunIDNotNil() predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldNotNull(FieldRunID))
}

// MacroTrendsEQ applies the EQ predicate on the "macro_trends" field.
func MacroTrendsEQ(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldEQ(FieldMacroTrends, v))
}

// MacroTrendsNEQ applies the NEQ predicate on the "macro_trends" field.
func MacroTrendsNEQ(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldNEQ(FieldMacroTrends, v))
}

// MacroTrendsIn applies the In predicate on the "macro_trends" field.
func MacroTrendsIn(vs ...string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldIn(FieldMacroTrends, vs...))
}

// MacroTrendsNotIn applies the NotIn predicate on the "macro_trends" field.
func MacroTrendsNotIn(vs ...string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldNotIn(FieldMacroTrends, vs...))
}

// MacroTrendsGT applies the GT predicate on the "macro_trends" field.
func MacroTrendsGT(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldGT(FieldMacroTrends, v))
}

// MacroTrendsGTE applies the GTE predicate on the "macro_trends" field.
func MacroTrendsGTE(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldGTE(FieldMacroTrends, v))
}

// MacroTrendsLT applies the LT predicate on the "macro_trends" field.
func MacroTrendsLT(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldLT(FieldMacroTrends, v))
}

// MacroTrendsLTE applies the LTE predicate on the "macro_trends" field.
func MacroTrendsLTE(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldLTE(FieldMacroTrends, v))
}

// MacroTrendsContains applies the Contains predicate on the "macro_trends" field.
func MacroTrendsContains(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldContains(FieldMacroTrends, v))
}

// MacroTrendsHasPrefix applies the HasPrefix predicate on the "macro_trends" field.
func MacroTrendsHasPrefix(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldHasPrefix(FieldMacroTrends, v))
}

// MacroTrendsHasSuffix applies the HasSuffix predicate on the "macro_trends" field.
func MacroTrendsHasSuffix(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldHasSuffix(FieldMacroTrends, v))
}

// MacroTrendsIsNil applies the IsNil predicate on the "macro_trends" field.
func MacroTrendsIsNil() predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldIsNull(FieldMacroTrends))
}

// MacroTrendsNotNil applies the NotNil predicate on the "macro_trends" field.
func MacroTrendsNotNil() predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldNotNull(FieldMacroTrends))
}

// MacroTrendsEqualFold applies the EqualFold predicate on the "macro_trends" field.
func MacroTrendsEqualFold(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldEqualFold(FieldMacroTrends, v))
}

// MacroTrendsContainsFold applies the ContainsFold predicate on the "macro_trends" field.
func MacroTrendsContainsFold(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldContainsFold(FieldMacroTrends, v))
}

// OpportunitiesEQ applies the EQ predicate on the "opportunities" field.
func OpportunitiesEQ(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldEQ(FieldOpportunities, v))
}

// OpportunitiesNEQ applies the NEQ predicate on the "opportunities" field.
func OpportunitiesNEQ(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldNEQ(FieldOpportunities, v))
}

// OpportunitiesIn applies the In predicate on the "opportunities" field.
func OpportunitiesIn(vs ...string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldIn(FieldOpportunities, vs...))
}

// OpportunitiesNotIn applies the NotIn predicate on the "opportunities" field.
func OpportunitiesNotIn(vs ...string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldNotIn(FieldOpportunities, vs...))
}

// OpportunitiesGT applies the GT predicate on the "opportunities" field.
func OpportunitiesGT(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldGT(FieldOpportunities, v))
}

// OpportunitiesGTE applies the GTE predicate on the "opportunities" field.
func OpportunitiesGTE(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldGTE(FieldOpportunities, v))
}

// OpportunitiesLT applies the LT predicate on the "opportunities" field.
func OpportunitiesLT(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldLT(FieldOpportunities, v))
}

// OpportunitiesLTE applies the LTE predicate on the "opportunities" field.
func OpportunitiesLTE(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldLTE(FieldOpportunities, v))
}

// OpportunitiesContains applies the Contains predicate on the "opportunities" field.
func OpportunitiesContains(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldContains(FieldOpportunities, v))
}

// OpportunitiesHasPrefix applies the HasPrefix predicate on the "opportunities" field.
func OpportunitiesHasPrefix(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldHasPrefix(FieldOpportunities, v))
}

// OpportunitiesHasSuffix applies the HasSuffix predicate on the "opportunities" field.
func OpportunitiesHasSuffix(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldHasSuffix(FieldOpportunities, v))
}

// OpportunitiesIsNil applies the IsNil predicate on the "opportunities" field.
func OpportunitiesIsNil() predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldIsNull(FieldOpportunities))
}

// OpportunitiesNotNil applies the NotNil predicate on the "opportunities" field.
func OpportunitiesNotNil() predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldNotNull(FieldOpportunities))
}

// OpportunitiesEqualFold applies the EqualFold predicate on the "opportunities" field.
func OpportunitiesEqualFold(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldEqualFold(FieldOpportunities, v))
}

// OpportunitiesContainsFold applies the ContainsFold predicate on the "opportunities" field.
func OpportunitiesContainsFold(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldContainsFold(FieldOpportunities, v))
}

// RisksEQ applies the EQ predicate on the "risks" field.
func RisksEQ(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldEQ(FieldRisks, v))
}

// RisksNEQ applies the NEQ predicate on the "risks" field.
func RisksNEQ(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldNEQ(FieldRisks, v))
}

// RisksIn applies the In predicate on the "risks" field.
func RisksIn(vs ...string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldIn(FieldRisks, vs...))
}

// RisksNotIn applies the NotIn predicate on the "risks" field.
func RisksNotIn(vs ...string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldNotIn(FieldRisks, vs...))
}

// RisksGT applies the GT predicate on the "risks" field.
func RisksGT(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldGT(FieldRisks, v))
}

// RisksGTE applies the GTE predicate on the "risks" field.
func RisksGTE(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldGTE(FieldRisks, v))
}

// RisksLT applies the LT predicate on the "risks" field.
func RisksLT(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldLT(FieldRisks, v))
}

// RisksLTE applies the LTE predicate on the "risks" field.
func RisksLTE(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldLTE(FieldRisks, v))
}

// RisksContains applies the Contains predicate on the "risks" field.
func RisksContains(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldContains(FieldRisks, v))
}

// RisksHasPrefix applies the HasPrefix predicate on the "risks" field.
func RisksHasPrefix(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldHasPrefix(FieldRisks, v))
}

// RisksHasSuffix applies the HasSuffix predicate on the "risks" field.
func RisksHasSuffix(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldHasSuffix(FieldRisks, v))
}

// RisksIsNil applies the IsNil predicate on the "risks" field.
func RisksIsNil() predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldIsNull(FieldRisks))
}

// RisksNotNil applies the NotNil predicate on the "risks" field.
func RisksNotNil() predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldNotNull(FieldRisks))
}

// RisksEqualFold applies the EqualFold predicate on the "risks" field.
func RisksEqualFold(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldEqualFold(FieldRisks, v))
}

// RisksContainsFold applies the ContainsFold predicate on the "risks" field.
func RisksContainsFold(v string) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldContainsFold(FieldRisks, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.FieldLTE(FieldCreatedAt, v))
}

// HasReportRun applies the HasEdge predicate on the "report_run" edge.
func HasReportRun() predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ReportRunTable, ReportRunColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReportRunWith applies the HasEdge predicate on the "report_run" edge with a given conditions (other predicates).
func HasReportRunWith(preds ...predicate.ReportRun) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(func(s *sql.Selector) {
		step := newReportRunStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasActionGuides applies the HasEdge predicate on the "action_guides" edge.
func HasActionGuides() predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ActionGuidesTable, ActionGuidesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActionGuidesWith applies the HasEdge predicate on the "action_guides" edge with a given conditions (other predicates).
func HasActionGuidesWith(preds ...predicate.ActionGuide) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(func(s *sql.Selector) {
		step := newActionGuidesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DeepAnalysisResult) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DeepAnalysisResult) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DeepAnalysisResult) predicate.DeepAnalysisResult {
	return predicate.DeepAnalysisResult(sql.NotPredicates(p))
}
