// Code generated by ent, DO NOT EDIT.

package article

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/iWorld-y/domain_radar/app/common/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Article {
	return predicate.Article(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Article {
	return predicate.Article(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Article {
	return predicate.Article(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Article {
	return predicate.Article(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Article {
	return predicate.Article(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Article {
	return predicate.Article(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Article {
	return predicate.Article(sql.FieldLTE(FieldID, id))
}

// DomainReportID applies equality check predicate on the "domain_report_id" field. It's identical to DomainReportIDEQ.
func DomainReportID(v int) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldDomainReportID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldTitle, v))
}

// Link applies equality check predicate on the "link" field. It's identical to LinkEQ.
func Link(v string) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldLink, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldSource, v))
}

// PubDate applies equality check predicate on the "pub_date" field. It's identical to PubDateEQ.
func PubDate(v string) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldPubDate, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldContent, v))
}

// DomainReportIDEQ applies the EQ predicate on the "domain_report_id" field.
func DomainReportIDEQ(v int) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldDomainReportID, v))
}

// DomainReportIDNEQ applies the NEQ predicate on the "domain_report_id" field.
func DomainReportIDNEQ(v int) predicate.Article {
	return predicate.Article(sql.FieldNEQ(FieldDomainReportID, v))
}

// DomainReportIDIn applies the In predicate on the "domain_report_id" field.
func DomainReportIDIn(vs ...int) predicate.Article {
	return predicate.Article(sql.FieldIn(FieldDomainReportID, vs...))
}

// DomainReportIDNotIn applies the NotIn predicate on the "domain_report_id" field.
func DomainReportIDNotIn(vs ...int) predicate.Article {
	return predicate.Article(sql.FieldNotIn(FieldDomainReportID, vs...))
}

// DomainReportIDIsNil applies the IsNil predicate on the "domain_report_id" field.
func DomainReportIDIsNil() predicate.Article {
	return predicate.Article(sql.FieldIsNull(FieldDomainReportID))
}

// DomainReportIDNotNil applies the NotNil predicate on the "domain_report_id" field.
func DomainReportIDNotNil() predicate.Article {
	return predicate.Article(sql.FieldNotNull(FieldDomainReportID))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Article {
	return predicate.Article(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Article {
	return predicate.Article(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Article {
	return predicate.Article(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Article {
	return predicate.Article(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Article {
	return predicate.Article(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Article {
	return predicate.Article(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Article {
	return predicate.Article(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Article {
	return predicate.Article(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Article {
	return predicate.Article(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Article {
	return predicate.Article(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleIsNil applies the IsNil predicate on the "title" field.
func TitleIsNil() predicate.Article {
	return predicate.Article(sql.FieldIsNull(FieldTitle))
}

// TitleNotNil applies the NotNil predicate on the "title" field.
func TitleNotNil() predicate.Article {
	return predicate.Article(sql.FieldNotNull(FieldTitle))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Article {
	return predicate.Article(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Article {
	return predicate.Article(sql.FieldContainsFold(FieldTitle, v))
}

// LinkEQ applies the EQ predicate on the "link" field.
func LinkEQ(v string) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldLink, v))
}

// LinkNEQ applies the NEQ predicate on the "link" field.
func LinkNEQ(v string) predicate.Article {
	return predicate.Article(sql.FieldNEQ(FieldLink, v))
}

// LinkIn applies the In predicate on the "link" field.
func LinkIn(vs ...string) predicate.Article {
	return predicate.Article(sql.FieldIn(FieldLink, vs...))
}

// LinkNotIn applies the NotIn predicate on the "link" field.
func LinkNotIn(vs ...string) predicate.Article {
	return predicate.Article(sql.FieldNotIn(FieldLink, vs...))
}

// LinkGT applies the GT predicate on the "link" field.
func LinkGT(v string) predicate.Article {
	return predicate.Article(sql.FieldGT(FieldLink, v))
}

// LinkGTE applies the GTE predicate on the "link" field.
func LinkGTE(v string) predicate.Article {
	return predicate.Article(sql.FieldGTE(FieldLink, v))
}

// LinkLT applies the LT predicate on the "link" field.
func LinkLT(v string) predicate.Article {
	return predicate.Article(sql.FieldLT(FieldLink, v))
}

// LinkLTE applies the LTE predicate on the "link" field.
func LinkLTE(v string) predicate.Article {
	return predicate.Article(sql.FieldLTE(FieldLink, v))
}

// LinkContains applies the Contains predicate on the "link" field.
func LinkContains(v string) predicate.Article {
	return predicate.Article(sql.FieldContains(FieldLink, v))
}

// LinkHasPrefix applies the HasPrefix predicate on the "link" field.
func LinkHasPrefix(v string) predicate.Article {
	return predicate.Article(sql.FieldHasPrefix(FieldLink, v))
}

// LinkHasSuffix applies the HasSuffix predicate on the "link" field.
func LinkHasSuffix(v string) predicate.Article {
	return predicate.Article(sql.FieldHasSuffix(FieldLink, v))
}

// LinkIsNil applies the IsNil predicate on the "link" field.
func LinkIsNil() predicate.Article {
	return predicate.Article(sql.FieldIsNull(FieldLink))
}

// LinkNotNil applies the NotNil predicate on the "link" field.
func LinkNotNil() predicate.Article {
	return predicate.Article(sql.FieldNotNull(FieldLink))
}

// LinkEqualFold applies the EqualFold predicate on the "link" field.
func LinkEqualFold(v string) predicate.Article {
	return predicate.Article(sql.FieldEqualFold(FieldLink, v))
}

// LinkContainsFold applies the ContainsFold predicate on the "link" field.
func LinkContainsFold(v string) predicate.Article {
	return predicate.Article(sql.FieldContainsFold(FieldLink, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.Article {
	return predicate.Article(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.Article {
	return predicate.Article(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.Article {
	return predicate.Article(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.Article {
	return predicate.Article(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.Article {
	return predicate.Article(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.Article {
	return predicate.Article(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.Article {
	return predicate.Article(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.Article {
	return predicate.Article(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.Article {
	return predicate.Article(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.Article {
	return predicate.Article(sql.FieldHasSuffix(FieldSource, v))
}

// SourceIsNil applies the IsNil predicate on the "source" field.
func SourceIsNil() predicate.Article {
	return predicate.Article(sql.FieldIsNull(FieldSource))
}

// SourceNotNil applies the NotNil predicate on the "source" field.
func SourceNotNil() predicate.Article {
	return predicate.Article(sql.FieldNotNull(FieldSource))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.Article {
	return predicate.Article(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.Article {
	return predicate.Article(sql.FieldContainsFold(FieldSource, v))
}

// PubDateEQ applies the EQ predicate on the "pub_date" field.
func PubDateEQ(v string) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldPubDate, v))
}

// PubDateNEQ applies the NEQ predicate on the "pub_date" field.
func PubDateNEQ(v string) predicate.Article {
	return predicate.Article(sql.FieldNEQ(FieldPubDate, v))
}

// PubDateIn applies the In predicate on the "pub_date" field.
func PubDateIn(vs ...string) predicate.Article {
	return predicate.Article(sql.FieldIn(FieldPubDate, vs...))
}

// PubDateNotIn applies the NotIn predicate on the "pub_date" field.
func PubDateNotIn(vs ...string) predicate.Article {
	return predicate.Article(sql.FieldNotIn(FieldPubDate, vs...))
}

// PubDateGT applies the GT predicate on the "pub_date" field.
func PubDateGT(v string) predicate.Article {
	return predicate.Article(sql.FieldGT(FieldPubDate, v))
}

// PubDateGTE applies the GTE predicate on the "pub_date" field.
func PubDateGTE(v string) predicate.Article {
	return predicate.Article(sql.FieldGTE(FieldPubDate, v))
}

// PubDateLT applies the LT predicate on the "pub_date" field.
func PubDateLT(v string) predicate.Article {
	return predicate.Article(sql.FieldLT(FieldPubDate, v))
}

// PubDateLTE applies the LTE predicate on the "pub_date" field.
func PubDateLTE(v string) predicate.Article {
	return predicate.Article(sql.FieldLTE(FieldPubDate, v))
}

// PubDateContains applies the Contains predicate on the "pub_date" field.
func PubDateContains(v string) predicate.Article {
	return predicate.Article(sql.FieldContains(FieldPubDate, v))
}

// PubDateHasPrefix applies the HasPrefix predicate on the "pub_date" field.
func PubDateHasPrefix(v string) predicate.Article {
	return predicate.Article(sql.FieldHasPrefix(FieldPubDate, v))
}

// PubDateHasSuffix applies the HasSuffix predicate on the "pub_date" field.
func PubDateHasSuffix(v string) predicate.Article {
	return predicate.Article(sql.FieldHasSuffix(FieldPubDate, v))
}

// PubDateIsNil applies the IsNil predicate on the "pub_date" field.
func PubDateIsNil() predicate.Article {
	return predicate.Article(sql.FieldIsNull(FieldPubDate))
}

// PubDateNotNil applies the NotNil predicate on the "pub_date" field.
func PubDateNotNil() predicate.Article {
	return predicate.Article(sql.FieldNotNull(FieldPubDate))
}

// PubDateEqualFold applies the EqualFold predicate on the "pub_date" field.
func PubDateEqualFold(v string) predicate.Article {
	return predicate.Article(sql.FieldEqualFold(FieldPubDate, v))
}

// PubDateContainsFold applies the ContainsFold predicate on the "pub_date" field.
func PubDateContainsFold(v string) predicate.Article {
	return predicate.Article(sql.FieldContainsFold(FieldPubDate, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Article {
	return predicate.Article(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Article {
	return predicate.Article(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Article {
	return predicate.Article(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Article {
	return predicate.Article(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Article {
	return predicate.Article(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Article {
	return predicate.Article(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Article {
	return predicate.Article(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Article {
	return predicate.Article(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Article {
	return predicate.Article(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Article {
	return predicate.Article(sql.FieldHasSuffix(FieldContent, v))
}

// ContentIsNil applies the IsNil predicate on the "content" field.
func ContentIsNil() predicate.Article {
	return predicate.Article(sql.FieldIsNull(FieldContent))
}

// ContentNotNil applies the NotNil predicate on the "content" field.
func ContentNotNil() predicate.Article {
	return predicate.Article(sql.FieldNotNull(FieldContent))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Article {
	return predicate.Article(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Article {
	return predicate.Article(sql.FieldContainsFold(FieldContent, v))
}

// HasDomainReport applies the HasEdge predicate on the "domain_report" edge.
func HasDomainReport() predicate.Article {
	return predicate.Article(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DomainReportTable, DomainReportColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDomainReportWith applies the HasEdge predicate on the "domain_report" edge with a given conditions (other predicates).
func HasDomainReportWith(preds ...predicate.DomainReport) predicate.Article {
	return predicate.Article(func(s *sql.Selector) {
		step := newDomainReportStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Article) predicate.Article {
	return predicate.Article(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Article) predicate.Article {
	return predicate.Article(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Article) predicate.Article {
	return predicate.Article(sql.NotPredicates(p))
}
