// Code generated by ent, DO NOT EDIT.

package reportrun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the reportrun type in the database.
	Label = "report_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeDomainReports holds the string denoting the domain_reports edge name in mutations.
	EdgeDomainReports = "domain_reports"
	// EdgeDeepAnalysisResults holds the string denoting the deep_analysis_results edge name in mutations.
	EdgeDeepAnalysisResults = "deep_analysis_results"
	// Table holds the table name of the reportrun in the database.
	Table = "report_runs"
	// DomainReportsTable is the table that holds the domain_reports relation/edge.
	DomainReportsTable = "domain_reports"
	// DomainReportsInverseTable is the table name for the DomainReport entity.
	// It exists in this package in order to avoid circular dependency with the "domainreport" package.
	DomainReportsInverseTable = "domain_reports"
	// DomainReportsColumn is the table column denoting the domain_reports relation/edge.
	DomainReportsColumn = "run_id"
	// DeepAnalysisResultsTable is the table that holds the deep_analysis_results relation/edge.
	DeepAnalysisResultsTable = "deep_analysis_results"
	// DeepAnalysisResultsInverseTable is the table name for the DeepAnalysisResult entity.
	// It exists in this package in order to avoid circular dependency with the "deepanalysisresult" package.
	DeepAnalysisResultsInverseTable = "deep_analysis_results"
	// DeepAnalysisResultsColumn is the table column denoting the deep_analysis_results relation/edge.
	DeepAnalysisResultsColumn = "run_id"
)

// Columns holds all SQL columns for reportrun fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ReportRun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByDomainReportsCount orders the results by domain_reports count.
func ByDomainReportsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDomainReportsStep(), opts...)
	}
}

// ByDomainReports orders the results by domain_reports terms.
func ByDomainReports(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDomainReportsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDeepAnalysisResultsCount orders the results by deep_analysis_results count.
func ByDeepAnalysisResultsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDeepAnalysisResultsStep(), opts...)
	}
}

// ByDeepAnalysisResults orders the results by deep_analysis_results terms.
func ByDeepAnalysisResults(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDeepAnalysisResultsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newDomainReportsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DomainReportsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DomainReportsTable, DomainReportsColumn),
	)
}
func newDeepAnalysisResultsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DeepAnalysisResultsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DeepAnalysisResultsTable, DeepAnalysisResultsColumn),
	)
}
