// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.0
// source: app/display/api/display/v1/display.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationDisplayGetReport = "/api.display.v1.Display/GetReport"
const OperationDisplayListReports = "/api.display.v1.Display/ListReports"
const OperationDisplayLogin = "/api.display.v1.Display/Login"
const OperationDisplayRegister = "/api.display.v1.Display/Register"

type DisplayHTTPServer interface {
	GetReport(context.Context, *GetReportReq) (*GetReportReply, error)
	ListReports(context.Context, *ListReportsReq) (*ListReportsReply, error)
	Login(context.Context, *LoginReq) (*LoginReply, error)
	Register(context.Context, *RegisterReq) (*RegisterReply, error)
}

func RegisterDisplayHTTPServer(s *http.Server, srv DisplayHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/register", _Display_Register0_HTTP_Handler(srv))
	r.POST("/v1/login", _Display_Login0_HTTP_Handler(srv))
	r.GET("/v1/reports", _Display_ListReports0_HTTP_Handler(srv))
	r.GET("/v1/reports/{id}", _Display_GetReport0_HTTP_Handler(srv))
}

func _Display_Register0_HTTP_Handler(srv DisplayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RegisterReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDisplayRegister)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Register(ctx, req.(*RegisterReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RegisterReply)
		return ctx.Result(200, reply)
	}
}

func _Display_Login0_HTTP_Handler(srv DisplayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDisplayLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Login(ctx, req.(*LoginReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginReply)
		return ctx.Result(200, reply)
	}
}

func _Display_ListReports0_HTTP_Handler(srv DisplayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListReportsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDisplayListReports)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListReports(ctx, req.(*ListReportsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListReportsReply)
		return ctx.Result(200, reply)
	}
}

func _Display_GetReport0_HTTP_Handler(srv DisplayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetReportReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDisplayGetReport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetReport(ctx, req.(*GetReportReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetReportReply)
		return ctx.Result(200, reply)
	}
}

type DisplayHTTPClient interface {
	GetReport(ctx context.Context, req *GetReportReq, opts ...http.CallOption) (rsp *GetReportReply, err error)
	ListReports(ctx context.Context, req *ListReportsReq, opts ...http.CallOption) (rsp *ListReportsReply, err error)
	Login(ctx context.Context, req *LoginReq, opts ...http.CallOption) (rsp *LoginReply, err error)
	Register(ctx context.Context, req *RegisterReq, opts ...http.CallOption) (rsp *RegisterReply, err error)
}

type DisplayHTTPClientImpl struct {
	cc *http.Client
}

func NewDisplayHTTPClient(client *http.Client) DisplayHTTPClient {
	return &DisplayHTTPClientImpl{client}
}

func (c *DisplayHTTPClientImpl) GetReport(ctx context.Context, in *GetReportReq, opts ...http.CallOption) (*GetReportReply, error) {
	var out GetReportReply
	pattern := "/v1/reports/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDisplayGetReport))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DisplayHTTPClientImpl) ListReports(ctx context.Context, in *ListReportsReq, opts ...http.CallOption) (*ListReportsReply, error) {
	var out ListReportsReply
	pattern := "/v1/reports"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDisplayListReports))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DisplayHTTPClientImpl) Login(ctx context.Context, in *LoginReq, opts ...http.CallOption) (*LoginReply, error) {
	var out LoginReply
	pattern := "/v1/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDisplayLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DisplayHTTPClientImpl) Register(ctx context.Context, in *RegisterReq, opts ...http.CallOption) (*RegisterReply, error) {
	var out RegisterReply
	pattern := "/v1/register"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDisplayRegister))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
