// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: app/display/api/display/v1/display.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Display_Register_FullMethodName    = "/api.display.v1.Display/Register"
	Display_Login_FullMethodName       = "/api.display.v1.Display/Login"
	Display_ListReports_FullMethodName = "/api.display.v1.Display/ListReports"
	Display_GetReport_FullMethodName   = "/api.display.v1.Display/GetReport"
)

// DisplayClient is the client API for Display service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DisplayClient interface {
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterReply, error)
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginReply, error)
	ListReports(ctx context.Context, in *ListReportsReq, opts ...grpc.CallOption) (*ListReportsReply, error)
	GetReport(ctx context.Context, in *GetReportReq, opts ...grpc.CallOption) (*GetReportReply, error)
}

type displayClient struct {
	cc grpc.ClientConnInterface
}

func NewDisplayClient(cc grpc.ClientConnInterface) DisplayClient {
	return &displayClient{cc}
}

func (c *displayClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterReply)
	err := c.cc.Invoke(ctx, Display_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *displayClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, Display_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *displayClient) ListReports(ctx context.Context, in *ListReportsReq, opts ...grpc.CallOption) (*ListReportsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReportsReply)
	err := c.cc.Invoke(ctx, Display_ListReports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *displayClient) GetReport(ctx context.Context, in *GetReportReq, opts ...grpc.CallOption) (*GetReportReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReportReply)
	err := c.cc.Invoke(ctx, Display_GetReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DisplayServer is the server API for Display service.
// All implementations must embed UnimplementedDisplayServer
// for forward compatibility.
type DisplayServer interface {
	Register(context.Context, *RegisterReq) (*RegisterReply, error)
	Login(context.Context, *LoginReq) (*LoginReply, error)
	ListReports(context.Context, *ListReportsReq) (*ListReportsReply, error)
	GetReport(context.Context, *GetReportReq) (*GetReportReply, error)
	mustEmbedUnimplementedDisplayServer()
}

// UnimplementedDisplayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDisplayServer struct{}

func (UnimplementedDisplayServer) Register(context.Context, *RegisterReq) (*RegisterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedDisplayServer) Login(context.Context, *LoginReq) (*LoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedDisplayServer) ListReports(context.Context, *ListReportsReq) (*ListReportsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReports not implemented")
}
func (UnimplementedDisplayServer) GetReport(context.Context, *GetReportReq) (*GetReportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReport not implemented")
}
func (UnimplementedDisplayServer) mustEmbedUnimplementedDisplayServer() {}
func (UnimplementedDisplayServer) testEmbeddedByValue()                 {}

// UnsafeDisplayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DisplayServer will
// result in compilation errors.
type UnsafeDisplayServer interface {
	mustEmbedUnimplementedDisplayServer()
}

func RegisterDisplayServer(s grpc.ServiceRegistrar, srv DisplayServer) {
	// If the following call pancis, it indicates UnimplementedDisplayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Display_ServiceDesc, srv)
}

func _Display_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Display_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Display_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Display_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Display_ListReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReportsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayServer).ListReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Display_ListReports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayServer).ListReports(ctx, req.(*ListReportsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Display_GetReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayServer).GetReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Display_GetReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayServer).GetReport(ctx, req.(*GetReportReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Display_ServiceDesc is the grpc.ServiceDesc for Display service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Display_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.display.v1.Display",
	HandlerType: (*DisplayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Display_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Display_Login_Handler,
		},
		{
			MethodName: "ListReports",
			Handler:    _Display_ListReports_Handler,
		},
		{
			MethodName: "GetReport",
			Handler:    _Display_GetReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/display/api/display/v1/display.proto",
}
