// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ActionGuidesColumns holds the columns for the "action_guides" table.
	ActionGuidesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "guide_content", Type: field.TypeString, Nullable: true},
		{Name: "deep_analysis_id", Type: field.TypeInt, Nullable: true},
	}
	// ActionGuidesTable holds the schema information for the "action_guides" table.
	ActionGuidesTable = &schema.Table{
		Name:       "action_guides",
		Columns:    ActionGuidesColumns,
		PrimaryKey: []*schema.Column{ActionGuidesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "action_guides_deep_analysis_results_action_guides",
				Columns:    []*schema.Column{ActionGuidesColumns[2]},
				RefColumns: []*schema.Column{DeepAnalysisResultsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ArticlesColumns holds the columns for the "articles" table.
	ArticlesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString, Nullable: true},
		{Name: "link", Type: field.TypeString, Nullable: true},
		{Name: "source", Type: field.TypeString, Nullable: true},
		{Name: "pub_date", Type: field.TypeString, Nullable: true},
		{Name: "content", Type: field.TypeString, Nullable: true},
		{Name: "domain_report_id", Type: field.TypeInt, Nullable: true},
	}
	// ArticlesTable holds the schema information for the "articles" table.
	ArticlesTable = &schema.Table{
		Name:       "articles",
		Columns:    ArticlesColumns,
		PrimaryKey: []*schema.Column{ArticlesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "articles_domain_reports_articles",
				Columns:    []*schema.Column{ArticlesColumns[6]},
				RefColumns: []*schema.Column{DomainReportsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// DeepAnalysisResultsColumns holds the columns for the "deep_analysis_results" table.
	DeepAnalysisResultsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "macro_trends", Type: field.TypeString, Nullable: true},
		{Name: "opportunities", Type: field.TypeString, Nullable: true},
		{Name: "risks", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "run_id", Type: field.TypeInt, Nullable: true},
	}
	// DeepAnalysisResultsTable holds the schema information for the "deep_analysis_results" table.
	DeepAnalysisResultsTable = &schema.Table{
		Name:       "deep_analysis_results",
		Columns:    DeepAnalysisResultsColumns,
		PrimaryKey: []*schema.Column{DeepAnalysisResultsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "deep_analysis_results_report_runs_deep_analysis_results",
				Columns:    []*schema.Column{DeepAnalysisResultsColumns[5]},
				RefColumns: []*schema.Column{ReportRunsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// DomainReportsColumns holds the columns for the "domain_reports" table.
	DomainReportsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "domain_name", Type: field.TypeString},
		{Name: "overview", Type: field.TypeString, Nullable: true},
		{Name: "trends", Type: field.TypeString, Nullable: true},
		{Name: "score", Type: field.TypeInt, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "run_id", Type: field.TypeInt, Nullable: true},
	}
	// DomainReportsTable holds the schema information for the "domain_reports" table.
	DomainReportsTable = &schema.Table{
		Name:       "domain_reports",
		Columns:    DomainReportsColumns,
		PrimaryKey: []*schema.Column{DomainReportsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "domain_reports_report_runs_domain_reports",
				Columns:    []*schema.Column{DomainReportsColumns[6]},
				RefColumns: []*schema.Column{ReportRunsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// KeyEventsColumns holds the columns for the "key_events" table.
	KeyEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "event_content", Type: field.TypeString, Nullable: true},
		{Name: "domain_report_id", Type: field.TypeInt, Nullable: true},
	}
	// KeyEventsTable holds the schema information for the "key_events" table.
	KeyEventsTable = &schema.Table{
		Name:       "key_events",
		Columns:    KeyEventsColumns,
		PrimaryKey: []*schema.Column{KeyEventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "key_events_domain_reports_key_events",
				Columns:    []*schema.Column{KeyEventsColumns[2]},
				RefColumns: []*schema.Column{DomainReportsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ReportRunsColumns holds the columns for the "report_runs" table.
	ReportRunsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ReportRunsTable holds the schema information for the "report_runs" table.
	ReportRunsTable = &schema.Table{
		Name:       "report_runs",
		Columns:    ReportRunsColumns,
		PrimaryKey: []*schema.Column{ReportRunsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ActionGuidesTable,
		ArticlesTable,
		DeepAnalysisResultsTable,
		DomainReportsTable,
		KeyEventsTable,
		ReportRunsTable,
		UsersTable,
	}
)

func init() {
	ActionGuidesTable.ForeignKeys[0].RefTable = DeepAnalysisResultsTable
	ArticlesTable.ForeignKeys[0].RefTable = DomainReportsTable
	DeepAnalysisResultsTable.ForeignKeys[0].RefTable = ReportRunsTable
	DomainReportsTable.ForeignKeys[0].RefTable = ReportRunsTable
	KeyEventsTable.ForeignKeys[0].RefTable = DomainReportsTable
}
