// Code generated by ent, DO NOT EDIT.

package domainreport

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the domainreport type in the database.
	Label = "domain_report"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRunID holds the string denoting the run_id field in the database.
	FieldRunID = "run_id"
	// FieldDomainName holds the string denoting the domain_name field in the database.
	FieldDomainName = "domain_name"
	// FieldOverview holds the string denoting the overview field in the database.
	FieldOverview = "overview"
	// FieldTrends holds the string denoting the trends field in the database.
	FieldTrends = "trends"
	// FieldScore holds the string denoting the score field in the database.
	FieldScore = "score"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeReportRun holds the string denoting the report_run edge name in mutations.
	EdgeReportRun = "report_run"
	// EdgeArticles holds the string denoting the articles edge name in mutations.
	EdgeArticles = "articles"
	// EdgeKeyEvents holds the string denoting the key_events edge name in mutations.
	EdgeKeyEvents = "key_events"
	// Table holds the table name of the domainreport in the database.
	Table = "domain_reports"
	// ReportRunTable is the table that holds the report_run relation/edge.
	ReportRunTable = "domain_reports"
	// ReportRunInverseTable is the table name for the ReportRun entity.
	// It exists in this package in order to avoid circular dependency with the "reportrun" package.
	ReportRunInverseTable = "report_runs"
	// ReportRunColumn is the table column denoting the report_run relation/edge.
	ReportRunColumn = "run_id"
	// ArticlesTable is the table that holds the articles relation/edge.
	ArticlesTable = "articles"
	// ArticlesInverseTable is the table name for the Article entity.
	// It exists in this package in order to avoid circular dependency with the "article" package.
	ArticlesInverseTable = "articles"
	// ArticlesColumn is the table column denoting the articles relation/edge.
	ArticlesColumn = "domain_report_id"
	// KeyEventsTable is the table that holds the key_events relation/edge.
	KeyEventsTable = "key_events"
	// KeyEventsInverseTable is the table name for the KeyEvent entity.
	// It exists in this package in order to avoid circular dependency with the "keyevent" package.
	KeyEventsInverseTable = "key_events"
	// KeyEventsColumn is the table column denoting the key_events relation/edge.
	KeyEventsColumn = "domain_report_id"
)

// Columns holds all SQL columns for domainreport fields.
var Columns = []string{
	FieldID,
	FieldRunID,
	FieldDomainName,
	FieldOverview,
	FieldTrends,
	FieldScore,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the DomainReport queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRunID orders the results by the run_id field.
func ByRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunID, opts...).ToFunc()
}

// ByDomainName orders the results by the domain_name field.
func ByDomainName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDomainName, opts...).ToFunc()
}

// ByOverview orders the results by the overview field.
func ByOverview(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOverview, opts...).ToFunc()
}

// ByTrends orders the results by the trends field.
func ByTrends(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrends, opts...).ToFunc()
}

// ByScore orders the results by the score field.
func ByScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScore, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByReportRunField orders the results by report_run field.
func ByReportRunField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReportRunStep(), sql.OrderByField(field, opts...))
	}
}

// ByArticlesCount orders the results by articles count.
func ByArticlesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newArticlesStep(), opts...)
	}
}

// ByArticles orders the results by articles terms.
func ByArticles(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newArticlesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByKeyEventsCount orders the results by key_events count.
func ByKeyEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newKeyEventsStep(), opts...)
	}
}

// ByKeyEvents orders the results by key_events terms.
func ByKeyEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newKeyEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newReportRunStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReportRunInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ReportRunTable, ReportRunColumn),
	)
}
func newArticlesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ArticlesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ArticlesTable, ArticlesColumn),
	)
}
func newKeyEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(KeyEventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, KeyEventsTable, KeyEventsColumn),
	)
}
