// Code generated by ent, DO NOT EDIT.

package domainreport

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/iWorld-y/domain_radar/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldLTE(FieldID, id))
}

// RunID applies equality check predicate on the "run_id" field. It's identical to RunIDEQ.
func RunID(v int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldEQ(FieldRunID, v))
}

// DomainName applies equality check predicate on the "domain_name" field. It's identical to DomainNameEQ.
func DomainName(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldEQ(FieldDomainName, v))
}

// Overview applies equality check predicate on the "overview" field. It's identical to OverviewEQ.
func Overview(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldEQ(FieldOverview, v))
}

// Trends applies equality check predicate on the "trends" field. It's identical to TrendsEQ.
func Trends(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldEQ(FieldTrends, v))
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldEQ(FieldScore, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldEQ(FieldCreatedAt, v))
}

// RunIDEQ applies the EQ predicate on the "run_id" field.
func RunIDEQ(v int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldEQ(FieldRunID, v))
}

// RunIDNEQ applies the NEQ predicate on the "run_id" field.
func RunIDNEQ(v int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldNEQ(FieldRunID, v))
}

// RunIDIn applies the In predicate on the "run_id" field.
func RunIDIn(vs ...int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldIn(FieldRunID, vs...))
}

// RunIDNotIn applies the NotIn predicate on the "run_id" field.
func RunIDNotIn(vs ...int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldNotIn(FieldRunID, vs...))
}

// RunIDIsNil applies the IsNil predicate on the "run_id" field.
func RunIDIsNil() predicate.DomainReport {
	return predicate.DomainReport(sql.FieldIsNull(FieldRunID))
}

// RunIDNotNil applies the NotNil predicate on the "run_id" field.
func RunIDNotNil() predicate.DomainReport {
	return predicate.DomainReport(sql.FieldNotNull(FieldRunID))
}

// DomainNameEQ applies the EQ predicate on the "domain_name" field.
func DomainNameEQ(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldEQ(FieldDomainName, v))
}

// DomainNameNEQ applies the NEQ predicate on the "domain_name" field.
func DomainNameNEQ(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldNEQ(FieldDomainName, v))
}

// DomainNameIn applies the In predicate on the "domain_name" field.
func DomainNameIn(vs ...string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldIn(FieldDomainName, vs...))
}

// DomainNameNotIn applies the NotIn predicate on the "domain_name" field.
func DomainNameNotIn(vs ...string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldNotIn(FieldDomainName, vs...))
}

// DomainNameGT applies the GT predicate on the "domain_name" field.
func DomainNameGT(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldGT(FieldDomainName, v))
}

// DomainNameGTE applies the GTE predicate on the "domain_name" field.
func DomainNameGTE(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldGTE(FieldDomainName, v))
}

// DomainNameLT applies the LT predicate on the "domain_name" field.
func DomainNameLT(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldLT(FieldDomainName, v))
}

// DomainNameLTE applies the LTE predicate on the "domain_name" field.
func DomainNameLTE(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldLTE(FieldDomainName, v))
}

// DomainNameContains applies the Contains predicate on the "domain_name" field.
func DomainNameContains(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldContains(FieldDomainName, v))
}

// DomainNameHasPrefix applies the HasPrefix predicate on the "domain_name" field.
func DomainNameHasPrefix(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldHasPrefix(FieldDomainName, v))
}

// DomainNameHasSuffix applies the HasSuffix predicate on the "domain_name" field.
func DomainNameHasSuffix(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldHasSuffix(FieldDomainName, v))
}

// DomainNameEqualFold applies the EqualFold predicate on the "domain_name" field.
func DomainNameEqualFold(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldEqualFold(FieldDomainName, v))
}

// DomainNameContainsFold applies the ContainsFold predicate on the "domain_name" field.
func DomainNameContainsFold(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldContainsFold(FieldDomainName, v))
}

// OverviewEQ applies the EQ predicate on the "overview" field.
func OverviewEQ(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldEQ(FieldOverview, v))
}

// OverviewNEQ applies the NEQ predicate on the "overview" field.
func OverviewNEQ(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldNEQ(FieldOverview, v))
}

// OverviewIn applies the In predicate on the "overview" field.
func OverviewIn(vs ...string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldIn(FieldOverview, vs...))
}

// OverviewNotIn applies the NotIn predicate on the "overview" field.
func OverviewNotIn(vs ...string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldNotIn(FieldOverview, vs...))
}

// OverviewGT applies the GT predicate on the "overview" field.
func OverviewGT(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldGT(FieldOverview, v))
}

// OverviewGTE applies the GTE predicate on the "overview" field.
func OverviewGTE(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldGTE(FieldOverview, v))
}

// OverviewLT applies the LT predicate on the "overview" field.
func OverviewLT(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldLT(FieldOverview, v))
}

// OverviewLTE applies the LTE predicate on the "overview" field.
func OverviewLTE(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldLTE(FieldOverview, v))
}

// OverviewContains applies the Contains predicate on the "overview" field.
func OverviewContains(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldContains(FieldOverview, v))
}

// OverviewHasPrefix applies the HasPrefix predicate on the "overview" field.
func OverviewHasPrefix(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldHasPrefix(FieldOverview, v))
}

// OverviewHasSuffix applies the HasSuffix predicate on the "overview" field.
func OverviewHasSuffix(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldHasSuffix(FieldOverview, v))
}

// OverviewIsNil applies the IsNil predicate on the "overview" field.
func OverviewIsNil() predicate.DomainReport {
	return predicate.DomainReport(sql.FieldIsNull(FieldOverview))
}

// OverviewNotNil applies the NotNil predicate on the "overview" field.
func OverviewNotNil() predicate.DomainReport {
	return predicate.DomainReport(sql.FieldNotNull(FieldOverview))
}

// OverviewEqualFold applies the EqualFold predicate on the "overview" field.
func OverviewEqualFold(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldEqualFold(FieldOverview, v))
}

// OverviewContainsFold applies the ContainsFold predicate on the "overview" field.
func OverviewContainsFold(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldContainsFold(FieldOverview, v))
}

// TrendsEQ applies the EQ predicate on the "trends" field.
func TrendsEQ(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldEQ(FieldTrends, v))
}

// TrendsNEQ applies the NEQ predicate on the "trends" field.
func TrendsNEQ(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldNEQ(FieldTrends, v))
}

// TrendsIn applies the In predicate on the "trends" field.
func TrendsIn(vs ...string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldIn(FieldTrends, vs...))
}

// TrendsNotIn applies the NotIn predicate on the "trends" field.
func TrendsNotIn(vs ...string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldNotIn(FieldTrends, vs...))
}

// TrendsGT applies the GT predicate on the "trends" field.
func TrendsGT(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldGT(FieldTrends, v))
}

// TrendsGTE applies the GTE predicate on the "trends" field.
func TrendsGTE(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldGTE(FieldTrends, v))
}

// TrendsLT applies the LT predicate on the "trends" field.
func TrendsLT(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldLT(FieldTrends, v))
}

// TrendsLTE applies the LTE predicate on the "trends" field.
func TrendsLTE(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldLTE(FieldTrends, v))
}

// TrendsContains applies the Contains predicate on the "trends" field.
func TrendsContains(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldContains(FieldTrends, v))
}

// TrendsHasPrefix applies the HasPrefix predicate on the "trends" field.
func TrendsHasPrefix(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldHasPrefix(FieldTrends, v))
}

// TrendsHasSuffix applies the HasSuffix predicate on the "trends" field.
func TrendsHasSuffix(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldHasSuffix(FieldTrends, v))
}

// TrendsIsNil applies the IsNil predicate on the "trends" field.
func TrendsIsNil() predicate.DomainReport {
	return predicate.DomainReport(sql.FieldIsNull(FieldTrends))
}

// TrendsNotNil applies the NotNil predicate on the "trends" field.
func TrendsNotNil() predicate.DomainReport {
	return predicate.DomainReport(sql.FieldNotNull(FieldTrends))
}

// TrendsEqualFold applies the EqualFold predicate on the "trends" field.
func TrendsEqualFold(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldEqualFold(FieldTrends, v))
}

// TrendsContainsFold applies the ContainsFold predicate on the "trends" field.
func TrendsContainsFold(v string) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldContainsFold(FieldTrends, v))
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldEQ(FieldScore, v))
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldNEQ(FieldScore, v))
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldIn(FieldScore, vs...))
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldNotIn(FieldScore, vs...))
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldGT(FieldScore, v))
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldGTE(FieldScore, v))
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldLT(FieldScore, v))
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v int) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldLTE(FieldScore, v))
}

// ScoreIsNil applies the IsNil predicate on the "score" field.
func ScoreIsNil() predicate.DomainReport {
	return predicate.DomainReport(sql.FieldIsNull(FieldScore))
}

// ScoreNotNil applies the NotNil predicate on the "score" field.
func ScoreNotNil() predicate.DomainReport {
	return predicate.DomainReport(sql.FieldNotNull(FieldScore))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DomainReport {
	return predicate.DomainReport(sql.FieldLTE(FieldCreatedAt, v))
}

// HasReportRun applies the HasEdge predicate on the "report_run" edge.
func HasReportRun() predicate.DomainReport {
	return predicate.DomainReport(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ReportRunTable, ReportRunColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReportRunWith applies the HasEdge predicate on the "report_run" edge with a given conditions (other predicates).
func HasReportRunWith(preds ...predicate.ReportRun) predicate.DomainReport {
	return predicate.DomainReport(func(s *sql.Selector) {
		step := newReportRunStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasArticles applies the HasEdge predicate on the "articles" edge.
func HasArticles() predicate.DomainReport {
	return predicate.DomainReport(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ArticlesTable, ArticlesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasArticlesWith applies the HasEdge predicate on the "articles" edge with a given conditions (other predicates).
func HasArticlesWith(preds ...predicate.Article) predicate.DomainReport {
	return predicate.DomainReport(func(s *sql.Selector) {
		step := newArticlesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasKeyEvents applies the HasEdge predicate on the "key_events" edge.
func HasKeyEvents() predicate.DomainReport {
	return predicate.DomainReport(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, KeyEventsTable, KeyEventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasKeyEventsWith applies the HasEdge predicate on the "key_events" edge with a given conditions (other predicates).
func HasKeyEventsWith(preds ...predicate.KeyEvent) predicate.DomainReport {
	return predicate.DomainReport(func(s *sql.Selector) {
		step := newKeyEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DomainReport) predicate.DomainReport {
	return predicate.DomainReport(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DomainReport) predicate.DomainReport {
	return predicate.DomainReport(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DomainReport) predicate.DomainReport {
	return predicate.DomainReport(sql.NotPredicates(p))
}
