// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iWorld-y/domain_radar/ent/actionguide"
	"github.com/iWorld-y/domain_radar/ent/deepanalysisresult"
	"github.com/iWorld-y/domain_radar/ent/predicate"
)

// ActionGuideUpdate is the builder for updating ActionGuide entities.
type ActionGuideUpdate struct {
	config
	hooks     []Hook
	mutation  *ActionGuideMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ActionGuideUpdate builder.
func (_u *ActionGuideUpdate) Where(ps ...predicate.ActionGuide) *ActionGuideUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeepAnalysisID sets the "deep_analysis_id" field.
func (_u *ActionGuideUpdate) SetDeepAnalysisID(v int) *ActionGuideUpdate {
	_u.mutation.SetDeepAnalysisID(v)
	return _u
}

// SetNillableDeepAnalysisID sets the "deep_analysis_id" field if the given value is not nil.
func (_u *ActionGuideUpdate) SetNillableDeepAnalysisID(v *int) *ActionGuideUpdate {
	if v != nil {
		_u.SetDeepAnalysisID(*v)
	}
	return _u
}

// ClearDeepAnalysisID clears the value of the "deep_analysis_id" field.
func (_u *ActionGuideUpdate) ClearDeepAnalysisID() *ActionGuideUpdate {
	_u.mutation.ClearDeepAnalysisID()
	return _u
}

// SetGuideContent sets the "guide_content" field.
func (_u *ActionGuideUpdate) SetGuideContent(v string) *ActionGuideUpdate {
	_u.mutation.SetGuideContent(v)
	return _u
}

// SetNillableGuideContent sets the "guide_content" field if the given value is not nil.
func (_u *ActionGuideUpdate) SetNillableGuideContent(v *string) *ActionGuideUpdate {
	if v != nil {
		_u.SetGuideContent(*v)
	}
	return _u
}

// ClearGuideContent clears the value of the "guide_content" field.
func (_u *ActionGuideUpdate) ClearGuideContent() *ActionGuideUpdate {
	_u.mutation.ClearGuideContent()
	return _u
}

// SetDeepAnalysisResultID sets the "deep_analysis_result" edge to the DeepAnalysisResult entity by ID.
func (_u *ActionGuideUpdate) SetDeepAnalysisResultID(id int) *ActionGuideUpdate {
	_u.mutation.SetDeepAnalysisResultID(id)
	return _u
}

// SetNillableDeepAnalysisResultID sets the "deep_analysis_result" edge to the DeepAnalysisResult entity by ID if the given value is not nil.
func (_u *ActionGuideUpdate) SetNillableDeepAnalysisResultID(id *int) *ActionGuideUpdate {
	if id != nil {
		_u = _u.SetDeepAnalysisResultID(*id)
	}
	return _u
}

// SetDeepAnalysisResult sets the "deep_analysis_result" edge to the DeepAnalysisResult entity.
func (_u *ActionGuideUpdate) SetDeepAnalysisResult(v *DeepAnalysisResult) *ActionGuideUpdate {
	return _u.SetDeepAnalysisResultID(v.ID)
}

// Mutation returns the ActionGuideMutation object of the builder.
func (_u *ActionGuideUpdate) Mutation() *ActionGuideMutation {
	return _u.mutation
}

// ClearDeepAnalysisResult clears the "deep_analysis_result" edge to the DeepAnalysisResult entity.
func (_u *ActionGuideUpdate) ClearDeepAnalysisResult() *ActionGuideUpdate {
	_u.mutation.ClearDeepAnalysisResult()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ActionGuideUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActionGuideUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ActionGuideUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActionGuideUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ActionGuideUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ActionGuideUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ActionGuideUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(actionguide.Table, actionguide.Columns, sqlgraph.NewFieldSpec(actionguide.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GuideContent(); ok {
		_spec.SetField(actionguide.FieldGuideContent, field.TypeString, value)
	}
	if _u.mutation.GuideContentCleared() {
		_spec.ClearField(actionguide.FieldGuideContent, field.TypeString)
	}
	if _u.mutation.DeepAnalysisResultCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   actionguide.DeepAnalysisResultTable,
			Columns: []string{actionguide.DeepAnalysisResultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deepanalysisresult.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeepAnalysisResultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   actionguide.DeepAnalysisResultTable,
			Columns: []string{actionguide.DeepAnalysisResultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deepanalysisresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{actionguide.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ActionGuideUpdateOne is the builder for updating a single ActionGuide entity.
type ActionGuideUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ActionGuideMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDeepAnalysisID sets the "deep_analysis_id" field.
func (_u *ActionGuideUpdateOne) SetDeepAnalysisID(v int) *ActionGuideUpdateOne {
	_u.mutation.SetDeepAnalysisID(v)
	return _u
}

// SetNillableDeepAnalysisID sets the "deep_analysis_id" field if the given value is not nil.
func (_u *ActionGuideUpdateOne) SetNillableDeepAnalysisID(v *int) *ActionGuideUpdateOne {
	if v != nil {
		_u.SetDeepAnalysisID(*v)
	}
	return _u
}

// ClearDeepAnalysisID clears the value of the "deep_analysis_id" field.
func (_u *ActionGuideUpdateOne) ClearDeepAnalysisID() *ActionGuideUpdateOne {
	_u.mutation.ClearDeepAnalysisID()
	return _u
}

// SetGuideContent sets the "guide_content" field.
func (_u *ActionGuideUpdateOne) SetGuideContent(v string) *ActionGuideUpdateOne {
	_u.mutation.SetGuideContent(v)
	return _u
}

// SetNillableGuideContent sets the "guide_content" field if the given value is not nil.
func (_u *ActionGuideUpdateOne) SetNillableGuideContent(v *string) *ActionGuideUpdateOne {
	if v != nil {
		_u.SetGuideContent(*v)
	}
	return _u
}

// ClearGuideContent clears the value of the "guide_content" field.
func (_u *ActionGuideUpdateOne) ClearGuideContent() *ActionGuideUpdateOne {
	_u.mutation.ClearGuideContent()
	return _u
}

// SetDeepAnalysisResultID sets the "deep_analysis_result" edge to the DeepAnalysisResult entity by ID.
func (_u *ActionGuideUpdateOne) SetDeepAnalysisResultID(id int) *ActionGuideUpdateOne {
	_u.mutation.SetDeepAnalysisResultID(id)
	return _u
}

// SetNillableDeepAnalysisResultID sets the "deep_analysis_result" edge to the DeepAnalysisResult entity by ID if the given value is not nil.
func (_u *ActionGuideUpdateOne) SetNillableDeepAnalysisResultID(id *int) *ActionGuideUpdateOne {
	if id != nil {
		_u = _u.SetDeepAnalysisResultID(*id)
	}
	return _u
}

// SetDeepAnalysisResult sets the "deep_analysis_result" edge to the DeepAnalysisResult entity.
func (_u *ActionGuideUpdateOne) SetDeepAnalysisResult(v *DeepAnalysisResult) *ActionGuideUpdateOne {
	return _u.SetDeepAnalysisResultID(v.ID)
}

// Mutation returns the ActionGuideMutation object of the builder.
func (_u *ActionGuideUpdateOne) Mutation() *ActionGuideMutation {
	return _u.mutation
}

// ClearDeepAnalysisResult clears the "deep_analysis_result" edge to the DeepAnalysisResult entity.
func (_u *ActionGuideUpdateOne) ClearDeepAnalysisResult() *ActionGuideUpdateOne {
	_u.mutation.ClearDeepAnalysisResult()
	return _u
}

// Where appends a list predicates to the ActionGuideUpdate builder.
func (_u *ActionGuideUpdateOne) Where(ps ...predicate.ActionGuide) *ActionGuideUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ActionGuideUpdateOne) Select(field string, fields ...string) *ActionGuideUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ActionGuide entity.
func (_u *ActionGuideUpdateOne) Save(ctx context.Context) (*ActionGuide, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActionGuideUpdateOne) SaveX(ctx context.Context) *ActionGuide {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ActionGuideUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActionGuideUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ActionGuideUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ActionGuideUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ActionGuideUpdateOne) sqlSave(ctx context.Context) (_node *ActionGuide, err error) {
	_spec := sqlgraph.NewUpdateSpec(actionguide.Table, actionguide.Columns, sqlgraph.NewFieldSpec(actionguide.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ActionGuide.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, actionguide.FieldID)
		for _, f := range fields {
			if !actionguide.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != actionguide.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GuideContent(); ok {
		_spec.SetField(actionguide.FieldGuideContent, field.TypeString, value)
	}
	if _u.mutation.GuideContentCleared() {
		_spec.ClearField(actionguide.FieldGuideContent, field.TypeString)
	}
	if _u.mutation.DeepAnalysisResultCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   actionguide.DeepAnalysisResultTable,
			Columns: []string{actionguide.DeepAnalysisResultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deepanalysisresult.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeepAnalysisResultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   actionguide.DeepAnalysisResultTable,
			Columns: []string{actionguide.DeepAnalysisResultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deepanalysisresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ActionGuide{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{actionguide.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
