// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iWorld-y/domain_radar/ent/actionguide"
	"github.com/iWorld-y/domain_radar/ent/deepanalysisresult"
	"github.com/iWorld-y/domain_radar/ent/predicate"
)

// ActionGuideQuery is the builder for querying ActionGuide entities.
type ActionGuideQuery struct {
	config
	ctx                    *QueryContext
	order                  []actionguide.OrderOption
	inters                 []Interceptor
	predicates             []predicate.ActionGuide
	withDeepAnalysisResult *DeepAnalysisResultQuery
	modifiers              []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ActionGuideQuery builder.
func (_q *ActionGuideQuery) Where(ps ...predicate.ActionGuide) *ActionGuideQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ActionGuideQuery) Limit(limit int) *ActionGuideQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ActionGuideQuery) Offset(offset int) *ActionGuideQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ActionGuideQuery) Unique(unique bool) *ActionGuideQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ActionGuideQuery) Order(o ...actionguide.OrderOption) *ActionGuideQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryDeepAnalysisResult chains the current query on the "deep_analysis_result" edge.
func (_q *ActionGuideQuery) QueryDeepAnalysisResult() *DeepAnalysisResultQuery {
	query := (&DeepAnalysisResultClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(actionguide.Table, actionguide.FieldID, selector),
			sqlgraph.To(deepanalysisresult.Table, deepanalysisresult.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, actionguide.DeepAnalysisResultTable, actionguide.DeepAnalysisResultColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ActionGuide entity from the query.
// Returns a *NotFoundError when no ActionGuide was found.
func (_q *ActionGuideQuery) First(ctx context.Context) (*ActionGuide, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{actionguide.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ActionGuideQuery) FirstX(ctx context.Context) *ActionGuide {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ActionGuide ID from the query.
// Returns a *NotFoundError when no ActionGuide ID was found.
func (_q *ActionGuideQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{actionguide.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ActionGuideQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ActionGuide entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ActionGuide entity is found.
// Returns a *NotFoundError when no ActionGuide entities are found.
func (_q *ActionGuideQuery) Only(ctx context.Context) (*ActionGuide, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{actionguide.Label}
	default:
		return nil, &NotSingularError{actionguide.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ActionGuideQuery) OnlyX(ctx context.Context) *ActionGuide {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ActionGuide ID in the query.
// Returns a *NotSingularError when more than one ActionGuide ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ActionGuideQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{actionguide.Label}
	default:
		err = &NotSingularError{actionguide.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ActionGuideQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ActionGuides.
func (_q *ActionGuideQuery) All(ctx context.Context) ([]*ActionGuide, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ActionGuide, *ActionGuideQuery]()
	return withInterceptors[[]*ActionGuide](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ActionGuideQuery) AllX(ctx context.Context) []*ActionGuide {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ActionGuide IDs.
func (_q *ActionGuideQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(actionguide.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ActionGuideQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ActionGuideQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ActionGuideQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ActionGuideQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ActionGuideQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ActionGuideQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ActionGuideQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ActionGuideQuery) Clone() *ActionGuideQuery {
	if _q == nil {
		return nil
	}
	return &ActionGuideQuery{
		config:                 _q.config,
		ctx:                    _q.ctx.Clone(),
		order:                  append([]actionguide.OrderOption{}, _q.order...),
		inters:                 append([]Interceptor{}, _q.inters...),
		predicates:             append([]predicate.ActionGuide{}, _q.predicates...),
		withDeepAnalysisResult: _q.withDeepAnalysisResult.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithDeepAnalysisResult tells the query-builder to eager-load the nodes that are connected to
// the "deep_analysis_result" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ActionGuideQuery) WithDeepAnalysisResult(opts ...func(*DeepAnalysisResultQuery)) *ActionGuideQuery {
	query := (&DeepAnalysisResultClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDeepAnalysisResult = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DeepAnalysisID int `json:"deep_analysis_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ActionGuide.Query().
//		GroupBy(actionguide.FieldDeepAnalysisID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ActionGuideQuery) GroupBy(field string, fields ...string) *ActionGuideGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ActionGuideGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = actionguide.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DeepAnalysisID int `json:"deep_analysis_id,omitempty"`
//	}
//
//	client.ActionGuide.Query().
//		Select(actionguide.FieldDeepAnalysisID).
//		Scan(ctx, &v)
func (_q *ActionGuideQuery) Select(fields ...string) *ActionGuideSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ActionGuideSelect{ActionGuideQuery: _q}
	sbuild.label = actionguide.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ActionGuideSelect configured with the given aggregations.
func (_q *ActionGuideQuery) Aggregate(fns ...AggregateFunc) *ActionGuideSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ActionGuideQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !actionguide.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ActionGuideQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ActionGuide, error) {
	var (
		nodes       = []*ActionGuide{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withDeepAnalysisResult != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ActionGuide).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ActionGuide{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withDeepAnalysisResult; query != nil {
		if err := _q.loadDeepAnalysisResult(ctx, query, nodes, nil,
			func(n *ActionGuide, e *DeepAnalysisResult) { n.Edges.DeepAnalysisResult = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ActionGuideQuery) loadDeepAnalysisResult(ctx context.Context, query *DeepAnalysisResultQuery, nodes []*ActionGuide, init func(*ActionGuide), assign func(*ActionGuide, *DeepAnalysisResult)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ActionGuide)
	for i := range nodes {
		fk := nodes[i].DeepAnalysisID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(deepanalysisresult.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "deep_analysis_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ActionGuideQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ActionGuideQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(actionguide.Table, actionguide.Columns, sqlgraph.NewFieldSpec(actionguide.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, actionguide.FieldID)
		for i := range fields {
			if fields[i] != actionguide.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withDeepAnalysisResult != nil {
			_spec.Node.AddColumnOnce(actionguide.FieldDeepAnalysisID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ActionGuideQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(actionguide.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = actionguide.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *ActionGuideQuery) Modify(modifiers ...func(s *sql.Selector)) *ActionGuideSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// ActionGuideGroupBy is the group-by builder for ActionGuide entities.
type ActionGuideGroupBy struct {
	selector
	build *ActionGuideQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ActionGuideGroupBy) Aggregate(fns ...AggregateFunc) *ActionGuideGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ActionGuideGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ActionGuideQuery, *ActionGuideGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ActionGuideGroupBy) sqlScan(ctx context.Context, root *ActionGuideQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ActionGuideSelect is the builder for selecting fields of ActionGuide entities.
type ActionGuideSelect struct {
	*ActionGuideQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ActionGuideSelect) Aggregate(fns ...AggregateFunc) *ActionGuideSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ActionGuideSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ActionGuideQuery, *ActionGuideSelect](ctx, _s.ActionGuideQuery, _s, _s.inters, v)
}

func (_s *ActionGuideSelect) sqlScan(ctx context.Context, root *ActionGuideQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *ActionGuideSelect) Modify(modifiers ...func(s *sql.Selector)) *ActionGuideSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
