// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/iWorld-y/domain_radar/ent/actionguide"
	"github.com/iWorld-y/domain_radar/ent/deepanalysisresult"
)

// ActionGuide is the model entity for the ActionGuide schema.
type ActionGuide struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// DeepAnalysisID holds the value of the "deep_analysis_id" field.
	DeepAnalysisID int `json:"deep_analysis_id,omitempty"`
	// GuideContent holds the value of the "guide_content" field.
	GuideContent string `json:"guide_content,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ActionGuideQuery when eager-loading is set.
	Edges        ActionGuideEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ActionGuideEdges holds the relations/edges for other nodes in the graph.
type ActionGuideEdges struct {
	// DeepAnalysisResult holds the value of the deep_analysis_result edge.
	DeepAnalysisResult *DeepAnalysisResult `json:"deep_analysis_result,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DeepAnalysisResultOrErr returns the DeepAnalysisResult value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ActionGuideEdges) DeepAnalysisResultOrErr() (*DeepAnalysisResult, error) {
	if e.DeepAnalysisResult != nil {
		return e.DeepAnalysisResult, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: deepanalysisresult.Label}
	}
	return nil, &NotLoadedError{edge: "deep_analysis_result"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ActionGuide) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case actionguide.FieldID, actionguide.FieldDeepAnalysisID:
			values[i] = new(sql.NullInt64)
		case actionguide.FieldGuideContent:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ActionGuide fields.
func (_m *ActionGuide) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case actionguide.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case actionguide.FieldDeepAnalysisID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deep_analysis_id", values[i])
			} else if value.Valid {
				_m.DeepAnalysisID = int(value.Int64)
			}
		case actionguide.FieldGuideContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field guide_content", values[i])
			} else if value.Valid {
				_m.GuideContent = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ActionGuide.
// This includes values selected through modifiers, order, etc.
func (_m *ActionGuide) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDeepAnalysisResult queries the "deep_analysis_result" edge of the ActionGuide entity.
func (_m *ActionGuide) QueryDeepAnalysisResult() *DeepAnalysisResultQuery {
	return NewActionGuideClient(_m.config).QueryDeepAnalysisResult(_m)
}

// Update returns a builder for updating this ActionGuide.
// Note that you need to call ActionGuide.Unwrap() before calling this method if this ActionGuide
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ActionGuide) Update() *ActionGuideUpdateOne {
	return NewActionGuideClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ActionGuide entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ActionGuide) Unwrap() *ActionGuide {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ActionGuide is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ActionGuide) String() string {
	var builder strings.Builder
	builder.WriteString("ActionGuide(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("deep_analysis_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeepAnalysisID))
	builder.WriteString(", ")
	builder.WriteString("guide_content=")
	builder.WriteString(_m.GuideContent)
	builder.WriteByte(')')
	return builder.String()
}

// ActionGuides is a parsable slice of ActionGuide.
type ActionGuides []*ActionGuide
