// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/iWorld-y/domain_radar/ent/article"
	"github.com/iWorld-y/domain_radar/ent/domainreport"
)

// Article is the model entity for the Article schema.
type Article struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// DomainReportID holds the value of the "domain_report_id" field.
	DomainReportID int `json:"domain_report_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Link holds the value of the "link" field.
	Link string `json:"link,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// PubDate holds the value of the "pub_date" field.
	PubDate string `json:"pub_date,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ArticleQuery when eager-loading is set.
	Edges        ArticleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ArticleEdges holds the relations/edges for other nodes in the graph.
type ArticleEdges struct {
	// DomainReport holds the value of the domain_report edge.
	DomainReport *DomainReport `json:"domain_report,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DomainReportOrErr returns the DomainReport value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ArticleEdges) DomainReportOrErr() (*DomainReport, error) {
	if e.DomainReport != nil {
		return e.DomainReport, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: domainreport.Label}
	}
	return nil, &NotLoadedError{edge: "domain_report"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Article) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case article.FieldID, article.FieldDomainReportID:
			values[i] = new(sql.NullInt64)
		case article.FieldTitle, article.FieldLink, article.FieldSource, article.FieldPubDate, article.FieldContent:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Article fields.
func (_m *Article) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case article.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case article.FieldDomainReportID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field domain_report_id", values[i])
			} else if value.Valid {
				_m.DomainReportID = int(value.Int64)
			}
		case article.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case article.FieldLink:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field link", values[i])
			} else if value.Valid {
				_m.Link = value.String
			}
		case article.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case article.FieldPubDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pub_date", values[i])
			} else if value.Valid {
				_m.PubDate = value.String
			}
		case article.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Article.
// This includes values selected through modifiers, order, etc.
func (_m *Article) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDomainReport queries the "domain_report" edge of the Article entity.
func (_m *Article) QueryDomainReport() *DomainReportQuery {
	return NewArticleClient(_m.config).QueryDomainReport(_m)
}

// Update returns a builder for updating this Article.
// Note that you need to call Article.Unwrap() before calling this method if this Article
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Article) Update() *ArticleUpdateOne {
	return NewArticleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Article entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Article) Unwrap() *Article {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Article is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Article) String() string {
	var builder strings.Builder
	builder.WriteString("Article(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("domain_report_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DomainReportID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("link=")
	builder.WriteString(_m.Link)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("pub_date=")
	builder.WriteString(_m.PubDate)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteByte(')')
	return builder.String()
}

// Articles is a parsable slice of Article.
type Articles []*Article
