// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iWorld-y/domain_radar/ent/article"
	"github.com/iWorld-y/domain_radar/ent/domainreport"
	"github.com/iWorld-y/domain_radar/ent/predicate"
)

// ArticleUpdate is the builder for updating Article entities.
type ArticleUpdate struct {
	config
	hooks     []Hook
	mutation  *ArticleMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ArticleUpdate builder.
func (_u *ArticleUpdate) Where(ps ...predicate.Article) *ArticleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDomainReportID sets the "domain_report_id" field.
func (_u *ArticleUpdate) SetDomainReportID(v int) *ArticleUpdate {
	_u.mutation.SetDomainReportID(v)
	return _u
}

// SetNillableDomainReportID sets the "domain_report_id" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableDomainReportID(v *int) *ArticleUpdate {
	if v != nil {
		_u.SetDomainReportID(*v)
	}
	return _u
}

// ClearDomainReportID clears the value of the "domain_report_id" field.
func (_u *ArticleUpdate) ClearDomainReportID() *ArticleUpdate {
	_u.mutation.ClearDomainReportID()
	return _u
}

// SetTitle sets the "title" field.
func (_u *ArticleUpdate) SetTitle(v string) *ArticleUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableTitle(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *ArticleUpdate) ClearTitle() *ArticleUpdate {
	_u.mutation.ClearTitle()
	return _u
}

// SetLink sets the "link" field.
func (_u *ArticleUpdate) SetLink(v string) *ArticleUpdate {
	_u.mutation.SetLink(v)
	return _u
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableLink(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetLink(*v)
	}
	return _u
}

// ClearLink clears the value of the "link" field.
func (_u *ArticleUpdate) ClearLink() *ArticleUpdate {
	_u.mutation.ClearLink()
	return _u
}

// SetSource sets the "source" field.
func (_u *ArticleUpdate) SetSource(v string) *ArticleUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableSource(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// ClearSource clears the value of the "source" field.
func (_u *ArticleUpdate) ClearSource() *ArticleUpdate {
	_u.mutation.ClearSource()
	return _u
}

// SetPubDate sets the "pub_date" field.
func (_u *ArticleUpdate) SetPubDate(v string) *ArticleUpdate {
	_u.mutation.SetPubDate(v)
	return _u
}

// SetNillablePubDate sets the "pub_date" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillablePubDate(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetPubDate(*v)
	}
	return _u
}

// ClearPubDate clears the value of the "pub_date" field.
func (_u *ArticleUpdate) ClearPubDate() *ArticleUpdate {
	_u.mutation.ClearPubDate()
	return _u
}

// SetContent sets the "content" field.
func (_u *ArticleUpdate) SetContent(v string) *ArticleUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableContent(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *ArticleUpdate) ClearContent() *ArticleUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetDomainReport sets the "domain_report" edge to the DomainReport entity.
func (_u *ArticleUpdate) SetDomainReport(v *DomainReport) *ArticleUpdate {
	return _u.SetDomainReportID(v.ID)
}

// Mutation returns the ArticleMutation object of the builder.
func (_u *ArticleUpdate) Mutation() *ArticleMutation {
	return _u.mutation
}

// ClearDomainReport clears the "domain_report" edge to the DomainReport entity.
func (_u *ArticleUpdate) ClearDomainReport() *ArticleUpdate {
	_u.mutation.ClearDomainReport()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ArticleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArticleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ArticleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArticleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ArticleUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ArticleUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ArticleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(article.Table, article.Columns, sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(article.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(article.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Link(); ok {
		_spec.SetField(article.FieldLink, field.TypeString, value)
	}
	if _u.mutation.LinkCleared() {
		_spec.ClearField(article.FieldLink, field.TypeString)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(article.FieldSource, field.TypeString, value)
	}
	if _u.mutation.SourceCleared() {
		_spec.ClearField(article.FieldSource, field.TypeString)
	}
	if value, ok := _u.mutation.PubDate(); ok {
		_spec.SetField(article.FieldPubDate, field.TypeString, value)
	}
	if _u.mutation.PubDateCleared() {
		_spec.ClearField(article.FieldPubDate, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(article.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(article.FieldContent, field.TypeString)
	}
	if _u.mutation.DomainReportCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   article.DomainReportTable,
			Columns: []string{article.DomainReportColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domainreport.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DomainReportIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   article.DomainReportTable,
			Columns: []string{article.DomainReportColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domainreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{article.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ArticleUpdateOne is the builder for updating a single Article entity.
type ArticleUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ArticleMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDomainReportID sets the "domain_report_id" field.
func (_u *ArticleUpdateOne) SetDomainReportID(v int) *ArticleUpdateOne {
	_u.mutation.SetDomainReportID(v)
	return _u
}

// SetNillableDomainReportID sets the "domain_report_id" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableDomainReportID(v *int) *ArticleUpdateOne {
	if v != nil {
		_u.SetDomainReportID(*v)
	}
	return _u
}

// ClearDomainReportID clears the value of the "domain_report_id" field.
func (_u *ArticleUpdateOne) ClearDomainReportID() *ArticleUpdateOne {
	_u.mutation.ClearDomainReportID()
	return _u
}

// SetTitle sets the "title" field.
func (_u *ArticleUpdateOne) SetTitle(v string) *ArticleUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableTitle(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *ArticleUpdateOne) ClearTitle() *ArticleUpdateOne {
	_u.mutation.ClearTitle()
	return _u
}

// SetLink sets the "link" field.
func (_u *ArticleUpdateOne) SetLink(v string) *ArticleUpdateOne {
	_u.mutation.SetLink(v)
	return _u
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableLink(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetLink(*v)
	}
	return _u
}

// ClearLink clears the value of the "link" field.
func (_u *ArticleUpdateOne) ClearLink() *ArticleUpdateOne {
	_u.mutation.ClearLink()
	return _u
}

// SetSource sets the "source" field.
func (_u *ArticleUpdateOne) SetSource(v string) *ArticleUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableSource(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// ClearSource clears the value of the "source" field.
func (_u *ArticleUpdateOne) ClearSource() *ArticleUpdateOne {
	_u.mutation.ClearSource()
	return _u
}

// SetPubDate sets the "pub_date" field.
func (_u *ArticleUpdateOne) SetPubDate(v string) *ArticleUpdateOne {
	_u.mutation.SetPubDate(v)
	return _u
}

// SetNillablePubDate sets the "pub_date" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillablePubDate(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetPubDate(*v)
	}
	return _u
}

// ClearPubDate clears the value of the "pub_date" field.
func (_u *ArticleUpdateOne) ClearPubDate() *ArticleUpdateOne {
	_u.mutation.ClearPubDate()
	return _u
}

// SetContent sets the "content" field.
func (_u *ArticleUpdateOne) SetContent(v string) *ArticleUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableContent(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *ArticleUpdateOne) ClearContent() *ArticleUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetDomainReport sets the "domain_report" edge to the DomainReport entity.
func (_u *ArticleUpdateOne) SetDomainReport(v *DomainReport) *ArticleUpdateOne {
	return _u.SetDomainReportID(v.ID)
}

// Mutation returns the ArticleMutation object of the builder.
func (_u *ArticleUpdateOne) Mutation() *ArticleMutation {
	return _u.mutation
}

// ClearDomainReport clears the "domain_report" edge to the DomainReport entity.
func (_u *ArticleUpdateOne) ClearDomainReport() *ArticleUpdateOne {
	_u.mutation.ClearDomainReport()
	return _u
}

// Where appends a list predicates to the ArticleUpdate builder.
func (_u *ArticleUpdateOne) Where(ps ...predicate.Article) *ArticleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ArticleUpdateOne) Select(field string, fields ...string) *ArticleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Article entity.
func (_u *ArticleUpdateOne) Save(ctx context.Context) (*Article, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArticleUpdateOne) SaveX(ctx context.Context) *Article {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ArticleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArticleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ArticleUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ArticleUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ArticleUpdateOne) sqlSave(ctx context.Context) (_node *Article, err error) {
	_spec := sqlgraph.NewUpdateSpec(article.Table, article.Columns, sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Article.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, article.FieldID)
		for _, f := range fields {
			if !article.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != article.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(article.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(article.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Link(); ok {
		_spec.SetField(article.FieldLink, field.TypeString, value)
	}
	if _u.mutation.LinkCleared() {
		_spec.ClearField(article.FieldLink, field.TypeString)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(article.FieldSource, field.TypeString, value)
	}
	if _u.mutation.SourceCleared() {
		_spec.ClearField(article.FieldSource, field.TypeString)
	}
	if value, ok := _u.mutation.PubDate(); ok {
		_spec.SetField(article.FieldPubDate, field.TypeString, value)
	}
	if _u.mutation.PubDateCleared() {
		_spec.ClearField(article.FieldPubDate, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(article.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(article.FieldContent, field.TypeString)
	}
	if _u.mutation.DomainReportCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   article.DomainReportTable,
			Columns: []string{article.DomainReportColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domainreport.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DomainReportIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   article.DomainReportTable,
			Columns: []string{article.DomainReportColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domainreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Article{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{article.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
