// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iWorld-y/domain_radar/ent/actionguide"
	"github.com/iWorld-y/domain_radar/ent/deepanalysisresult"
	"github.com/iWorld-y/domain_radar/ent/predicate"
	"github.com/iWorld-y/domain_radar/ent/reportrun"
)

// DeepAnalysisResultUpdate is the builder for updating DeepAnalysisResult entities.
type DeepAnalysisResultUpdate struct {
	config
	hooks     []Hook
	mutation  *DeepAnalysisResultMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DeepAnalysisResultUpdate builder.
func (_u *DeepAnalysisResultUpdate) Where(ps ...predicate.DeepAnalysisResult) *DeepAnalysisResultUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRunID sets the "run_id" field.
func (_u *DeepAnalysisResultUpdate) SetRunID(v int) *DeepAnalysisResultUpdate {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *DeepAnalysisResultUpdate) SetNillableRunID(v *int) *DeepAnalysisResultUpdate {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// ClearRunID clears the value of the "run_id" field.
func (_u *DeepAnalysisResultUpdate) ClearRunID() *DeepAnalysisResultUpdate {
	_u.mutation.ClearRunID()
	return _u
}

// SetMacroTrends sets the "macro_trends" field.
func (_u *DeepAnalysisResultUpdate) SetMacroTrends(v string) *DeepAnalysisResultUpdate {
	_u.mutation.SetMacroTrends(v)
	return _u
}

// SetNillableMacroTrends sets the "macro_trends" field if the given value is not nil.
func (_u *DeepAnalysisResultUpdate) SetNillableMacroTrends(v *string) *DeepAnalysisResultUpdate {
	if v != nil {
		_u.SetMacroTrends(*v)
	}
	return _u
}

// ClearMacroTrends clears the value of the "macro_trends" field.
func (_u *DeepAnalysisResultUpdate) ClearMacroTrends() *DeepAnalysisResultUpdate {
	_u.mutation.ClearMacroTrends()
	return _u
}

// SetOpportunities sets the "opportunities" field.
func (_u *DeepAnalysisResultUpdate) SetOpportunities(v string) *DeepAnalysisResultUpdate {
	_u.mutation.SetOpportunities(v)
	return _u
}

// SetNillableOpportunities sets the "opportunities" field if the given value is not nil.
func (_u *DeepAnalysisResultUpdate) SetNillableOpportunities(v *string) *DeepAnalysisResultUpdate {
	if v != nil {
		_u.SetOpportunities(*v)
	}
	return _u
}

// ClearOpportunities clears the value of the "opportunities" field.
func (_u *DeepAnalysisResultUpdate) ClearOpportunities() *DeepAnalysisResultUpdate {
	_u.mutation.ClearOpportunities()
	return _u
}

// SetRisks sets the "risks" field.
func (_u *DeepAnalysisResultUpdate) SetRisks(v string) *DeepAnalysisResultUpdate {
	_u.mutation.SetRisks(v)
	return _u
}

// SetNillableRisks sets the "risks" field if the given value is not nil.
func (_u *DeepAnalysisResultUpdate) SetNillableRisks(v *string) *DeepAnalysisResultUpdate {
	if v != nil {
		_u.SetRisks(*v)
	}
	return _u
}

// ClearRisks clears the value of the "risks" field.
func (_u *DeepAnalysisResultUpdate) ClearRisks() *DeepAnalysisResultUpdate {
	_u.mutation.ClearRisks()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DeepAnalysisResultUpdate) SetCreatedAt(v time.Time) *DeepAnalysisResultUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DeepAnalysisResultUpdate) SetNillableCreatedAt(v *time.Time) *DeepAnalysisResultUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetReportRunID sets the "report_run" edge to the ReportRun entity by ID.
func (_u *DeepAnalysisResultUpdate) SetReportRunID(id int) *DeepAnalysisResultUpdate {
	_u.mutation.SetReportRunID(id)
	return _u
}

// SetNillableReportRunID sets the "report_run" edge to the ReportRun entity by ID if the given value is not nil.
func (_u *DeepAnalysisResultUpdate) SetNillableReportRunID(id *int) *DeepAnalysisResultUpdate {
	if id != nil {
		_u = _u.SetReportRunID(*id)
	}
	return _u
}

// SetReportRun sets the "report_run" edge to the ReportRun entity.
func (_u *DeepAnalysisResultUpdate) SetReportRun(v *ReportRun) *DeepAnalysisResultUpdate {
	return _u.SetReportRunID(v.ID)
}

// AddActionGuideIDs adds the "action_guides" edge to the ActionGuide entity by IDs.
func (_u *DeepAnalysisResultUpdate) AddActionGuideIDs(ids ...int) *DeepAnalysisResultUpdate {
	_u.mutation.AddActionGuideIDs(ids...)
	return _u
}

// AddActionGuides adds the "action_guides" edges to the ActionGuide entity.
func (_u *DeepAnalysisResultUpdate) AddActionGuides(v ...*ActionGuide) *DeepAnalysisResultUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddActionGuideIDs(ids...)
}

// Mutation returns the DeepAnalysisResultMutation object of the builder.
func (_u *DeepAnalysisResultUpdate) Mutation() *DeepAnalysisResultMutation {
	return _u.mutation
}

// ClearReportRun clears the "report_run" edge to the ReportRun entity.
func (_u *DeepAnalysisResultUpdate) ClearReportRun() *DeepAnalysisResultUpdate {
	_u.mutation.ClearReportRun()
	return _u
}

// ClearActionGuides clears all "action_guides" edges to the ActionGuide entity.
func (_u *DeepAnalysisResultUpdate) ClearActionGuides() *DeepAnalysisResultUpdate {
	_u.mutation.ClearActionGuides()
	return _u
}

// RemoveActionGuideIDs removes the "action_guides" edge to ActionGuide entities by IDs.
func (_u *DeepAnalysisResultUpdate) RemoveActionGuideIDs(ids ...int) *DeepAnalysisResultUpdate {
	_u.mutation.RemoveActionGuideIDs(ids...)
	return _u
}

// RemoveActionGuides removes "action_guides" edges to ActionGuide entities.
func (_u *DeepAnalysisResultUpdate) RemoveActionGuides(v ...*ActionGuide) *DeepAnalysisResultUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveActionGuideIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeepAnalysisResultUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeepAnalysisResultUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeepAnalysisResultUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeepAnalysisResultUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DeepAnalysisResultUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DeepAnalysisResultUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DeepAnalysisResultUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(deepanalysisresult.Table, deepanalysisresult.Columns, sqlgraph.NewFieldSpec(deepanalysisresult.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MacroTrends(); ok {
		_spec.SetField(deepanalysisresult.FieldMacroTrends, field.TypeString, value)
	}
	if _u.mutation.MacroTrendsCleared() {
		_spec.ClearField(deepanalysisresult.FieldMacroTrends, field.TypeString)
	}
	if value, ok := _u.mutation.Opportunities(); ok {
		_spec.SetField(deepanalysisresult.FieldOpportunities, field.TypeString, value)
	}
	if _u.mutation.OpportunitiesCleared() {
		_spec.ClearField(deepanalysisresult.FieldOpportunities, field.TypeString)
	}
	if value, ok := _u.mutation.Risks(); ok {
		_spec.SetField(deepanalysisresult.FieldRisks, field.TypeString, value)
	}
	if _u.mutation.RisksCleared() {
		_spec.ClearField(deepanalysisresult.FieldRisks, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(deepanalysisresult.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ReportRunCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deepanalysisresult.ReportRunTable,
			Columns: []string{deepanalysisresult.ReportRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportrun.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReportRunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deepanalysisresult.ReportRunTable,
			Columns: []string{deepanalysisresult.ReportRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportrun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ActionGuidesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deepanalysisresult.ActionGuidesTable,
			Columns: []string{deepanalysisresult.ActionGuidesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionguide.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedActionGuidesIDs(); len(nodes) > 0 && !_u.mutation.ActionGuidesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deepanalysisresult.ActionGuidesTable,
			Columns: []string{deepanalysisresult.ActionGuidesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionguide.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActionGuidesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deepanalysisresult.ActionGuidesTable,
			Columns: []string{deepanalysisresult.ActionGuidesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionguide.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deepanalysisresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeepAnalysisResultUpdateOne is the builder for updating a single DeepAnalysisResult entity.
type DeepAnalysisResultUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DeepAnalysisResultMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetRunID sets the "run_id" field.
func (_u *DeepAnalysisResultUpdateOne) SetRunID(v int) *DeepAnalysisResultUpdateOne {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *DeepAnalysisResultUpdateOne) SetNillableRunID(v *int) *DeepAnalysisResultUpdateOne {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// ClearRunID clears the value of the "run_id" field.
func (_u *DeepAnalysisResultUpdateOne) ClearRunID() *DeepAnalysisResultUpdateOne {
	_u.mutation.ClearRunID()
	return _u
}

// SetMacroTrends sets the "macro_trends" field.
func (_u *DeepAnalysisResultUpdateOne) SetMacroTrends(v string) *DeepAnalysisResultUpdateOne {
	_u.mutation.SetMacroTrends(v)
	return _u
}

// SetNillableMacroTrends sets the "macro_trends" field if the given value is not nil.
func (_u *DeepAnalysisResultUpdateOne) SetNillableMacroTrends(v *string) *DeepAnalysisResultUpdateOne {
	if v != nil {
		_u.SetMacroTrends(*v)
	}
	return _u
}

// ClearMacroTrends clears the value of the "macro_trends" field.
func (_u *DeepAnalysisResultUpdateOne) ClearMacroTrends() *DeepAnalysisResultUpdateOne {
	_u.mutation.ClearMacroTrends()
	return _u
}

// SetOpportunities sets the "opportunities" field.
func (_u *DeepAnalysisResultUpdateOne) SetOpportunities(v string) *DeepAnalysisResultUpdateOne {
	_u.mutation.SetOpportunities(v)
	return _u
}

// SetNillableOpportunities sets the "opportunities" field if the given value is not nil.
func (_u *DeepAnalysisResultUpdateOne) SetNillableOpportunities(v *string) *DeepAnalysisResultUpdateOne {
	if v != nil {
		_u.SetOpportunities(*v)
	}
	return _u
}

// ClearOpportunities clears the value of the "opportunities" field.
func (_u *DeepAnalysisResultUpdateOne) ClearOpportunities() *DeepAnalysisResultUpdateOne {
	_u.mutation.ClearOpportunities()
	return _u
}

// SetRisks sets the "risks" field.
func (_u *DeepAnalysisResultUpdateOne) SetRisks(v string) *DeepAnalysisResultUpdateOne {
	_u.mutation.SetRisks(v)
	return _u
}

// SetNillableRisks sets the "risks" field if the given value is not nil.
func (_u *DeepAnalysisResultUpdateOne) SetNillableRisks(v *string) *DeepAnalysisResultUpdateOne {
	if v != nil {
		_u.SetRisks(*v)
	}
	return _u
}

// ClearRisks clears the value of the "risks" field.
func (_u *DeepAnalysisResultUpdateOne) ClearRisks() *DeepAnalysisResultUpdateOne {
	_u.mutation.ClearRisks()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DeepAnalysisResultUpdateOne) SetCreatedAt(v time.Time) *DeepAnalysisResultUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DeepAnalysisResultUpdateOne) SetNillableCreatedAt(v *time.Time) *DeepAnalysisResultUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetReportRunID sets the "report_run" edge to the ReportRun entity by ID.
func (_u *DeepAnalysisResultUpdateOne) SetReportRunID(id int) *DeepAnalysisResultUpdateOne {
	_u.mutation.SetReportRunID(id)
	return _u
}

// SetNillableReportRunID sets the "report_run" edge to the ReportRun entity by ID if the given value is not nil.
func (_u *DeepAnalysisResultUpdateOne) SetNillableReportRunID(id *int) *DeepAnalysisResultUpdateOne {
	if id != nil {
		_u = _u.SetReportRunID(*id)
	}
	return _u
}

// SetReportRun sets the "report_run" edge to the ReportRun entity.
func (_u *DeepAnalysisResultUpdateOne) SetReportRun(v *ReportRun) *DeepAnalysisResultUpdateOne {
	return _u.SetReportRunID(v.ID)
}

// AddActionGuideIDs adds the "action_guides" edge to the ActionGuide entity by IDs.
func (_u *DeepAnalysisResultUpdateOne) AddActionGuideIDs(ids ...int) *DeepAnalysisResultUpdateOne {
	_u.mutation.AddActionGuideIDs(ids...)
	return _u
}

// AddActionGuides adds the "action_guides" edges to the ActionGuide entity.
func (_u *DeepAnalysisResultUpdateOne) AddActionGuides(v ...*ActionGuide) *DeepAnalysisResultUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddActionGuideIDs(ids...)
}

// Mutation returns the DeepAnalysisResultMutation object of the builder.
func (_u *DeepAnalysisResultUpdateOne) Mutation() *DeepAnalysisResultMutation {
	return _u.mutation
}

// ClearReportRun clears the "report_run" edge to the ReportRun entity.
func (_u *DeepAnalysisResultUpdateOne) ClearReportRun() *DeepAnalysisResultUpdateOne {
	_u.mutation.ClearReportRun()
	return _u
}

// ClearActionGuides clears all "action_guides" edges to the ActionGuide entity.
func (_u *DeepAnalysisResultUpdateOne) ClearActionGuides() *DeepAnalysisResultUpdateOne {
	_u.mutation.ClearActionGuides()
	return _u
}

// RemoveActionGuideIDs removes the "action_guides" edge to ActionGuide entities by IDs.
func (_u *DeepAnalysisResultUpdateOne) RemoveActionGuideIDs(ids ...int) *DeepAnalysisResultUpdateOne {
	_u.mutation.RemoveActionGuideIDs(ids...)
	return _u
}

// RemoveActionGuides removes "action_guides" edges to ActionGuide entities.
func (_u *DeepAnalysisResultUpdateOne) RemoveActionGuides(v ...*ActionGuide) *DeepAnalysisResultUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveActionGuideIDs(ids...)
}

// Where appends a list predicates to the DeepAnalysisResultUpdate builder.
func (_u *DeepAnalysisResultUpdateOne) Where(ps ...predicate.DeepAnalysisResult) *DeepAnalysisResultUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeepAnalysisResultUpdateOne) Select(field string, fields ...string) *DeepAnalysisResultUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DeepAnalysisResult entity.
func (_u *DeepAnalysisResultUpdateOne) Save(ctx context.Context) (*DeepAnalysisResult, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeepAnalysisResultUpdateOne) SaveX(ctx context.Context) *DeepAnalysisResult {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeepAnalysisResultUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeepAnalysisResultUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DeepAnalysisResultUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DeepAnalysisResultUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DeepAnalysisResultUpdateOne) sqlSave(ctx context.Context) (_node *DeepAnalysisResult, err error) {
	_spec := sqlgraph.NewUpdateSpec(deepanalysisresult.Table, deepanalysisresult.Columns, sqlgraph.NewFieldSpec(deepanalysisresult.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DeepAnalysisResult.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deepanalysisresult.FieldID)
		for _, f := range fields {
			if !deepanalysisresult.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deepanalysisresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MacroTrends(); ok {
		_spec.SetField(deepanalysisresult.FieldMacroTrends, field.TypeString, value)
	}
	if _u.mutation.MacroTrendsCleared() {
		_spec.ClearField(deepanalysisresult.FieldMacroTrends, field.TypeString)
	}
	if value, ok := _u.mutation.Opportunities(); ok {
		_spec.SetField(deepanalysisresult.FieldOpportunities, field.TypeString, value)
	}
	if _u.mutation.OpportunitiesCleared() {
		_spec.ClearField(deepanalysisresult.FieldOpportunities, field.TypeString)
	}
	if value, ok := _u.mutation.Risks(); ok {
		_spec.SetField(deepanalysisresult.FieldRisks, field.TypeString, value)
	}
	if _u.mutation.RisksCleared() {
		_spec.ClearField(deepanalysisresult.FieldRisks, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(deepanalysisresult.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ReportRunCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deepanalysisresult.ReportRunTable,
			Columns: []string{deepanalysisresult.ReportRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportrun.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReportRunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deepanalysisresult.ReportRunTable,
			Columns: []string{deepanalysisresult.ReportRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportrun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ActionGuidesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deepanalysisresult.ActionGuidesTable,
			Columns: []string{deepanalysisresult.ActionGuidesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionguide.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedActionGuidesIDs(); len(nodes) > 0 && !_u.mutation.ActionGuidesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deepanalysisresult.ActionGuidesTable,
			Columns: []string{deepanalysisresult.ActionGuidesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionguide.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActionGuidesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deepanalysisresult.ActionGuidesTable,
			Columns: []string{deepanalysisresult.ActionGuidesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionguide.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &DeepAnalysisResult{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deepanalysisresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
