// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/iWorld-y/domain_radar/ent/domainreport"
	"github.com/iWorld-y/domain_radar/ent/reportrun"
)

// DomainReport is the model entity for the DomainReport schema.
type DomainReport struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RunID holds the value of the "run_id" field.
	RunID int `json:"run_id,omitempty"`
	// DomainName holds the value of the "domain_name" field.
	DomainName string `json:"domain_name,omitempty"`
	// Overview holds the value of the "overview" field.
	Overview string `json:"overview,omitempty"`
	// Trends holds the value of the "trends" field.
	Trends string `json:"trends,omitempty"`
	// Score holds the value of the "score" field.
	Score int `json:"score,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DomainReportQuery when eager-loading is set.
	Edges        DomainReportEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DomainReportEdges holds the relations/edges for other nodes in the graph.
type DomainReportEdges struct {
	// ReportRun holds the value of the report_run edge.
	ReportRun *ReportRun `json:"report_run,omitempty"`
	// Articles holds the value of the articles edge.
	Articles []*Article `json:"articles,omitempty"`
	// KeyEvents holds the value of the key_events edge.
	KeyEvents []*KeyEvent `json:"key_events,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ReportRunOrErr returns the ReportRun value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DomainReportEdges) ReportRunOrErr() (*ReportRun, error) {
	if e.ReportRun != nil {
		return e.ReportRun, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: reportrun.Label}
	}
	return nil, &NotLoadedError{edge: "report_run"}
}

// ArticlesOrErr returns the Articles value or an error if the edge
// was not loaded in eager-loading.
func (e DomainReportEdges) ArticlesOrErr() ([]*Article, error) {
	if e.loadedTypes[1] {
		return e.Articles, nil
	}
	return nil, &NotLoadedError{edge: "articles"}
}

// KeyEventsOrErr returns the KeyEvents value or an error if the edge
// was not loaded in eager-loading.
func (e DomainReportEdges) KeyEventsOrErr() ([]*KeyEvent, error) {
	if e.loadedTypes[2] {
		return e.KeyEvents, nil
	}
	return nil, &NotLoadedError{edge: "key_events"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DomainReport) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case domainreport.FieldID, domainreport.FieldRunID, domainreport.FieldScore:
			values[i] = new(sql.NullInt64)
		case domainreport.FieldDomainName, domainreport.FieldOverview, domainreport.FieldTrends:
			values[i] = new(sql.NullString)
		case domainreport.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DomainReport fields.
func (_m *DomainReport) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case domainreport.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case domainreport.FieldRunID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field run_id", values[i])
			} else if value.Valid {
				_m.RunID = int(value.Int64)
			}
		case domainreport.FieldDomainName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field domain_name", values[i])
			} else if value.Valid {
				_m.DomainName = value.String
			}
		case domainreport.FieldOverview:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field overview", values[i])
			} else if value.Valid {
				_m.Overview = value.String
			}
		case domainreport.FieldTrends:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trends", values[i])
			} else if value.Valid {
				_m.Trends = value.String
			}
		case domainreport.FieldScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field score", values[i])
			} else if value.Valid {
				_m.Score = int(value.Int64)
			}
		case domainreport.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DomainReport.
// This includes values selected through modifiers, order, etc.
func (_m *DomainReport) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryReportRun queries the "report_run" edge of the DomainReport entity.
func (_m *DomainReport) QueryReportRun() *ReportRunQuery {
	return NewDomainReportClient(_m.config).QueryReportRun(_m)
}

// QueryArticles queries the "articles" edge of the DomainReport entity.
func (_m *DomainReport) QueryArticles() *ArticleQuery {
	return NewDomainReportClient(_m.config).QueryArticles(_m)
}

// QueryKeyEvents queries the "key_events" edge of the DomainReport entity.
func (_m *DomainReport) QueryKeyEvents() *KeyEventQuery {
	return NewDomainReportClient(_m.config).QueryKeyEvents(_m)
}

// Update returns a builder for updating this DomainReport.
// Note that you need to call DomainReport.Unwrap() before calling this method if this DomainReport
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DomainReport) Update() *DomainReportUpdateOne {
	return NewDomainReportClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DomainReport entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DomainReport) Unwrap() *DomainReport {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DomainReport is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DomainReport) String() string {
	var builder strings.Builder
	builder.WriteString("DomainReport(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("run_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RunID))
	builder.WriteString(", ")
	builder.WriteString("domain_name=")
	builder.WriteString(_m.DomainName)
	builder.WriteString(", ")
	builder.WriteString("overview=")
	builder.WriteString(_m.Overview)
	builder.WriteString(", ")
	builder.WriteString("trends=")
	builder.WriteString(_m.Trends)
	builder.WriteString(", ")
	builder.WriteString("score=")
	builder.WriteString(fmt.Sprintf("%v", _m.Score))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DomainReports is a parsable slice of DomainReport.
type DomainReports []*DomainReport
