// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iWorld-y/domain_radar/ent/deepanalysisresult"
	"github.com/iWorld-y/domain_radar/ent/domainreport"
	"github.com/iWorld-y/domain_radar/ent/predicate"
	"github.com/iWorld-y/domain_radar/ent/reportrun"
)

// ReportRunUpdate is the builder for updating ReportRun entities.
type ReportRunUpdate struct {
	config
	hooks     []Hook
	mutation  *ReportRunMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ReportRunUpdate builder.
func (_u *ReportRunUpdate) Where(ps ...predicate.ReportRun) *ReportRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ReportRunUpdate) SetCreatedAt(v time.Time) *ReportRunUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ReportRunUpdate) SetNillableCreatedAt(v *time.Time) *ReportRunUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddDomainReportIDs adds the "domain_reports" edge to the DomainReport entity by IDs.
func (_u *ReportRunUpdate) AddDomainReportIDs(ids ...int) *ReportRunUpdate {
	_u.mutation.AddDomainReportIDs(ids...)
	return _u
}

// AddDomainReports adds the "domain_reports" edges to the DomainReport entity.
func (_u *ReportRunUpdate) AddDomainReports(v ...*DomainReport) *ReportRunUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDomainReportIDs(ids...)
}

// AddDeepAnalysisResultIDs adds the "deep_analysis_results" edge to the DeepAnalysisResult entity by IDs.
func (_u *ReportRunUpdate) AddDeepAnalysisResultIDs(ids ...int) *ReportRunUpdate {
	_u.mutation.AddDeepAnalysisResultIDs(ids...)
	return _u
}

// AddDeepAnalysisResults adds the "deep_analysis_results" edges to the DeepAnalysisResult entity.
func (_u *ReportRunUpdate) AddDeepAnalysisResults(v ...*DeepAnalysisResult) *ReportRunUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeepAnalysisResultIDs(ids...)
}

// Mutation returns the ReportRunMutation object of the builder.
func (_u *ReportRunUpdate) Mutation() *ReportRunMutation {
	return _u.mutation
}

// ClearDomainReports clears all "domain_reports" edges to the DomainReport entity.
func (_u *ReportRunUpdate) ClearDomainReports() *ReportRunUpdate {
	_u.mutation.ClearDomainReports()
	return _u
}

// RemoveDomainReportIDs removes the "domain_reports" edge to DomainReport entities by IDs.
func (_u *ReportRunUpdate) RemoveDomainReportIDs(ids ...int) *ReportRunUpdate {
	_u.mutation.RemoveDomainReportIDs(ids...)
	return _u
}

// RemoveDomainReports removes "domain_reports" edges to DomainReport entities.
func (_u *ReportRunUpdate) RemoveDomainReports(v ...*DomainReport) *ReportRunUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDomainReportIDs(ids...)
}

// ClearDeepAnalysisResults clears all "deep_analysis_results" edges to the DeepAnalysisResult entity.
func (_u *ReportRunUpdate) ClearDeepAnalysisResults() *ReportRunUpdate {
	_u.mutation.ClearDeepAnalysisResults()
	return _u
}

// RemoveDeepAnalysisResultIDs removes the "deep_analysis_results" edge to DeepAnalysisResult entities by IDs.
func (_u *ReportRunUpdate) RemoveDeepAnalysisResultIDs(ids ...int) *ReportRunUpdate {
	_u.mutation.RemoveDeepAnalysisResultIDs(ids...)
	return _u
}

// RemoveDeepAnalysisResults removes "deep_analysis_results" edges to DeepAnalysisResult entities.
func (_u *ReportRunUpdate) RemoveDeepAnalysisResults(v ...*DeepAnalysisResult) *ReportRunUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeepAnalysisResultIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReportRunUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReportRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReportRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReportRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ReportRunUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ReportRunUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ReportRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(reportrun.Table, reportrun.Columns, sqlgraph.NewFieldSpec(reportrun.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(reportrun.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.DomainReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportrun.DomainReportsTable,
			Columns: []string{reportrun.DomainReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domainreport.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDomainReportsIDs(); len(nodes) > 0 && !_u.mutation.DomainReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportrun.DomainReportsTable,
			Columns: []string{reportrun.DomainReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domainreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DomainReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportrun.DomainReportsTable,
			Columns: []string{reportrun.DomainReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domainreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeepAnalysisResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportrun.DeepAnalysisResultsTable,
			Columns: []string{reportrun.DeepAnalysisResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deepanalysisresult.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDeepAnalysisResultsIDs(); len(nodes) > 0 && !_u.mutation.DeepAnalysisResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportrun.DeepAnalysisResultsTable,
			Columns: []string{reportrun.DeepAnalysisResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deepanalysisresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeepAnalysisResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportrun.DeepAnalysisResultsTable,
			Columns: []string{reportrun.DeepAnalysisResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deepanalysisresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reportrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReportRunUpdateOne is the builder for updating a single ReportRun entity.
type ReportRunUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ReportRunMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreatedAt sets the "created_at" field.
func (_u *ReportRunUpdateOne) SetCreatedAt(v time.Time) *ReportRunUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ReportRunUpdateOne) SetNillableCreatedAt(v *time.Time) *ReportRunUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddDomainReportIDs adds the "domain_reports" edge to the DomainReport entity by IDs.
func (_u *ReportRunUpdateOne) AddDomainReportIDs(ids ...int) *ReportRunUpdateOne {
	_u.mutation.AddDomainReportIDs(ids...)
	return _u
}

// AddDomainReports adds the "domain_reports" edges to the DomainReport entity.
func (_u *ReportRunUpdateOne) AddDomainReports(v ...*DomainReport) *ReportRunUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDomainReportIDs(ids...)
}

// AddDeepAnalysisResultIDs adds the "deep_analysis_results" edge to the DeepAnalysisResult entity by IDs.
func (_u *ReportRunUpdateOne) AddDeepAnalysisResultIDs(ids ...int) *ReportRunUpdateOne {
	_u.mutation.AddDeepAnalysisResultIDs(ids...)
	return _u
}

// AddDeepAnalysisResults adds the "deep_analysis_results" edges to the DeepAnalysisResult entity.
func (_u *ReportRunUpdateOne) AddDeepAnalysisResults(v ...*DeepAnalysisResult) *ReportRunUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeepAnalysisResultIDs(ids...)
}

// Mutation returns the ReportRunMutation object of the builder.
func (_u *ReportRunUpdateOne) Mutation() *ReportRunMutation {
	return _u.mutation
}

// ClearDomainReports clears all "domain_reports" edges to the DomainReport entity.
func (_u *ReportRunUpdateOne) ClearDomainReports() *ReportRunUpdateOne {
	_u.mutation.ClearDomainReports()
	return _u
}

// RemoveDomainReportIDs removes the "domain_reports" edge to DomainReport entities by IDs.
func (_u *ReportRunUpdateOne) RemoveDomainReportIDs(ids ...int) *ReportRunUpdateOne {
	_u.mutation.RemoveDomainReportIDs(ids...)
	return _u
}

// RemoveDomainReports removes "domain_reports" edges to DomainReport entities.
func (_u *ReportRunUpdateOne) RemoveDomainReports(v ...*DomainReport) *ReportRunUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDomainReportIDs(ids...)
}

// ClearDeepAnalysisResults clears all "deep_analysis_results" edges to the DeepAnalysisResult entity.
func (_u *ReportRunUpdateOne) ClearDeepAnalysisResults() *ReportRunUpdateOne {
	_u.mutation.ClearDeepAnalysisResults()
	return _u
}

// RemoveDeepAnalysisResultIDs removes the "deep_analysis_results" edge to DeepAnalysisResult entities by IDs.
func (_u *ReportRunUpdateOne) RemoveDeepAnalysisResultIDs(ids ...int) *ReportRunUpdateOne {
	_u.mutation.RemoveDeepAnalysisResultIDs(ids...)
	return _u
}

// RemoveDeepAnalysisResults removes "deep_analysis_results" edges to DeepAnalysisResult entities.
func (_u *ReportRunUpdateOne) RemoveDeepAnalysisResults(v ...*DeepAnalysisResult) *ReportRunUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeepAnalysisResultIDs(ids...)
}

// Where appends a list predicates to the ReportRunUpdate builder.
func (_u *ReportRunUpdateOne) Where(ps ...predicate.ReportRun) *ReportRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReportRunUpdateOne) Select(field string, fields ...string) *ReportRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReportRun entity.
func (_u *ReportRunUpdateOne) Save(ctx context.Context) (*ReportRun, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReportRunUpdateOne) SaveX(ctx context.Context) *ReportRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReportRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReportRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ReportRunUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ReportRunUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ReportRunUpdateOne) sqlSave(ctx context.Context) (_node *ReportRun, err error) {
	_spec := sqlgraph.NewUpdateSpec(reportrun.Table, reportrun.Columns, sqlgraph.NewFieldSpec(reportrun.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReportRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reportrun.FieldID)
		for _, f := range fields {
			if !reportrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != reportrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(reportrun.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.DomainReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportrun.DomainReportsTable,
			Columns: []string{reportrun.DomainReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domainreport.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDomainReportsIDs(); len(nodes) > 0 && !_u.mutation.DomainReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportrun.DomainReportsTable,
			Columns: []string{reportrun.DomainReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domainreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DomainReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportrun.DomainReportsTable,
			Columns: []string{reportrun.DomainReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domainreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeepAnalysisResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportrun.DeepAnalysisResultsTable,
			Columns: []string{reportrun.DeepAnalysisResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deepanalysisresult.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDeepAnalysisResultsIDs(); len(nodes) > 0 && !_u.mutation.DeepAnalysisResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportrun.DeepAnalysisResultsTable,
			Columns: []string{reportrun.DeepAnalysisResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deepanalysisresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeepAnalysisResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportrun.DeepAnalysisResultsTable,
			Columns: []string{reportrun.DeepAnalysisResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deepanalysisresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ReportRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reportrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
