// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iWorld-y/domain_radar/ent/deepanalysisresult"
	"github.com/iWorld-y/domain_radar/ent/domainreport"
	"github.com/iWorld-y/domain_radar/ent/reportrun"
)

// ReportRunCreate is the builder for creating a ReportRun entity.
type ReportRunCreate struct {
	config
	mutation *ReportRunMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReportRunCreate) SetCreatedAt(v time.Time) *ReportRunCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReportRunCreate) SetNillableCreatedAt(v *time.Time) *ReportRunCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ReportRunCreate) SetID(v int) *ReportRunCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddDomainReportIDs adds the "domain_reports" edge to the DomainReport entity by IDs.
func (_c *ReportRunCreate) AddDomainReportIDs(ids ...int) *ReportRunCreate {
	_c.mutation.AddDomainReportIDs(ids...)
	return _c
}

// AddDomainReports adds the "domain_reports" edges to the DomainReport entity.
func (_c *ReportRunCreate) AddDomainReports(v ...*DomainReport) *ReportRunCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDomainReportIDs(ids...)
}

// AddDeepAnalysisResultIDs adds the "deep_analysis_results" edge to the DeepAnalysisResult entity by IDs.
func (_c *ReportRunCreate) AddDeepAnalysisResultIDs(ids ...int) *ReportRunCreate {
	_c.mutation.AddDeepAnalysisResultIDs(ids...)
	return _c
}

// AddDeepAnalysisResults adds the "deep_analysis_results" edges to the DeepAnalysisResult entity.
func (_c *ReportRunCreate) AddDeepAnalysisResults(v ...*DeepAnalysisResult) *ReportRunCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDeepAnalysisResultIDs(ids...)
}

// Mutation returns the ReportRunMutation object of the builder.
func (_c *ReportRunCreate) Mutation() *ReportRunMutation {
	return _c.mutation
}

// Save creates the ReportRun in the database.
func (_c *ReportRunCreate) Save(ctx context.Context) (*ReportRun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReportRunCreate) SaveX(ctx context.Context) *ReportRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReportRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReportRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReportRunCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := reportrun.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReportRunCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ReportRun.created_at"`)}
	}
	return nil
}

func (_c *ReportRunCreate) sqlSave(ctx context.Context) (*ReportRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReportRunCreate) createSpec() (*ReportRun, *sqlgraph.CreateSpec) {
	var (
		_node = &ReportRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(reportrun.Table, sqlgraph.NewFieldSpec(reportrun.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(reportrun.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.DomainReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportrun.DomainReportsTable,
			Columns: []string{reportrun.DomainReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domainreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DeepAnalysisResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportrun.DeepAnalysisResultsTable,
			Columns: []string{reportrun.DeepAnalysisResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deepanalysisresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ReportRunCreateBulk is the builder for creating many ReportRun entities in bulk.
type ReportRunCreateBulk struct {
	config
	err      error
	builders []*ReportRunCreate
}

// Save creates the ReportRun entities in the database.
func (_c *ReportRunCreateBulk) Save(ctx context.Context) ([]*ReportRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReportRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReportRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReportRunCreateBulk) SaveX(ctx context.Context) []*ReportRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReportRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReportRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
