// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/iWorld-y/domain_radar/ent/deepanalysisresult"
	"github.com/iWorld-y/domain_radar/ent/domainreport"
	"github.com/iWorld-y/domain_radar/ent/reportrun"
	"github.com/iWorld-y/domain_radar/ent/schema"
	"github.com/iWorld-y/domain_radar/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	deepanalysisresultFields := schema.DeepAnalysisResult{}.Fields()
	_ = deepanalysisresultFields
	// deepanalysisresultDescCreatedAt is the schema descriptor for created_at field.
	deepanalysisresultDescCreatedAt := deepanalysisresultFields[4].Descriptor()
	// deepanalysisresult.DefaultCreatedAt holds the default value on creation for the created_at field.
	deepanalysisresult.DefaultCreatedAt = deepanalysisresultDescCreatedAt.Default.(func() time.Time)
	domainreportFields := schema.DomainReport{}.Fields()
	_ = domainreportFields
	// domainreportDescCreatedAt is the schema descriptor for created_at field.
	domainreportDescCreatedAt := domainreportFields[5].Descriptor()
	// domainreport.DefaultCreatedAt holds the default value on creation for the created_at field.
	domainreport.DefaultCreatedAt = domainreportDescCreatedAt.Default.(func() time.Time)
	reportrunFields := schema.ReportRun{}.Fields()
	_ = reportrunFields
	// reportrunDescCreatedAt is the schema descriptor for created_at field.
	reportrunDescCreatedAt := reportrunFields[0].Descriptor()
	// reportrun.DefaultCreatedAt holds the default value on creation for the created_at field.
	reportrun.DefaultCreatedAt = reportrunDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[2].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}
