// Code generated by ent, DO NOT EDIT.

package article

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the article type in the database.
	Label = "article"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDomainReportID holds the string denoting the domain_report_id field in the database.
	FieldDomainReportID = "domain_report_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldLink holds the string denoting the link field in the database.
	FieldLink = "link"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldPubDate holds the string denoting the pub_date field in the database.
	FieldPubDate = "pub_date"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// EdgeDomainReport holds the string denoting the domain_report edge name in mutations.
	EdgeDomainReport = "domain_report"
	// Table holds the table name of the article in the database.
	Table = "articles"
	// DomainReportTable is the table that holds the domain_report relation/edge.
	DomainReportTable = "articles"
	// DomainReportInverseTable is the table name for the DomainReport entity.
	// It exists in this package in order to avoid circular dependency with the "domainreport" package.
	DomainReportInverseTable = "domain_reports"
	// DomainReportColumn is the table column denoting the domain_report relation/edge.
	DomainReportColumn = "domain_report_id"
)

// Columns holds all SQL columns for article fields.
var Columns = []string{
	FieldID,
	FieldDomainReportID,
	FieldTitle,
	FieldLink,
	FieldSource,
	FieldPubDate,
	FieldContent,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Article queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDomainReportID orders the results by the domain_report_id field.
func ByDomainReportID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDomainReportID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByLink orders the results by the link field.
func ByLink(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLink, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByPubDate orders the results by the pub_date field.
func ByPubDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPubDate, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByDomainReportField orders the results by domain_report field.
func ByDomainReportField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDomainReportStep(), sql.OrderByField(field, opts...))
	}
}
func newDomainReportStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DomainReportInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DomainReportTable, DomainReportColumn),
	)
}
