// Code generated by ent, DO NOT EDIT.

package deepanalysisresult

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the deepanalysisresult type in the database.
	Label = "deep_analysis_result"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRunID holds the string denoting the run_id field in the database.
	FieldRunID = "run_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldMacroTrends holds the string denoting the macro_trends field in the database.
	FieldMacroTrends = "macro_trends"
	// FieldOpportunities holds the string denoting the opportunities field in the database.
	FieldOpportunities = "opportunities"
	// FieldRisks holds the string denoting the risks field in the database.
	FieldRisks = "risks"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeReportRun holds the string denoting the report_run edge name in mutations.
	EdgeReportRun = "report_run"
	// EdgeActionGuides holds the string denoting the action_guides edge name in mutations.
	EdgeActionGuides = "action_guides"
	// Table holds the table name of the deepanalysisresult in the database.
	Table = "deep_analysis_results"
	// ReportRunTable is the table that holds the report_run relation/edge.
	ReportRunTable = "deep_analysis_results"
	// ReportRunInverseTable is the table name for the ReportRun entity.
	// It exists in this package in order to avoid circular dependency with the "reportrun" package.
	ReportRunInverseTable = "report_runs"
	// ReportRunColumn is the table column denoting the report_run relation/edge.
	ReportRunColumn = "run_id"
	// ActionGuidesTable is the table that holds the action_guides relation/edge.
	ActionGuidesTable = "action_guides"
	// ActionGuidesInverseTable is the table name for the ActionGuide entity.
	// It exists in this package in order to avoid circular dependency with the "actionguide" package.
	ActionGuidesInverseTable = "action_guides"
	// ActionGuidesColumn is the table column denoting the action_guides relation/edge.
	ActionGuidesColumn = "deep_analysis_id"
)

// Columns holds all SQL columns for deepanalysisresult fields.
var Columns = []string{
	FieldID,
	FieldRunID,
	FieldUserID,
	FieldMacroTrends,
	FieldOpportunities,
	FieldRisks,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the DeepAnalysisResult queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRunID orders the results by the run_id field.
func ByRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByMacroTrends orders the results by the macro_trends field.
func ByMacroTrends(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMacroTrends, opts...).ToFunc()
}

// ByOpportunities orders the results by the opportunities field.
func ByOpportunities(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOpportunities, opts...).ToFunc()
}

// ByRisks orders the results by the risks field.
func ByRisks(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRisks, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByReportRunField orders the results by report_run field.
func ByReportRunField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReportRunStep(), sql.OrderByField(field, opts...))
	}
}

// ByActionGuidesCount orders the results by action_guides count.
func ByActionGuidesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newActionGuidesStep(), opts...)
	}
}

// ByActionGuides orders the results by action_guides terms.
func ByActionGuides(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newActionGuidesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newReportRunStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReportRunInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ReportRunTable, ReportRunColumn),
	)
}
func newActionGuidesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ActionGuidesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ActionGuidesTable, ActionGuidesColumn),
	)
}
