// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ActionGuide is the predicate function for actionguide builders.
type ActionGuide func(*sql.Selector)

// Article is the predicate function for article builders.
type Article func(*sql.Selector)

// DeepAnalysisResult is the predicate function for deepanalysisresult builders.
type DeepAnalysisResult func(*sql.Selector)

// DomainReport is the predicate function for domainreport builders.
type DomainReport func(*sql.Selector)

// KeyEvent is the predicate function for keyevent builders.
type KeyEvent func(*sql.Selector)

// ReportRun is the predicate function for reportrun builders.
type ReportRun func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
